### ISSUE TITLE
Convention for longitude in Opendrift.

### ISSUE THREAD

**Issue by simonweppe** [OpenDrift/opendrift#100]
Hi there,

It seems that Opendrift uses  longitudes in the [-180,180] range internally  via pyproj. The function seed_elements() appears to do the correct conversion if we input an initial element longitude that is > 180deg.

What would happen though if the netcdf data input uses the convention [0,360] for longitude ? is this going to be handled correctly ?  I never came across a case like that in my past applications, but my latest case uses data that spans across that 180degW line. 

I'll dive in the code to have a look but curious for tips on how/where this is covered.

Thanks 
Simon

**Comment by simonweppe** [comment]
An update on this.
Im running into issues when the reader longitude runs over the +180 degT line.
The data from the reader is correctly loaded, with extents as in file e.g. `lon = [176.0-184.0]`. If I test the interpolation for given position beyond the 180 degT line, this returns a correct value e.g. 
`o.get_environment(['y_sea_water_velocity'],time=reader_ocean.start_time, lon=numpy.array(181.0),lat=numpy.array(-45.0),z=numpy.array([0.0]), profiles=None) `

However, Opendrift since internally uses longitude in the [-180,180] range, and converts any release positions with a longitude>180 to that convention (i.e. 181.0 becomes -179.0), the reader's methods that are called down the track such as  `covers_positions`, `get_variables`, `get_variables_interpolated` etc..wont return the correct values for those location beyond the 180 degT line.   

A workaround is to check if there are any lon>180 and locally change these if needed within the reader-specific methods to make sure the interpolation is done correctly but this is not super elegant.

Any insights, ideas on how to be approach this ? Happy to give it a go as I have some test scripts ready to go.

Likewise, how should be define a reader_global_landmask in those cases ? The below doesnt seem to work.

```
reader_landmask = reader_global_landmask.Reader(
                    llcrnrlon=179.0, llcrnrlat=-42.0,
                    urcrnrlon=181.0, urcrnrlat=-40.0)
```

Nor this one

```
reader_landmask = reader_global_landmask.Reader(
                    llcrnrlon=179.0, llcrnrlat=-42.0,
                    urcrnrlon=-179.0, urcrnrlat=-40.0)
```

**Comment by yosoyjay** [comment]
@simonweppe I've run into the same issues.  Did you find any resolution?

**Comment by simonweppe** [comment]
Hi @yosoyjay , yep I did make some quick and dirty fix on this reader. There is probably a nicer way of doing this but I had to get something quick :) 
>> https://github.com/simonweppe/opendrift/blob/379f6b308aad0252d58a26cad544efd2593f3ecd/opendrift/readers/reader_ROMS_native_MOANA.py#L181

I didnt need a workaround for the landmask in the end since I've used landmask variable of the ROMS dataset itself. But it would be useful too. 

Hope it helps

**Comment by knutfrode** [comment]
@simonweppe This looks interesting. Are you happy with this solution? Perhaps it could work also for `reader_netCDF_CF_generic` and `reader_global_landmask`?

I have not spent much time on the dateline problem, but have got the impression that there is no solution, only more or less ugly workarounds :-)

**Comment by simonweppe** [comment]
@knutfrode Yes I think it could work as well in these readers. 

One thing to note is that the longitude in the native netcdf ROMS files Im using is following the convention [0<lon<360].  Not sure if that is the official/CF way of handling that ? It works well with what we do around NZ where we are not far from that line.

This approach (i.e . 0<lon<360) will likely cause issue around the prime meridian though (longitude=0), but in these cases,I suppose the longitude would be defined between -180/180 in the netcdf file itself ?

**Comment by yosoyjay** [comment]
Thanks @simonweppe ! I ended up taking a similar approach for the `reader_netCDF_CF_generic` and `reader_global_landmask` readers.

I'm working through trying to get plotting working by essentially adding `central_longitude` to a bunch of functions so
that it is added to the `PlateCarree()` calls.  This looks to be a bit more involved.

**Comment by gauteh** [comment]
Is there any code that solves this issue now (that could potentially be made into a PR)? Or does it need a more thorough fix?

**Comment by simonweppe** [comment]
Hi @gauteh,

Yes there is some code in a modified version of the `reader_roms_native,py` I made for a specific dataset we are using : [reader_roms_native_MOANA.py](https://github.com/simonweppe/opendrift/blob/379f6b308aad0252d58a26cad544efd2593f3ecd/opendrift/readers/reader_ROMS_native_MOANA.py)

The ROMS grid covers New Zealand and uses longitudes between [0-360] instead of [-180,180] as used internally in Opendrift. The grid extends over the 180 deg line (max longitude 184.5 deg).

You can search `has_lon_0_360` to see where the code was modified. All the Opendrift  interpolation routines work fine provided that the input coordinates of particles where data is required, was consistent with the convention used in the netcdf file itself. So basically I'm just temporarily converting the longitude used within Opendrift to the [0-360] convention, and then make the query for interpolated data using `get_variables_interpolated()`. Also added a small switch on the `covers_positions()` method. 

I have added a small script seeding particles across the 180degT line to test it [here](https://github.com/simonweppe/opendrift/blob/master/examples_msl/opendrift_using_moana_data_crossing_180deg.py) (you will notice the usual `plot()` doesnt work well since it goes over the 180deg line).

I have kept the code separate while I developed it to avoid messing up the original roms reader. Also, I haven't tested what happens over the 0 deg line, though I suppose the longitude would be defined between -180/180 in the netcdf file itself then, i.e. like used within Opendrfit, so probably no issue. 

Happy to package into a pull request if you see fit (in basereader.py?), or feel free to re-use some code if you'd rather adjust a few things on your side.

cheers

**Comment by gauteh** [comment]
Closing in favor of #89.
