### ISSUE TITLE
Error occurs when using oil type 'EKOFISK BLEND 2002'

### ISSUE THREAD

**Issue by lyingTree** [OpenDrift/opendrift#1026]
When I run openoil to seed element using the oil type 'EKOFISK BLEND 2002', the following error occurs

![image](https://user-images.githubusercontent.com/39767907/202254812-e8fa893c-0a7b-44e2-a265-f2cf0c9bc261.png)

Other oil types do not have this problem, because oil type 'EKOFISK BLEND 2002' is an alias for oil type 'EKOFISK BLEND 2000', as seen in the file ***opendrift/models/openoil/adios/\_\_init\_\_.py*** at line 28
``` python
oil_name_alias = {'EKOFISK BLEND 2002': 'EKOFISK BLEND 2000'}
```

Because in the file ***opendrift/models/openoil/openoil.py***, running line 1420 followed by line 1424 is in conflict with line 315

``` python
# line 1420-1424
oiltype = adios.oil_name_alias.get(oiltype, oiltype)
logger.info(f'setting oil_type to: {oiltype}')

self.oil_name = oiltype
self.set_config('seed:oil_type', oiltype)
# ------------------------------------------------------
# line 315
self.oiltypes.extend(adios.oil_name_alias.keys())
```

After running line 1420, it will get the oil type that is not in `self.oiltypes`, which will lead to an error on line 1424, so is the following change reasonable in the file ***opendrift/models/openoil/openoil.py***?
``` python
# before modification
oiltype = adios.oil_name_alias.get(oiltype, oiltype)
logger.info(f'setting oil_type to: {oiltype}')

self.oil_name = oiltype
self.set_config('seed:oil_type', oiltype)

# ---------------------------------------------------------------------
# after modification
self.set_config('seed:oil_type', oiltype)
oiltype = adios.oil_name_alias.get(oiltype, oiltype)
logger.info(f'setting oil_type to: {oiltype}')

self.oil_name = oiltype

```

**Comment by knutfrode** [comment]
You are right, and your suggestion fixed this issue. Thank you for the contribution.
https://github.com/OpenDrift/opendrift/pull/1029
