### ISSUE TITLE
Attributes for land_binary_mask variable?

### ISSUE THREAD

**Issue by AndresSepulveda** [OpenDrift/opendrift#103]
I am using results from the CMEMS product MERCATOR GLORYS12V1, which doesn't have a land_mask by itself. 

I created one added to the nc file, just as

        double land_binary_mask(latitude, longitude) ;

but I think there are missing attributes as the the following code. 

import matplotlib
matplotlib.use('Agg')
import sys
sys.path.append('/home/mosa/opendrift/')
import os
from datetime import datetime, timedelta
import numpy as np

from opendrift.readers import reader_netCDF_CF_generic
from opendrift.models.oceandrift import OceanDrift

o = OceanDrift(loglevel=0)  # Set loglevel to 0 for debug information

filename_nc = 'vo_1993-2017.nc';

copas_native = reader_netCDF_CF_generic.Reader('/home/mosa/Daniel/' + filename_nc)
copas_native.interpolation='linearND'
o.add_reader([copas_native])

time = copas_native.start_time

lon = -76; lat = -45;  

o.seed_elements(lon, lat, radius=1500, number=100, z=-3, time=time)

o.set_config('general:coastline_action', 'previous') # Vuelve al punto inicial (PelagicEgg)
o.set_config('general:use_basemap_landmask', False)

o.run(time_step=86400,steps=100)

gives me this error:

INFO: OpenDriftSimulation initialised (version 1.0.5)
INFO: Opening dataset: /home/mosa/Daniel/vo_1993-2017.nc
INFO: Opening file with Dataset
DEBUG: Finding coordinate variables.
DEBUG: Parsing variable: depth
DEBUG: Parsing variable: latitude
DEBUG: Parsing variable: longitude
DEBUG: Parsing variable: time
DEBUG: Parsing variable: vo
DEBUG: Parsing variable: uo
DEBUG: Parsing variable: land_binary_mask
DEBUG: Lon and lat are 1D arrays, assuming latong projection
DEBUG: Setting buffer size 49 for reader /home/mosa/Daniel/vo_1993-2017.nc, assuming a maximum average speed of 5 m/s.
DEBUG: Setting buffer size 12 for reader /home/mosa/Daniel/vo_1993-2017.nc, assuming a maximum average speed of 1 m/s.
DEBUG: Calculation SRS set to: +units=m +proj=latlong +ellps=WGS84
DEBUG: Using srs for common grid: +proj=latlong
DEBUG: Added reader /home/mosa/Daniel/vo_1993-2017.nc
DEBUG: ------------------------------------------------------
DEBUG: Software and hardware:
DEBUG:   unknown GB memory
DEBUG:   4 processors (x86_64)
DEBUG:   Basemap version 1.0.7
DEBUG:   NumPy version 1.13.3
DEBUG:   SciPy version 0.19.1
DEBUG:   Matplotlib version 2.1.0
DEBUG:   NetCDF4 version 1.2.4
DEBUG:   Python version 2.7.14 |Anaconda, Inc.| (default, Oct 16 2017, 17:29:19) [GCC 7.2.0]
DEBUG: ------------------------------------------------------
INFO: Config validation OK
DEBUG: No output file is specified, neglecting export_buffer_length
INFO: Fallback values will be used for the following variables which have no readers: 
INFO: 	x_wind: 0.000000
INFO: 	y_wind: 0.000000
INFO: No land reader added, making a temporary basemap reader
DEBUG: Creating Basemap...
DEBUG: No land polygons to rasterize...
DEBUG: Calculation SRS set to: None
INFO: OpenDriftSimulation initialised (version 1.0.5)
DEBUG: Calculation SRS set to: +lon_0=-76.0026855469 +lat_ts=0.0 +R=6370997.0 +proj=merc +x_0=-0.0 +units=m +y_0=5635695.66227 +ellps=WGS84 
DEBUG: Using srs for common grid: +lon_0=-76.0026855469 +lat_ts=0.0 +R=6370997.0 +proj=merc +x_0=-0.0 +units=m +y_0=5635695.66227 
DEBUG: Added reader tempreader
DEBUG: ----------------------------------------
DEBUG: Variable group ['land_binary_mask']
DEBUG: ----------------------------------------
DEBUG: Calling reader tempreader
DEBUG: ----------------------------------------
DEBUG: Data needed for 100 elements
DEBUG: Reader time:
		None (before)
		None (after)
DEBUG: Fetching variables from tempreader
DEBUG: Fetched env-before
DEBUG: No time interpolation needed - right on time.
DEBUG: Obtained data for all elements.
DEBUG: ---------------------------------------
DEBUG: Finished processing all variable groups
DEBUG: ------------ SUMMARY -------------
DEBUG:     land_binary_mask: 0 (min) 0 (max)
DEBUG: ---------------------------------
DEBUG: 		0 active elements
INFO: All points are in ocean
DEBUG: to be seeded: 100, already seeded 0
DEBUG: Released 100 new elements.
DEBUG: ======================================================================
INFO: 1993-01-01 12:00:00 - step 1 of 100 - 100 active elements (0 deactivated)
DEBUG: 0 elements scheduled.
DEBUG: ======================================================================
DEBUG: ----------------------------------------
DEBUG: Variable group ['y_sea_water_velocity', 'x_sea_water_velocity']
DEBUG: ----------------------------------------
DEBUG: Calling reader /home/mosa/Daniel/vo_1993-2017.nc
DEBUG: ----------------------------------------
DEBUG: Data needed for 100 elements
DEBUG: Reader time:
		1993-01-01 12:00:00 (before)
		1993-01-02 12:00:00 (after)
DEBUG: Fetching variables from /home/mosa/Daniel/vo_1993-2017.nc
DEBUG: Filled NaN-values toward seafloor for :['y_sea_water_velocity', 'x_sea_water_velocity']
DEBUG: Fetched env-block (size 25x25x4) for time before (1993-01-01 12:00:00)
DEBUG: Interpolating before (1993-01-01 12:00:00) in space  (linearND)
DEBUG: Initialising interpolator.
DEBUG: No time interpolation needed - right on time.
DEBUG: Reader SRS is the same as calculation SRS - rotation of vectors is not needed.
DEBUG: Obtained data for all elements.
DEBUG: ---------------------------------------
DEBUG: Finished processing all variable groups
DEBUG: ------------ SUMMARY -------------
DEBUG:     x_sea_water_velocity: 0.0562179 (min) 0.0638721 (max)
DEBUG:     y_sea_water_velocity: 0.0129747 (min) 0.0402517 (max)
DEBUG:     x_wind: 0 (min) 0 (max)
DEBUG:     y_wind: 0 (min) 0 (max)
DEBUG:     land_binary_mask: nan (min) nan (max)
DEBUG: ---------------------------------
DEBUG: 		100 active elements
DEBUG: 		-45.03 <- latitude  -> -44.9678
DEBUG: 		-76.0486 <- longitude -> -75.9568
DEBUG: 		z = -3.0
DEBUG: ---------------------------------
WARNING: Missing variables: ['land_binary_mask']
DEBUG: No elements hit coastline.
DEBUG: Added status missing_data
DEBUG: 100 elements scheduled for deactivation (missing_data)
DEBUG: 	(z: -3.000000 to -3.000000)
DEBUG: Removed 100 elements.
DEBUG: Removed 100 values from environment.
WARNING: The simulation stopped before requested end time was reached.
INFO: ========================
INFO: End of simulation:
INFO: No more active elements, quitting.
INFO: Traceback (most recent call last):
  File "/home/mosa/opendrift/opendrift/models/basemodel.py", line 2186, in run
    raise ValueError('No more active elements, quitting.')
ValueError: No more active elements, quitting.

INFO: "Missing variables: ['land_binary_mask']", 'The simulation stopped before requested end time was reached.'

INFO: ========================
Traceback (most recent call last):
  File "./copas_opendrift.py", line 71, in <module>
    o.run(time_step=86400,steps=100)
  File "/home/mosa/opendrift/opendrift/models/basemodel.py", line 2228, in run
    'first timestep. ' + self.get_messages())
ValueError: Simulation stopped within first timestep. "Missing variables: ['land_binary_mask']", 'The simulation stopped before requested end time was reached.'

**Comment by vic1309** [comment]
Hey Andres,

There is the possibility of create land_mask using Basemap. For instance:

    # Landmask (Basemap)
    reader_basemap = reader_basemap_landmask.Reader(
                        llcrnrlon=5, llcrnrlat=75,
                        urcrnrlon=35, urcrnrlat=84, resolution='h')

    o.add_reader(reader_basemap,
                  variables=['land_binary_mask'])

Where: 
     

     llcrnrlon - longitude of lower left hand corner of the desired map domain (degrees).
     llcrnrlat - latitude of lower left hand corner of the desired map domain (degrees).    
     urcrnrlon - longitude of upper right hand corner of the desired map domain (degrees).
     urcrnrlat - latitude of upper right hand corner of the desired map domain (degrees).

**Comment by AndresSepulveda** [comment]
Hi , thanks. Yes, I've used that, but I would like the particles to respect the boundaries that were in the model, this is an area with a lot of channels and particles are getting in place where the original model has land values, if I use basemap.

**Comment by knutfrode** [comment]
OpenDrift detects variables solely based on the ```standard_name``` attribute, according to the CF-convention. 
Thus it should work if you add an attribute ```standard_name``` identical to ```land_binary_mask``` to this variable.

**Comment by AndresSepulveda** [comment]
ok, that works, thanks again. Could I use this same variable (land_binary_mask) for the output plot?

**Comment by knutfrode** [comment]
There is currently no way to do that, so you would need to hack the plotting function.
A general input parameter to this one (show_landmask=True/False) could be generally useful.
Note that you may also provide a colormap (cmap, custom made or string/name), and set vmin and vmax for background limits.
