### ISSUE TITLE
URL Links for wind & ocean currents databases

### ISSUE THREAD

**Issue by ssosas** [OpenDrift/opendrift#1043]
Hi all,

It should be quite obvious but I'm a beginner with OpenDrift, apologies! ... May someone tell me some URLs where I could download subsets for the zone and time I'm analyzing?  Something similar to that: https://psl.noaa.gov/mddb2/makePlot.html?variableID=155703... but for U/V together in a nc file and for ocean currents

Thanks a lot! Best regards,

Sergio

**Comment by knutfrode** [comment]
Hi, and sorry for the late response.

The simplest is to use a thredds URL of remote datasets, then the necessary data will be automatically downloaded during the simulation.
The forcing data themselves are independent from OpenDrift, but here is a list of some available datasets with various coverage:
https://github.com/OpenDrift/opendrift/blob/master/opendrift/scripts/data_sources.txt

There are two global sources of ocean currents, namely
HYCOM: https://tds.hycom.org/thredds/dodsC/GLBy0.08/latest
and
Mercator: https://nrt.cmems-du.eu/thredds/dodsC/cmems_mod_glo_phy_anfc_merged-uv_PT1H-i
Mercator requires that you create a CMEMS user and make a `.netrc`files as explanined here:
https://opendrift.github.io/gallery/example_long_cmems.html#sphx-glr-gallery-example-long-cmems-py

**Comment by ssosas** [comment]
Hi and many thanks for your answer ;). Ok I'm currently using thredds CMEMS for ocean currents and it works for dates in the past. Regarding surface winds I point to thredds "https://pae-paha.pacioos.hawaii.edu/thredds/dodsC/ncep_global/NCEP_Global_Atmospheric_Model_best.ncd" but it works only for forecast winds, not for reanalysis. Could you tell an URL for that?
Cheers!
Sergio

**Comment by ssosas** [comment]
Hi Knut-Frode, so I found a way to obtain automatically Copernicus ERA5 data for surface winds. This is possible using the Python library cdsapi and extracting the data you need for your simulation. The problem is that the opendrift netcdf reader doesn't recognize variables from ERA5 even if I change the name of u and v wind. See the example here below:

- your test data *.nc file opened with xarray:
<xarray.Dataset>
Dimensions:             (y: 151, x: 81, time: 67)
Coordinates:
    latitude            (y, x) float64 ...
    longitude           (y, x) float64 ...
  * time                (time) datetime64[ns] 2015-11-16 ... 2015-11-18T18:00:00
  * x                   (x) float32 -6.474e+05 -6.449e+05 ... -4.474e+05
  * y                   (y) float32 -4.043e+05 -4.018e+05 ... -2.932e+04
Data variables:
    projection_lambert  int32 ...
    x_wind_10m          (time, y, x) float32 ...
    y_wind_10m          (time, y, x) float32 ...
Attributes:
    Expires:      2015-12-02
    history:      Mon Nov 16 15:06:45 2015: ncks -O -4 -v x_wind_10m,y_wind_1...
    min_time:     2015-11-16 00:00 UTC
    max_time:     2015-11-18 18:00 UTC
    title:        unknown
    references:   unknown
    comment:      none
    Conventions:  CF-1.0
    institution:  Norwegian Meteorological Institute, met.no
    source:       AROME-MetCoOp (SURFEX output)
    NCO:          4.0.8

- ERA5 file downloaded from Copernicus opened with xarray:
<xarray.Dataset>
Dimensions:    (longitude: 25, latitude: 17, expver: 2, time: 10228)
Coordinates:
  * longitude  (longitude) float32 -6.0 -5.75 -5.5 -5.25 ... -0.5 -0.25 0.0
  * latitude   (latitude) float32 47.0 46.75 46.5 46.25 ... 43.5 43.25 43.0
  * expver     (expver) int32 1 5
  * time       (time) datetime64[ns] 2015-01-01 ... 2022-12-31T18:00:00
Data variables:
    u10        (time, expver, latitude, longitude) float32 ...
    v10        (time, expver, latitude, longitude) float32 ...
Attributes:
    Conventions:  CF-1.6
    history:      2023-01-12 17:24:20 GMT by grib_to_netcdf-2.25.1: /opt/ecmw...

Do you have any idea to make ERA5 files readable by opendrift?

Many thanks

Sergio

**Comment by knutfrode** [comment]
Hi,

OpenDrift does not look at variable names, as these could anything, depending on the preference of the creator.
Instead, it looks for the attribute `standard_name`, which identifies the correct variable according the the CF convention
https://cfconventions.org/Data/cf-standard-names/current/build/cf-standard-name-table.html
https://cfconventions.org/Data/cf-conventions/cf-conventions-1.10/cf-conventions.html

If the variables of a dataset does not contain `standard_name` attributes, you can provide a mapping to the reader, as in this example:
https://cfconventions.org/Data/cf-conventions/cf-conventions-1.10/cf-conventions.html

I.e. the mapping is `standard_name_mapping={<variable_name>: <corresponding CF standard_name>} `

**Comment by ssosas** [comment]
Thanks again, ok I see the difference :)  I have checked that in ERA5 data and this key (standard_name) is missing in the attribute dictionary object.

See here the print of xr['u10'].attrs -->  {'units': 'm s**-1', 'long_name': '10 metre U wind component'}

The mapping doesn't work, we need to add this attribute.

I have included that in my code:
import xarray as xr
test_xr = xr.open_dataset('/path_to/your_original_ERA5_file.nc')
test_xr['u10'].attrs = {'units': 'm s**-1', 'long_name': '10 metre U wind component', 'standard_name': 'x_wind'}
test_xr['v10'].attrs = {'units': 'm s**-1', 'long_name': '10 metre V wind component', 'standard_name': 'v_wind'}
test_xr.to_netcdf(''/path_to/your_new_ERA5_file.nc'')

Now we can read the new_ERA5_file with the opendrift reader_netCDF_CF_generic. I have tested and it works fine, wind is taken into account in the simulation.

;) Cheers!
