### ISSUE TITLE
opendrift simulation with high resolution coastlines by using local nc file

### ISSUE THREAD

**Issue by Morhaf-ALjber** [OpenDrift/opendrift#1053]
Dear all, I'm using open drift to run a simulation for a particle tracking in a bay using the water currents resulted from Schism model. I have the binary map of the bay and I want to used it in the simulation because the resolution is higher than those provided by the code. I imported the nc file map which contains longitude, latitude, and land_binary_mask using, reader_landmask = reader_netCDF_CF_generic.Reader('land_mask.nc'), to my code and I changed the debugging source in the line number 83 in "reader_global_landmask.py" to the directory that contains the file that I want to use. Still I'm receiving the resulted plotted map from GSHHG.
How I can obtain my resulted using the high resolution map I have.

**Comment by knutfrode** [comment]
Hi, please see this example:
https://opendrift.github.io/gallery/example_model_landmask.html

**Comment by knutfrode** [comment]
Please reopen if this did not work for you

**Comment by Morhaf-ALjber** [comment]
Thank you for your help.
==============================
Morhaf Aljber (Mr.), Master Candidate, CHESS lab
<http://home.hiroshima-u.ac.jp/leehs/>
Transdisciplinary Science and Engineering (TSE) Programme, Graduate School
of Advanced Science and Engineering, Hiroshima Univ
<http://www.hiroshima-u.ac.jp/index-j.html>.
E-mail: ***@***.***
