### ISSUE TITLE
issue with opendrift_gui.py 

### ISSUE THREAD

**Issue by snowfalcon123** [OpenDrift/opendrift#1059]
the gui part requires model Openoil to run, and it seems like the openoil part needs something called "unit_conversion". the "correct" one i found on pypj  https://pypi.org/project/unit-conversion/ is unit-conversion 1.0.2 which released on 2016, and only convert time. also, the unit_conversion i am using does not have the function called convert, but clearly, on the measurement.py line 19,it called the function convert from unit_conversion. 
my guess, i am using the wrong unit_conversion model, but i am not sure which one i am supposed to use

**Comment by gauteh** [comment]
I think this is provided by pynucos. The dependencies listed in pyproject.toml or environment.yml should be sufficient.

**Comment by knutfrode** [comment]
I am not able to reproduce this problem with a new installation.
Did you follow the steps here?
https://opendrift.github.io/install.html

Could you have an old version making trouble? If so, you can try to remove the conda environment and create anew. Note that "conda update" is not always working as expected.

**Comment by snowfalcon123** [comment]
> I am not able to reproduce this problem with a new installation. Did you follow the steps here? https://opendrift.github.io/install.html
> 
> Could you have an old version making trouble? If so, you can try to remove the conda environment and create anew. Note that "conda update" is not always working as expected.

thanks for the reply .
I do follow the installation guide. 
i will try it tomorrow and let u know if it is working or not .

**Comment by snowfalcon123** [comment]
> I am not able to reproduce this problem with a new installation. Did you follow the steps here? https://opendrift.github.io/install.html
> 
> Could you have an old version making trouble? If so, you can try to remove the conda environment and create anew. Note that "conda update" is not always working as expected.



> I am not able to reproduce this problem with a new installation. Did you follow the steps here? https://opendrift.github.io/install.html
> 
> Could you have an old version making trouble? If so, you can try to remove the conda environment and create anew. Note that "conda update" is not always working as expected.

hi
i try to use the newest version and reinstall the whole package. the gui part still does not work. the error is same " no module named “unit_conversion'

**Comment by knutfrode** [comment]
Hi,
Which of the alternatives did you use for installation? Did you follow the step exactly as written, or any modifications?
https://opendrift.github.io/install.html

Did you remove the environment (conda env remove -n opendrift) before trying again?
Note that it is not enough to update OpenDrift code, the conda environment must also be updated, and rather installed from scratch if there are problems.

And what is your operating system?

**Comment by snowfalcon123** [comment]
> Hi, Which of the alternatives did you use for installation? Did you follow the step exactly as written, or any modifications? https://opendrift.github.io/install.html
> 
> Did you remove the environment (conda env remove -n opendrift) before trying again? Note that it is not enough to update OpenDrift code, the conda environment must also be updated, and rather installed from scratch if there are problems.
> 
> And what is your operating system?
i am using alternative 1 here . 
the thing is, if i just double click the "opendrift-gui.exe",under folder miniconda3\envs\opendrift\Scripts , it works perfectly fine. on the anther hand, if i am using pycharm to run "opendrift_gui.py",the error raises.

**Comment by knutfrode** [comment]
Ok, then it seems that there is an issue with your Pycharm Python environment.

**Comment by snowfalcon123** [comment]
> Ok, then it seems that there is an issue with your Pycharm Python environment.

maybe. i will try to reconnect the conda with my Pycharm to see if it is fixed . 
thanks a lot .
