### ISSUE TITLE
Problem using two ROMS files

### ISSUE THREAD

**Issue by AndresSepulveda** [OpenDrift/opendrift#106]
Hi,

I am using the velocity fields from a ROMS files and the GRID information from a separate file to study LCS.

The script is
import sys

sys.path.append('/home/mosa/opendrift/')

import os
from datetime import datetime, timedelta
import numpy as np

from opendrift.readers import reader_ROMS_native
from opendrift.models.oceandrift import OceanDrift

o = OceanDrift(loglevel=0)  # Set loglevel to 0 for debug information

#filename_nc = 'roms_his_20181002_l.nc';
filename_nc = 'oldroms.nc';
o.set_config('general:basemap_resolution','i')
gridfile='/var/www/html/MOSAv2/roms_grd3.nc'

ifop_native = reader_ROMS_native.Reader('/media/mosa/MOSA2018/' + filename_nc,gridfile=gridfile)
ifop_native.interpolation='linearND'

o.add_reader([ifop_native])

start_time = ifop_native.start_time
end_time = ifop_native.end_time

lcs = o.calculate_ftle(
    time=ifop_native.start_time + timedelta(hours=20),
    time_step=timedelta(minutes=30),
    duration=timedelta(hours=5), delta=1000,
    RLCS=False)

#Simulation from beginning and up to 30 hours (time of LCS)
o.reset()
o.seed_elements(lon=-73.3536, lat=-43.5851, number=1000, radius=1000,
                time=ifop_native.start_time)
o.run(end_time=ifop_native.start_time+timedelta(hours=20),
      time_step=timedelta(minutes=30))

o.plot(lcs=lcs, vmin=1e-7, vmax=1e-4, colorbar=True, show_particles=True)

However, I get the following error:

INFO: OpenDriftSimulation initialised (version 1.0.5)
INFO: Opening dataset: /media/mosa/MOSA2018/oldroms.nc
INFO: Opening file with Dataset
INFO: 'gls_cmu0'
INFO: Did not find complete set of GLS parameters
INFO: Ocean time given as seconds relative to start Setting artifical start time of 1 Jan 2000.
INFO: Making Splines for lon,lat to x,y conversion...
Traceback (most recent call last):
  File "./ifop_mosa.py", line 25, in <module>
    ifop_native = reader_ROMS_native.Reader('/media/mosa/MOSA2018/' + filename_nc,gridfile=gridfile)
  File "/home/mosa/opendrift/opendrift/readers/reader_ROMS_native.py", line 179, in __init__
    super(Reader, self).__init__()
  File "/home/mosa/opendrift/opendrift/readers/basereader.py", line 159, in __init__
    fill_value=np.nan)
  File "interpnd.pyx", line 243, in scipy.interpolate.interpnd.LinearNDInterpolator.__init__
  File "interpnd.pyx", line 78, in scipy.interpolate.interpnd.NDInterpolatorBase.__init__
  File "interpnd.pyx", line 189, in scipy.interpolate.interpnd._check_init_shape
ValueError: different number of values and points

Any clue on the meaning?

**Comment by AndresSepulveda** [comment]
Here is what I get.

INFO: OpenDriftSimulation initialised (version 1.0.5)
INFO: Opening dataset: /media/mosa/MOSA2018/oldroms.nc
INFO: Opening file with Dataset
INFO: 'gls_cmu0'
INFO: Did not find complete set of GLS parameters
INFO: Ocean time given as seconds relative to start Setting artifical start time of 1 Jan 2000.
INFO: Making Splines for lon,lat to x,y conversion...
(603, 251) (603, 251) 0.0 504.0 (603, 505)
Traceback (most recent call last):
  File "./ifop_mosa.py", line 27, in <module>
    ifop_native = reader_ROMS_native.Reader('/media/mosa/MOSA2018/' + filename_nc,gridfile=gridfile)
  File "/home/mosa/opendrift/opendrift/readers/reader_ROMS_native.py", line 179, in __init__
    super(Reader, self).__init__()
  File "/home/mosa/opendrift/opendrift/readers/basereader.py", line 160, in __init__
    fill_value=np.nan)
  File "interpnd.pyx", line 243, in scipy.interpolate.interpnd.LinearNDInterpolator.__init__
  File "interpnd.pyx", line 78, in scipy.interpolate.interpnd.NDInterpolatorBase.__init__
  File "interpnd.pyx", line 189, in scipy.interpolate.interpnd._check_init_shape
ValueError: different number of values and points

As mentioned in another post, the example_LCS_norkyst.py case works fine in version 1.0.5

**Comment by knutfrode** [comment]
This shows that the size of the lon/lat-arrays (603x251) does not match the size of the x (xi_rho) dimension. Are you sure that the gridfile corresponds to the given ROMS file?
It would help to see an ```ncdump``` of these two files.

**Comment by AndresSepulveda** [comment]
My bad, sorry. I was calling the grid fied of a different run. Fixed that, now I get the following problem, probably related to time steps definitions. In this file we have  a 1h time step and 24 records.

mosa@parti-mosa:~/Daniel$ ./ifop_mosa.py 
INFO: OpenDriftSimulation initialised (version 1.0.5)
INFO: Opening dataset: /media/mosa/MOSA2018/oldroms.nc
INFO: Opening file with Dataset
INFO: 'gls_cmu0'
INFO: Did not find complete set of GLS parameters
INFO: Ocean time given as seconds relative to start Setting artifical start time of 1 Jan 2000.
INFO: Making Splines for lon,lat to x,y conversion...
(603, 505) (603, 505) 0.0 504.0 (603, 505)
DEBUG: Setting buffer size 20 for reader roms native, assuming a maximum average speed of 5 m/s.
DEBUG: Setting buffer size 6 for reader roms native, assuming a maximum average speed of 1 m/s.
DEBUG: roms native is unprojected, cannot use for common grid
DEBUG: Added reader roms native
INFO: Setting SRS to latlong, since not defined before.
DEBUG: Calculation SRS set to: +units=m +proj=latlong +ellps=WGS84
INFO: No reader provided, using first available:
INFO: roms native
INFO: Calculating LCS for 2018-10-02 20:00:00
INFO: Nothing to reset
DEBUG: ------------------------------------------------------
DEBUG: Software and hardware:
DEBUG:   unknown GB memory
DEBUG:   4 processors (x86_64)
DEBUG:   Basemap version 1.0.7
DEBUG:   NumPy version 1.13.3
DEBUG:   SciPy version 0.19.1
DEBUG:   Matplotlib version 2.1.0
DEBUG:   NetCDF4 version 1.2.4
DEBUG:   Python version 2.7.14 |Anaconda, Inc.| (default, Oct 16 2017, 17:29:19) [GCC 7.2.0]
DEBUG: ------------------------------------------------------
INFO: Config validation OK
DEBUG: No output file is specified, neglecting export_buffer_length
INFO: Fallback values will be used for the following variables which have no readers: 
INFO: 	x_wind: 0.000000
INFO: 	y_wind: 0.000000
INFO: Backwards simulation, starting from last seeded element
INFO: Adding a dynamical landmask (resolution "i") based on assumed maximum speed of 1 m/s. Adding a customised landmask may be faster...
DEBUG: Creating Basemap...
DEBUG: No land polygons to rasterize...
DEBUG: Added reader basemap_landmask
INFO: Using existing reader for land_binary_mask
DEBUG: ----------------------------------------
DEBUG: Variable group ['land_binary_mask']
DEBUG: ----------------------------------------
DEBUG: Calling reader basemap_landmask
DEBUG: ----------------------------------------
DEBUG: Data needed for 1 elements
DEBUG: Reader time:
		None (before)
		None (after)
DEBUG: Fetching variables from basemap_landmask
DEBUG: Fetched env-before
DEBUG: No time interpolation needed - right on time.
DEBUG: Obtained data for all elements.
DEBUG: ---------------------------------------
DEBUG: Finished processing all variable groups
DEBUG: ------------ SUMMARY -------------
DEBUG:     land_binary_mask: 0 (min) 0 (max)
DEBUG: ---------------------------------
DEBUG: 		0 active elements
INFO: All points are in ocean
INFO: Backwards simulation, starting at time of last seeded element
DEBUG: to be seeded: 1, already seeded 0
DEBUG: Released 1 new elements.
DEBUG: ======================================================================
INFO: 2018-10-02 20:00:00 - step 1 of 5 - 1 active elements (0 deactivated)
DEBUG: 0 elements scheduled.
DEBUG: ======================================================================
DEBUG: ----------------------------------------
DEBUG: Variable group ['x_sea_water_velocity', 'y_sea_water_velocity']
DEBUG: ----------------------------------------
DEBUG: Calling reader roms native
DEBUG: ----------------------------------------
DEBUG: Data needed for 1 elements
DEBUG: Reader time:
		2018-10-02 20:00:00 (before)
		2018-10-02 20:59:44 (after)
DEBUG: Fetching variables from roms native
DEBUG: Manually masking x_sea_water_velocity, FillValue None, scale 1, offset 0
DEBUG: Manually masking y_sea_water_velocity, FillValue None, scale 1, offset 0
DEBUG: Reading angle between xi and east...
INFO: ========================
INFO: Exception:
INFO: 'angle'
DEBUG: Traceback (most recent call last):
  File "/home/mosa/opendrift/opendrift/models/basemodel.py", line 913, in get_environment
    z[missing_indices], self.use_block, self.proj)
  File "/home/mosa/opendrift/opendrift/readers/basereader.py", line 400, in get_variables_interpolated
    block=block)
  File "/home/mosa/opendrift/opendrift/readers/basereader.py", line 292, in _get_variables
    env = self.get_variables(variables, time, x, y, z, block)
  File "/home/mosa/opendrift/opendrift/readers/reader_ROMS_native.py", line 400, in get_variables
    self.angle_xi_east = self.Dataset.variables['angle'][:]
KeyError: 'angle'

INFO: ========================
DEBUG: ----------------------------------------
DEBUG: Variable group ['land_binary_mask']
DEBUG: ----------------------------------------
DEBUG: Calling reader basemap_landmask
DEBUG: ----------------------------------------
DEBUG: Data needed for 1 elements
DEBUG: Reader time:
		None (before)
		None (after)
DEBUG: Fetching variables from basemap_landmask
DEBUG: Fetched env-before
DEBUG: No time interpolation needed - right on time.
DEBUG: Obtained data for all elements.
DEBUG: ---------------------------------------
DEBUG: Finished processing all variable groups
DEBUG: ------------ SUMMARY -------------
DEBUG:     x_sea_water_velocity: 0 (min) 0 (max)
DEBUG:     y_sea_water_velocity: 0 (min) 0 (max)
DEBUG:     x_wind: 0 (min) 0 (max)
DEBUG:     y_wind: 0 (min) 0 (max)
DEBUG:     land_binary_mask: 0 (min) 0 (max)
DEBUG: ---------------------------------
DEBUG: 		1 active elements
DEBUG: 		latitude =  -47.0
DEBUG: 		longitude = -79.0
DEBUG: 		z = 0.0
DEBUG: ---------------------------------
DEBUG: No elements to deactivate
DEBUG: Calling OceanDrift.update()
DEBUG: Applying wind drift factor of 0.019999999553 to 1 elements at surface
DEBUG: 1 active elements (0 deactivated)
DEBUG: to be seeded: 0, already seeded 1
DEBUG: ======================================================================
INFO: 2018-10-02 19:00:00 - step 2 of 5 - 1 active elements (0 deactivated)
DEBUG: 0 elements scheduled.
DEBUG: ======================================================================
DEBUG: ----------------------------------------
DEBUG: Variable group ['x_sea_water_velocity', 'y_sea_water_velocity']
DEBUG: ----------------------------------------
DEBUG: Calling reader roms native
DEBUG: ----------------------------------------
DEBUG: Data needed for 1 elements
DEBUG: Reader time:
		2018-10-02 17:59:28 (before)
		2018-10-02 19:00:16 (after)
DEBUG: Fetching variables from roms native
DEBUG: Manually masking x_sea_water_velocity, FillValue None, scale 1, offset 0
DEBUG: Manually masking y_sea_water_velocity, FillValue None, scale 1, offset 0
DEBUG: Reading angle between xi and east...
INFO: ========================
INFO: Exception:
INFO: 'angle'
DEBUG: Traceback (most recent call last):
  File "/home/mosa/opendrift/opendrift/models/basemodel.py", line 913, in get_environment
    z[missing_indices], self.use_block, self.proj)
  File "/home/mosa/opendrift/opendrift/readers/basereader.py", line 400, in get_variables_interpolated
    block=block)
  File "/home/mosa/opendrift/opendrift/readers/basereader.py", line 292, in _get_variables
    env = self.get_variables(variables, time, x, y, z, block)
  File "/home/mosa/opendrift/opendrift/readers/reader_ROMS_native.py", line 400, in get_variables
    self.angle_xi_east = self.Dataset.variables['angle'][:]
KeyError: 'angle'

INFO: ========================
DEBUG: ----------------------------------------
DEBUG: Variable group ['land_binary_mask']
DEBUG: ----------------------------------------
DEBUG: Calling reader basemap_landmask
DEBUG: ----------------------------------------
DEBUG: Data needed for 1 elements
DEBUG: Reader time:
		None (before)
		None (after)
DEBUG: Fetching variables from basemap_landmask
DEBUG: Fetched env-before
DEBUG: No time interpolation needed - right on time.
DEBUG: Obtained data for all elements.
DEBUG: ---------------------------------------
DEBUG: Finished processing all variable groups
DEBUG: ------------ SUMMARY -------------
DEBUG:     x_sea_water_velocity: 0 (min) 0 (max)
DEBUG:     y_sea_water_velocity: 0 (min) 0 (max)
DEBUG:     x_wind: 0 (min) 0 (max)
DEBUG:     y_wind: 0 (min) 0 (max)
DEBUG:     land_binary_mask: 0 (min) 0 (max)
DEBUG: ---------------------------------
DEBUG: 		1 active elements
DEBUG: 		latitude =  -47.0
DEBUG: 		longitude = -79.0
DEBUG: 		z = 0.0
DEBUG: ---------------------------------
DEBUG: No elements to deactivate
DEBUG: Calling OceanDrift.update()
DEBUG: Applying wind drift factor of 0.019999999553 to 1 elements at surface
DEBUG: 1 active elements (0 deactivated)
DEBUG: to be seeded: 0, already seeded 1
DEBUG: ======================================================================
INFO: 2018-10-02 18:00:00 - step 3 of 5 - 1 active elements (0 deactivated)
DEBUG: 0 elements scheduled.
DEBUG: ======================================================================
DEBUG: ----------------------------------------
DEBUG: Variable group ['x_sea_water_velocity', 'y_sea_water_velocity']
DEBUG: ----------------------------------------
DEBUG: Calling reader roms native
DEBUG: ----------------------------------------
DEBUG: Data needed for 1 elements
DEBUG: Reader time:
		2018-10-02 17:59:28 (before)
		2018-10-02 19:00:16 (after)
DEBUG: Fetching variables from roms native
DEBUG: Manually masking x_sea_water_velocity, FillValue None, scale 1, offset 0
DEBUG: Manually masking y_sea_water_velocity, FillValue None, scale 1, offset 0
DEBUG: Reading angle between xi and east...
INFO: ========================
INFO: Exception:
INFO: 'angle'
DEBUG: Traceback (most recent call last):
  File "/home/mosa/opendrift/opendrift/models/basemodel.py", line 913, in get_environment
    z[missing_indices], self.use_block, self.proj)
  File "/home/mosa/opendrift/opendrift/readers/basereader.py", line 400, in get_variables_interpolated
    block=block)
  File "/home/mosa/opendrift/opendrift/readers/basereader.py", line 292, in _get_variables
    env = self.get_variables(variables, time, x, y, z, block)
  File "/home/mosa/opendrift/opendrift/readers/reader_ROMS_native.py", line 400, in get_variables
    self.angle_xi_east = self.Dataset.variables['angle'][:]
KeyError: 'angle'

INFO: ========================
DEBUG: ----------------------------------------
DEBUG: Variable group ['land_binary_mask']
DEBUG: ----------------------------------------
DEBUG: Calling reader basemap_landmask
DEBUG: ----------------------------------------
DEBUG: Data needed for 1 elements
DEBUG: Reader time:
		None (before)
		None (after)
DEBUG: Fetching variables from basemap_landmask
DEBUG: Fetched env-before
DEBUG: No time interpolation needed - right on time.
DEBUG: Obtained data for all elements.
DEBUG: ---------------------------------------
DEBUG: Finished processing all variable groups
DEBUG: ------------ SUMMARY -------------
DEBUG:     x_sea_water_velocity: 0 (min) 0 (max)
DEBUG:     y_sea_water_velocity: 0 (min) 0 (max)
DEBUG:     x_wind: 0 (min) 0 (max)
DEBUG:     y_wind: 0 (min) 0 (max)
DEBUG:     land_binary_mask: 0 (min) 0 (max)
DEBUG: ---------------------------------
DEBUG: 		1 active elements
DEBUG: 		latitude =  -47.0
DEBUG: 		longitude = -79.0
DEBUG: 		z = 0.0
DEBUG: ---------------------------------
DEBUG: No elements to deactivate
DEBUG: Calling OceanDrift.update()
DEBUG: Applying wind drift factor of 0.019999999553 to 1 elements at surface
DEBUG: 1 active elements (0 deactivated)
DEBUG: to be seeded: 0, already seeded 1
DEBUG: ======================================================================
INFO: 2018-10-02 17:00:00 - step 4 of 5 - 1 active elements (0 deactivated)
DEBUG: 0 elements scheduled.
DEBUG: ======================================================================
DEBUG: ----------------------------------------
DEBUG: Variable group ['x_sea_water_velocity', 'y_sea_water_velocity']
DEBUG: ----------------------------------------
DEBUG: Calling reader roms native
DEBUG: ----------------------------------------
DEBUG: Data needed for 1 elements
DEBUG: Reader time:
		2018-10-02 16:59:44 (before)
		2018-10-02 17:59:28 (after)
DEBUG: Fetching variables from roms native
DEBUG: Manually masking x_sea_water_velocity, FillValue None, scale 1, offset 0
DEBUG: Manually masking y_sea_water_velocity, FillValue None, scale 1, offset 0
DEBUG: Reading angle between xi and east...
INFO: ========================
INFO: Exception:
INFO: 'angle'
DEBUG: Traceback (most recent call last):
  File "/home/mosa/opendrift/opendrift/models/basemodel.py", line 913, in get_environment
    z[missing_indices], self.use_block, self.proj)
  File "/home/mosa/opendrift/opendrift/readers/basereader.py", line 400, in get_variables_interpolated
    block=block)
  File "/home/mosa/opendrift/opendrift/readers/basereader.py", line 292, in _get_variables
    env = self.get_variables(variables, time, x, y, z, block)
  File "/home/mosa/opendrift/opendrift/readers/reader_ROMS_native.py", line 400, in get_variables
    self.angle_xi_east = self.Dataset.variables['angle'][:]
KeyError: 'angle'

INFO: ========================
DEBUG: ----------------------------------------
DEBUG: Variable group ['land_binary_mask']
DEBUG: ----------------------------------------
DEBUG: Calling reader basemap_landmask
DEBUG: ----------------------------------------
DEBUG: Data needed for 1 elements
DEBUG: Reader time:
		None (before)
		None (after)
DEBUG: Fetching variables from basemap_landmask
DEBUG: Fetched env-before
DEBUG: No time interpolation needed - right on time.
DEBUG: Obtained data for all elements.
DEBUG: ---------------------------------------
DEBUG: Finished processing all variable groups
DEBUG: ------------ SUMMARY -------------
DEBUG:     x_sea_water_velocity: 0 (min) 0 (max)
DEBUG:     y_sea_water_velocity: 0 (min) 0 (max)
DEBUG:     x_wind: 0 (min) 0 (max)
DEBUG:     y_wind: 0 (min) 0 (max)
DEBUG:     land_binary_mask: 0 (min) 0 (max)
DEBUG: ---------------------------------
DEBUG: 		1 active elements
DEBUG: 		latitude =  -47.0
DEBUG: 		longitude = -79.0
DEBUG: 		z = 0.0
DEBUG: ---------------------------------
DEBUG: No elements to deactivate
DEBUG: Calling OceanDrift.update()
DEBUG: Applying wind drift factor of 0.019999999553 to 1 elements at surface
DEBUG: 1 active elements (0 deactivated)
DEBUG: to be seeded: 0, already seeded 1
DEBUG: ======================================================================
INFO: 2018-10-02 16:00:00 - step 5 of 5 - 1 active elements (0 deactivated)
DEBUG: 0 elements scheduled.
DEBUG: ======================================================================
DEBUG: ----------------------------------------
DEBUG: Variable group ['x_sea_water_velocity', 'y_sea_water_velocity']
DEBUG: ----------------------------------------
DEBUG: Calling reader roms native
DEBUG: ----------------------------------------
DEBUG: Data needed for 1 elements
DEBUG: Reader time:
		2018-10-02 16:00:00 (before)
		2018-10-02 16:59:44 (after)
DEBUG: Fetching variables from roms native
DEBUG: Manually masking x_sea_water_velocity, FillValue None, scale 1, offset 0
DEBUG: Manually masking y_sea_water_velocity, FillValue None, scale 1, offset 0
DEBUG: Reading angle between xi and east...
INFO: ========================
INFO: Exception:
INFO: 'angle'
DEBUG: Traceback (most recent call last):
  File "/home/mosa/opendrift/opendrift/models/basemodel.py", line 913, in get_environment
    z[missing_indices], self.use_block, self.proj)
  File "/home/mosa/opendrift/opendrift/readers/basereader.py", line 400, in get_variables_interpolated
    block=block)
  File "/home/mosa/opendrift/opendrift/readers/basereader.py", line 292, in _get_variables
    env = self.get_variables(variables, time, x, y, z, block)
  File "/home/mosa/opendrift/opendrift/readers/reader_ROMS_native.py", line 400, in get_variables
    self.angle_xi_east = self.Dataset.variables['angle'][:]
KeyError: 'angle'

INFO: ========================
DEBUG: ----------------------------------------
DEBUG: Variable group ['land_binary_mask']
DEBUG: ----------------------------------------
DEBUG: Calling reader basemap_landmask
DEBUG: ----------------------------------------
DEBUG: Data needed for 1 elements
DEBUG: Reader time:
		None (before)
		None (after)
DEBUG: Fetching variables from basemap_landmask
DEBUG: Fetched env-before
DEBUG: No time interpolation needed - right on time.
DEBUG: Obtained data for all elements.
DEBUG: ---------------------------------------
DEBUG: Finished processing all variable groups
DEBUG: ------------ SUMMARY -------------
DEBUG:     x_sea_water_velocity: 0 (min) 0 (max)
DEBUG:     y_sea_water_velocity: 0 (min) 0 (max)
DEBUG:     x_wind: 0 (min) 0 (max)
DEBUG:     y_wind: 0 (min) 0 (max)
DEBUG:     land_binary_mask: 0 (min) 0 (max)
DEBUG: ---------------------------------
DEBUG: 		1 active elements
DEBUG: 		latitude =  -47.0
DEBUG: 		longitude = -79.0
DEBUG: 		z = 0.0
DEBUG: ---------------------------------
DEBUG: No elements to deactivate
DEBUG: Calling OceanDrift.update()
DEBUG: Applying wind drift factor of 0.019999999553 to 1 elements at surface
DEBUG: 1 active elements (0 deactivated)
DEBUG: Cleaning up
INFO: Zooming basemap to (-79.4 to -78.6 E), (-47.2 to -46.8 N)
Traceback (most recent call last):
  File "./ifop_mosa.py", line 39, in <module>
    RLCS=False)
  File "/home/mosa/opendrift/opendrift/models/basemodel.py", line 3701, in calculate_ftle
    lcs['ALCS'][i,:,:] = ftle(b_x1-X, b_y1-Y, delta, T)
  File "/home/mosa/opendrift/opendrift/models/physics_methods.py", line 58, in ftle
    dx = np.gradient(X) 
  File "/home/mosa/miniconda2/lib/python2.7/site-packages/numpy/lib/function_base.py", line 1754, in gradient
    "Shape of array too small to calculate a numerical gradient, "
ValueError: Shape of array too small to calculate a numerical gradient, at least (edge_order + 1) elements are required.

The configuration for the run is:

lcs = o.calculate_ftle(
    time=ifop_native.start_time + timedelta(hours=20),
    time_step=timedelta(minutes=60),
    duration=timedelta(hours=5), delta=1000,
    RLCS=False)

# Simulation from beginning and up to 30 hours (time of LCS)
o.reset()
o.seed_elements(lon=-73.3536, lat=-43.5851, number=1000, radius=1000,
                time=ifop_native.start_time)
o.run(end_time=ifop_native.start_time+timedelta(hours=20),
      time_step=timedelta(minutes=60))

**Comment by knutfrode** [comment]
This ROMS file seems to be missing the variable ```angle```, which is the angle between x and east directions. This is essential to rotate/orientate vectors properly.

**Comment by AndresSepulveda** [comment]
ok, fixed that. However, even when I seed the elements at

o.seed_elements(lon=-74.5, lat=-43, number=1000, radius=1000,
                time=ifop_native.start_time)

I quickly get  

DEBUG: ---------------------------------
DEBUG:          1 active elements
DEBUG:          latitude =  -47.0
DEBUG:          longitude = -79.0
DEBUG:          z = 0.0

and later

INFO: Exception:
INFO: All 1 particles (-79.00--79.00E, -47.00--47.00N) are outside domain of roms native (-79.00--72.00E, -47.00--40.99N)
DEBUG: Traceback (most recent call last):
  File "/home/mosa/opendrift/opendrift/models/basemodel.py", line 913, in get_environment
    z[missing_indices], self.use_block, self.proj)
  File "/home/mosa/opendrift/opendrift/readers/basereader.py", line 348, in get_variables_interpolated
    lat.max(), self.name, self.coverage_string()))
ValueError: All 1 particles (-79.00--79.00E, -47.00--47.00N) are outside domain of roms native (-79.00--72.00E, -47.00--40.99N)

Full log attached...

[salida.log](https://github.com/OpenDrift/opendrift/files/3064627/salida.log)

**Comment by knutfrode** [comment]
It seems you are overriding the default interpolation scheme to 'linearND'
Is there any particular reason for this? Otherwise I would recommend using the default (linearNDFast).

Element is moved to the corner of your reader, so I guess there is some issue with your ROMS file or the accompanying gridfile. Can you please post the output from printing this reader after its creation ```print ifop_native```
Does the boundaries look correct?
