### ISSUE TITLE
Problem installing OpenDrift

### ISSUE THREAD

**Issue by EllynnCM** [OpenDrift/opendrift#1069]
Hello,

I'm having problems installing Opendrift.
I'm new to python so i'm a complete newbie and might do obvsious mistakes.

I've follow the tutorial online to install it, using git, conda and created a news environment for opendrift.
I am now trying to run a example "seed_from_shapefile" but have the following error:

```
File ~\Miniconda3\envs\opendrift\Lib\site-packages\pyproj\network.py:10
    from pyproj._network import (  # noqa: F401 pylint: disable=unused-import

ModuleNotFoundError: No module named 'pyproj._network'
```

I have try to update everything, unistall and re install the package "pyproj"... I even tried to remove the '_' from the script 'pyproj._netwrok' without any success...

Anyone has a clue on what am I doing wrong ?

Thank you !

**Comment by EllynnCM** [comment]
I've managed to find the error!
Thx

**Comment by patnavgon** [comment]
Hi @EllynnCM, could I ask how did you solve the issue? I'm currently having the same problem with the pyproj._network submodule
