### ISSUE TITLE
LCS time steps and CMES file

### ISSUE THREAD

**Issue by AndresSepulveda** [OpenDrift/opendrift#107]
Hi,

 I would like to replicate the example_LCS_norkyst.py case with a model outpur from CMES that has daily timesteps. My first attempt wast to set

lcs = o.calculate_ftle(
    time=copas_native.start_time + timedelta(hours=240),
    time_step=timedelta(minutes=2880),
    duration=timedelta(hours=24), delta=1000,
    RLCS=False)

o.reset()
o.seed_elements(lon=-76, lat=-46, number=1000, radius=1000,
                time=copas_native.start_time)

o.run(end_time=copas_native.start_time+timedelta(hours=240),
      time_step=timedelta(minutes=2880))

but as a result I get the following error:

mosa@parti-mosa:~/Daniel$ ./copas_opendrift_LCS.py 
INFO: OpenDriftSimulation initialised (version 1.0.5)
INFO: Opening dataset: /home/mosa/Daniel/cmems_patagonia_1993-2017.nc
INFO: Opening file with Dataset
DEBUG: Finding coordinate variables.
DEBUG: Parsing variable: depth
DEBUG: Parsing variable: latitude
DEBUG: Parsing variable: longitude
DEBUG: Parsing variable: time
DEBUG: Parsing variable: vo
DEBUG: Parsing variable: uo
DEBUG: Parsing variable: land_binary_mask
DEBUG: Lon and lat are 1D arrays, assuming latong projection
DEBUG: Setting buffer size 49 for reader /home/mosa/Daniel/cmems_patagonia_1993-2017.nc, assuming a maximum average speed of 5 m/s.
DEBUG: Setting buffer size 12 for reader /home/mosa/Daniel/cmems_patagonia_1993-2017.nc, assuming a maximum average speed of 1 m/s.
DEBUG: Calculation SRS set to: +units=m +proj=latlong +ellps=WGS84
DEBUG: Using srs for common grid: +proj=latlong
DEBUG: Added reader /home/mosa/Daniel/cmems_patagonia_1993-2017.nc
INFO: No reader provided, using first available:
INFO: /home/mosa/Daniel/cmems_patagonia_1993-2017.nc
INFO: Calculating LCS for 1993-01-11 12:00:00
INFO: Nothing to reset
DEBUG: ------------------------------------------------------
DEBUG: Software and hardware:
DEBUG:   unknown GB memory
DEBUG:   4 processors (x86_64)
DEBUG:   Basemap version 1.0.7
DEBUG:   NumPy version 1.13.3
DEBUG:   SciPy version 0.19.1
DEBUG:   Matplotlib version 2.1.0
DEBUG:   NetCDF4 version 1.2.4
DEBUG:   Python version 2.7.14 |Anaconda, Inc.| (default, Oct 16 2017, 17:29:19) [GCC 7.2.0]
DEBUG: ------------------------------------------------------
INFO: Config validation OK
DEBUG: No output file is specified, neglecting export_buffer_length
INFO: Fallback values will be used for the following variables which have no readers: 
INFO: 	x_wind: 0.000000
INFO: 	y_wind: 0.000000
INFO: Backwards simulation, starting from last seeded element
INFO: Adding a dynamical landmask (resolution "i") based on assumed maximum speed of 1 m/s. Adding a customised landmask may be faster...
DEBUG: Creating Basemap...
Traceback (most recent call last):
  File "./copas_opendrift_LCS.py", line 36, in <module>
    RLCS=False)
  File "/home/mosa/opendrift/opendrift/models/basemodel.py", line 3697, in calculate_ftle
    self.run(duration=duration, time_step=-time_step)
  File "/home/mosa/opendrift/opendrift/models/basemodel.py", line 2041, in run
    projection='merc')
  File "/home/mosa/opendrift/opendrift/readers/reader_basemap_landmask.py", line 64, in __init__
    resolution=resolution, projection=projection)
  File "/home/mosa/miniconda2/lib/python2.7/site-packages/mpl_toolkits/basemap/__init__.py", line 988, in __init__
    self.aspect = (proj.ymax-proj.ymin)/(proj.xmax-proj.xmin)
ZeroDivisionError: float division by zero

Is there a problem with the timestep, timedelta, duration value? The Norkyst case runs fine.

Note: I've tried to update to opendrift 1.06 to no avail yet.

**Comment by knutfrode** [comment]
The LCS functionality has so far only been tested with projected datasets, and not with ROMS native (which has 2D arrays of lon and lat, instead of x,y in meters and a projection definition).
It could work, but then ```delta``` would be in ROMS pixel units, and not in meters.
So you could try with e.g. ```delta = 0.01```
But no guarantee it will work anyway, the LCS/FTLE feature is very experimental and immature!

Btw, you may update to the latest version (1.0.6) e.g. if using Git, which is highly recommended.
