### ISSUE TITLE
Bathymetry Data

### ISSUE THREAD

**Issue by joeelrahi** [OpenDrift/opendrift#108]
Hello,

I am working on a Pelagic model for Jellyfish where the vertical behavior is directly related to the bathymetry.  If I understood well, Opendrift NetCDF readers search for the variable sea_floor_depth_below_sea_level. For that I downloaded bathymetry data from GEBCO in .nc format, but this gives me an Attribute error (find it below):
_basereader.py: line 225, in set_buffer_size if self.time_step is none_
-AttributeError: 'Reader' object has no attribute 'time_step'

What would you propose to overcome this?
i) Should I take this data and create my own netCDF files?
ii) Would it be easier to create a new generic reader?
iii) To your knowledge, is there any website that provides 'sea_floor_depth_below_sea_level' for the Mediterranean Sea.

Thanks in advance
Joe

**Comment by knutfrode** [comment]
I will look at this within a couple of days, but in the meantime:
- yes, the simplest solution is probably to get bathymetry from the same file as the ocean model data. If not available in your own ocean current files, you can probably find something from CMEMS: http://marine.copernicus.eu/services-portfolio/access-to-products/

Perhaps the problem with the GEBCO-file, is that it contains no time steps, if it only contains a 2D-field of static bathymetry data. 

If this does not solve your problem, it would help if you could send more of your log with errors.

**Comment by joeelrahi** [comment]
Thank you for your reply!
As far as I know CMEMS has no bathymetry data but I will give it another try

**Comment by joeelrahi** [comment]
Hello again,

I wrote a script than adds a time variable to Bathymetry data and makes it compliant with Opendrift. If you think this is handy I am more than willing to share it !

Have a nice day

**Comment by knutfrode** [comment]
Good that it solved your problem!
Yes, I would be interest to see your code. Generally I would prefer to update/improve OpenDrift instead of users needing to update their input files, but I might do that based on your solution.

**Comment by joeelrahi** [comment]
"""
Created on Fri Apr 19 12:06:58 2019

@author: Joe El Rahi & Marc Weeber - Deltares, the Netherlands
"""

"""
Created on Fri Apr 19 09:54:04 2019
Purposely developed script to convert 2D bathymetry file into 
3 dimensional netCDF files in time and space compatible with
openDRIFT simulations

Bathymetry data obtained from GEBCO
Attention: Opendrift requires positive values for sea floor depth below sea level

"""

#%%
#creating the netCDF file

from netCDF4 import Dataset
dataset=Dataset('bathymetry_opendrift.nc','w',format='NETCDF4_CLASSIC')

#Adjust the size of latitude and longitude based on your grid size
lat=dataset.createDimension('lat',1066)
lon=dataset.createDimension('lon',1312)
time=dataset.createDimension('time',30)
#%%
print 'Lon dimension:', dataset.dimensions['lon']

for dimname in dataset.dimensions.keys():
    dim = dataset.dimensions[dimname]
    print dimname, len(dim), dim.isunlimited()
    
    #%%
import numpy as np
#Create the variables
times=dataset.createVariable('time', np.float64, ('time',))  
lat=dataset.createVariable('lat', np.float32,('lat',))
lon=dataset.createVariable('lon', np.float32,('lon',))
h=dataset.createVariable('sea_floor_depth_below_sea_level', np.float32, ('time','lat','lon'))
#%%
#accessing the variables
#print 'sea_floor_depth_below_sea_level variable:', dataset.variables['sea_floor_depth_below_sea_level']

for varname in dataset.variables.keys():
    var=dataset.variables[varname]
    print varname, var.dtype, var.dimensions, var.shape
    
#%%
    #Setting the attributes
import time
dataset.description='Bathymetry Data obtained from GEBCO'
dataset.history='Created' + time.ctime(time.time())
dataset.source='netCDF4 python module tutorial'

lat.units='degree_north'
lat.standard_name='latitude'
lat.long_name='latitude'

lon.units='degree_east'
lon.standard_name='longitude'
lon.long_name='longitude'



h.units= 'meter'
h.standard_name='sea_floor_depth_below_sea_level'


times.units= 'hours since 2019-04-09 00:00:00'
times.calendar='gregorian'

#%%
#Accessing attributes

print dataset.description

print dataset.history

#%%
#writing data

lat[:]=latsource
lon[:]=lonsource

print 'latitudes =\n', lat[:]

print 'sea_floor_depth_below_sea_level shape before adding data =', h.shape

from numpy.random import uniform

nlats=len(dataset.dimensions['lat'])
nlons= len(dataset.dimensions['lon'])
h[0:30,:,:]=uniform(size=(30,nlats,nlons))
print 'sea_floor_depth_below_sea_level shape after adding data = ', h.shape
#%%
for n in range(h.shape[0]):
    h[n,:,:]=elevation
    
    
#%%
#inserting time and date

from datetime import datetime, timedelta
from netCDF4 import num2date, date2num
dates=[]

for n in range(h.shape[0]):
    dates.append(datetime(2019,4,9) + n * timedelta (hours=24))
    
times[:]= date2num(dates, units=times.units, calendar=times.calendar)

print 'time values (in units %s) :' % times.units + '\n', times[:]

dates=num2date(times[:],units=times.units, calendar=times.calendar)

print 'dates corresponsing to time values :\n', dates

dataset.close()
#%%

**Comment by knutfrode** [comment]
I made now an update to OpenDrift, so that this preprocessing of the netCDF-inputfile should not anymore be necessary.

**Comment by ADevisM** [comment]
Hello 
I am trying to include bathymetry data following the ideas commented here, but still not working. What sould I do. I need real bottom depths and not a constant value of 'sea_floor_depth_below_sea_level' .
Thanks!

**Comment by knutfrode** [comment]
Is the bathymetry data included in your netCDF file, with ```standard_name``` attribute equal to ```land_binary_mask```?
If so, this variable should be listed if you print your reader with ```print r```

If not working, please post the output of  ```ncdump -h <netCDF-file>```

**Comment by AndresSepulveda** [comment]
Hi Knut, 

Shouldn't the variable with standard_name land_binary_mask have values of 1 and 0 only?

How does one adds the depth values?

**Comment by knutfrode** [comment]
My mistake, I corrected my comment above. So:
- ```land_binary_mask``` is ```standard_name``` with 1 for land and 0 for sea
- ```sea_floor_depth_below_sea_level``` is ```standard_name```  for depth below ocean surface, normally in meters.

**Comment by AndresSepulveda** [comment]
ok, In CROCO h is a little different standard_name

float h(eta_rho, xi_rho) ;
                h:long_name = "bathymetry at RHO-points" ;
                h:units = "meter" ;
                h:field = "bath, scalar" ;
                h:standard_name = "model_sea_floor_depth_below_geoid" ;
                h:coordinates = "lat_rho lon_rho" ;
but is easy to change it to what OpenDrift expects using the NCO tools

**Comment by knutfrode** [comment]
Yes, ```model_sea_floor_depth_below_geoid```does not seem to be an official ```standard_name``` according to [CF-convention](http://cfconventions.org/Data/cf-standard-names/66/build/cf-standard-name-table.html).

However, instead of manipulating your netCDF-file, you may instead map this as an [alias in basereader.py](https://github.com/OpenDrift/opendrift/blob/master/opendrift/readers/basereader.py#L97).

If it works for you we could consider adding that alias permanently.

**Comment by ADevisM** [comment]
It works, thank you all for your help!!!
I included the bathymetry data within the currents file and now it is reading it. The particles are settled at the correct depth.  Have a nice week!!

**Comment by ADevisM** [comment]
I used the GEBCO bathymetry which is better in this region, so I have to interpolate the data to the model grid. Then, I generated the netCDF file with the variable "dep" and finally I generated the attributes in GNU-Octave: netcdf_putAtt(FID,BATx,"standard_name","sea_floor_depth_below_sea_level");
netcdf_putAtt(FID,BATx,"long_name","h");
netcdf_putAtt(FID,BATx,"units","meter");
netcdf_putAtt(FID,BATx,"_FillValue",-32767);
The issue was to include the bathy data inside de currents-model file. I was using a separated file.

**Comment by gauteh** [comment]
Hi @oceandiff, I (hopefully) just fixed the specific error you encountered in latest master of opendrift. However, I do not think this is the root cause of your troubles. Please open a new issue with a longer log included if the issue persists.
