### ISSUE TITLE
Get the centre of the track

### ISSUE THREAD

**Issue by Dovelet1** [OpenDrift/opendrift#1082]
Dear all，

Is there some way to get a central drift track as shown below when using the Leeway model？
<img width="624" alt="image" src="https://user-images.githubusercontent.com/129474085/231182052-6d6b5628-61f5-4271-8f19-d8ae7ff8ebe2.png">

Thanks！

**Comment by knutfrode** [comment]
Hi,

Yes, there is a method `center_of_gravity` which will provide the center positions as well as the spatial variance:
https://opendrift.github.io/_modules/opendrift/models/basemodel.html#OpenDriftSimulation.center_of_gravity

Note that we have recently created a new package `TrajAn` for the analysis of output from OpenDrift, as well as any other model or measurements that follow the netCDF convention on trajectories. With TrajAn, you can do this more easily and transparently using Xarray syntax:
https://opendrift.github.io/trajan/gallery/example_opendrift.html#sphx-glr-gallery-example-opendrift-py

TrajAn does not have very much funtionality yet, but may still be worth testing out.

**Comment by Dovelet1** [comment]
Thanks for the fast reply.As you suggested, I have solved the problem using the method center_of_gravity. Next I will use TrajAnd to analyse my results. 
Thanks again for your help!
![image](https://user-images.githubusercontent.com/129474085/231191433-bf6ca2bc-a254-45b0-9c9e-ddd18cd98bb6.png)
