### ISSUE TITLE
importe "cmocean" could not be resolved

### ISSUE THREAD

**Issue by Alonso112358** [OpenDrift/opendrift#1086]
Hi,
I'm new using Open Drift, and I installed using conda(WSL) with VScode, but there is some warnings when I performance the test run,  like example_leeway. 
There is a message for "cmocean" that says "import cmocean could not be resolved" 
![image](https://user-images.githubusercontent.com/130098180/232927724-b69fd20e-9182-4416-9742-273b8b6fcc3e.png)

**Comment by knutfrode** [comment]
Hi,
I guess this is a problem with Pylance, and not with OpenDrift.

Maybe this will help:
https://stackoverflow.com/questions/68486207/import-could-not-be-resolved-could-not-be-resolved-from-source-pylance-in-vs-cod
