### ISSUE TITLE
Combining input files

### ISSUE THREAD

**Issue by IreneNA95** [OpenDrift/opendrift#1107]
Hi everyone,
I hope you're all doing well. I wanted to reach out to ask for some help with my particle advection experiments using the Opendrift code and the SHYFEM native readers.
My challenge is that I need to run the same program for multiple input data files, with each file corresponding to one month of SHYFEM simulation. I've attempted to add multiple SHYFEM readers for each file, but it didn't worked. I'm wondering if there's a way to combine several input files at the beginning of the experiment to get just one output. I'm hoping this approach would allow me to run a long-term simulation more efficiently.
If concatenating multiple input files isn't feasible, I'm wondering if there's a way to use the results from one simulation run as the initial conditions for the next simulation run.
Thank you for any help or advice you can offer.

**Comment by knutfrode** [comment]
Hi,
Did you try to use wildcards in filename, e.g. 
`r = shyfem.Reader(filename='shyfem_2022*.nc')`
Then they should me merged to a single dataset.

If you add several independent readers, there might be a gap of e.g. a few hours between them, and OpenDrift will not interpolate in time between different readers.

**Comment by knutfrode** [comment]
There is not automatic built-in method to start a simulation based on the output of a previous simulation. It should be possible to read output and seed again at final positions, but it would be a little awkward.

It is not clear why `var.getncattr` fails for you. 
I see line numbers do not mach latest version; did you do some local modification to shyfem.py?
Can you post the output from ncdump of one of these files?

**Comment by knutfrode** [comment]
I found that there seem to be a bug in netCDF4 so that `var.getncattr` does not work when using MFDataset:
https://stackoverflow.com/questions/34331005/getting-variable-attributes-from-netcdf-mfdataset-in-python/34334833#34334833

Thus I made a new commit to circumvent this. Please see if it works for you after updating OpenDrift.
https://github.com/OpenDrift/opendrift/pull/1108/files

**Comment by IreneNA95** [comment]
Hi,
Yes, actually I made some minor modifications to the code to enable the shyfem native reader to read environmental properties such as temperature and salinity, but those lines were commented when I obtained the error.

Anyway, I tried to update the OpenDrift code as you suggested, and now it's working perfectly. Thank you for your help and quick responses to all my questions! :)

**Comment by knutfrode** [comment]
Very good. Thanks for contributing to improvement! Then closing this issue.
