### ISSUE TITLE
netCDF file

### ISSUE THREAD

**Issue by arianjoel93** [OpenDrift/opendrift#111]
How can I write the transformed data from an unstructured grid to the regular grid in a netCDF file?
Thank You

**Comment by knutfrode** [comment]
Here is an example of how to do this:
https://earthscience.stackexchange.com/questions/12057/how-to-interpolate-scattered-data-to-a-regular-grid-in-python
If you would also comply with the [CF-conventions](http://www.cfconventions.org) including geographical specification, the file will be readable by OpenDrift, and much other software.

Alternatively, for OpenDrift, one can use a reader which support unstructured data directly. There is presently one reader, but it is very basic yet, to be improved in the future:
https://github.com/OpenDrift/opendrift/blob/master/opendrift/readers/reader_netCDF_CF_unstructured.py
