### ISSUE TITLE
all particles go to surface

### ISSUE THREAD

**Issue by CaroMedel** [OpenDrift/opendrift#1118]
HI,
The following is happening to me with Opendrift: At the first time step all the particles go up to z=0;
Sometimes this is fixed by adding the line o.set_config('drift:vertical_mixing', True) , but many times it is not fixed.
The z variable (for one particle), looks like this:
-8,2322025
0
0
0
0
0

I would like to know what are the possible reasons and solutions for this, i am using OceanDrift module
thank you

**Comment by CaroMedel** [comment]
hi?

**Comment by knutfrode** [comment]
Hi,
It is not clear why this is happening, as the default buoyancy (`terminal_velocity`) is 0 for particles in OceanDrift.
Perhaps you are adding an ocean model which has an upwards ocean current?

Can you make a minimalistic example which reproduces this issue?

**Comment by CaroMedel** [comment]
The simulation is using the upward ocean current from the hydrodynamic model. Maybe this upward current is too high?

**Comment by knutfrode** [comment]
That could be. You can disable the vertical advection (due to ocean vertical current, `w`) with
`o.set_config('drift:vertical_advection', False)`

**Comment by CaroMedel** [comment]
Thank you
