### ISSUE TITLE
Vertical seeding of particles?

### ISSUE THREAD

**Issue by AndresSepulveda** [OpenDrift/opendrift#112]
Hi,

I currently use the option 

  o.seed_elements(lon, lat, radius=2000,

to cover an area around the initial dispersion point.

Is there a way to seed particles randomly in the vertical as well, e.g. in the first 20 m?

**Comment by trondkr** [comment]
Hi Andres,

You can specify the depths to release at with the option 'o.seed_elements(lon, lat, radius=2000,z=[list of depths]') where length of 'listofdepths' equal number of particles. Or you can specify a specific depth level such as 'z="seafloor+1".

**Comment by AndresSepulveda** [comment]
Thanks Trond,

When using OceanDrift3D, besides the input  w field, what other options are to add vertical mixing to the particles?

**Comment by knutfrode** [comment]
Please note that depths (z) should be given as negative numbers.

Vertical advection (w) is switched on/off with:
```o.set_config('processes:verticaladvection', True)  # evt False```
Vertical mixing (turbulence) is switched on/off with:
```o.set_config('processes:turbulentmixing', True)  # evt False```
Turbulent mixing coefficient is either read from ocean model file, parameterised form wind, or 0.02 as constant fallback value.

To see all config options for a module, you can type:
```o.list_configspec()```
