### ISSUE TITLE
seeding from shape file

### ISSUE THREAD

**Issue by joeelrahi** [OpenDrift/opendrift#114]
Hello,

I am trying to see particles through a shape file (from QGIS) over a total period of 10 days.

As you can see in the attached pictures, when I use 100 000 particles the seeding process goes wrong and is not spatially confined to the polygon defined by the shapefile.

On the other hand, when I seed 100 particles the particle distribution is within the shape file.

Do you have any idea what might be wrong?

Thanks in advance,
Joe

![shapefile_100000](https://user-images.githubusercontent.com/49030919/59107424-e7b3b980-8938-11e9-933c-29817263de39.png)
![shapefile](https://user-images.githubusercontent.com/49030919/59107426-e7b3b980-8938-11e9-8b24-7b79fb5d3f9d.png)
![correct_release](https://user-images.githubusercontent.com/49030919/59107427-e84c5000-8938-11e9-841a-449dffbd9ded.png)

**Comment by knutfrode** [comment]
What are your calculation time step (time_step) and output time step (time_step_output) in these cases?

**Comment by joeelrahi** [comment]
(time_step) is the default 60

(time_step_output): 
for 10 000 particles: I set it to 3600

for 100 particles: default

**Comment by knutfrode** [comment]
There might be a bug here, in that the initial field shown (green) is in fact the first output field.
However, 60 seconds time_step is very small for this scale.
I would suggest using a time step of 3600 seconds, and the same (or e.g. 6 hours) for output.
time_step of 3600 is default for the built-in OpenDrift modules, but seems you are using your own module here.

**Comment by joeelrahi** [comment]
Hello again,

Thanks for the prompt response; with a time step of 60 mins and the default time_step_output the results are okey.

with kind regards,
Joe

**Comment by knutfrode** [comment]
Good.
Note that 60 minutes means that "time_step" should be 3600 (seconds).

**Comment by joeelrahi** [comment]
Ow! I might be confused; I built my model taking into account the following :

_o.list_configspec( )
general:time_step_minutes[60] integer(min=1, max=1440, default=60)_

So I assume when I run using o.run( ) the default time step is 1 hour ! is that the case?

**Comment by knutfrode** [comment]
Yes, you are correct!
For the config settings, which will be the default value, the time steps are given in minutes (as clearly indicated by the name of the key).

However, when starting a run, it is possible to override the time steps with keywords "time_step" and "time_step_output", which is either in seconds, or a datetime timedelta.

This should be better harmonized in the future. But actually I am considering generally to remove the too many input parameters to various functions like ```run()``` and instead rely in using the config-mechanism to customize a simulation. An advantage of this is that it is easier then to make generic graphical user interfaces.
