### ISSUE TITLE
Seeding from CSV file

### ISSUE THREAD

**Issue by joeelrahi** [OpenDrift/opendrift#115]
Hello,

working on my model I figured out that adding the option of feeding elements from a CSV files (which defines lon, lat and time) is handy. I implemented this with few lines of script using pandas.

#Required libraries
_import pandas as pd_
_from netCDF4 import num2data_

#adjust units depending on your data
_units="seconds since 1970-01-01 00:00:00.0"_

#define your input file
_inputfile='exportsheet.csv'_
_inputdf=pd.read_csv(input_file, sep=";")
for index, line in input_df.iterrows():
      lon=line[0]
      lat=line[1]
      time=line[2]
      time=num2date(time,units)
      o.seed_elements(lon,lat, number=1, time=time)_

**Comment by AndresSepulveda** [comment]
Great, very useful!

**Comment by knutfrode** [comment]
This works, but as there is some overhead for each call to ```seed_elements()```, it would be faster to first read in ```lon, lat, time``` as arrays, and provide these in a single call.

```number``` should then either be equal to the length of the arrays, and will default to this if not provided.
