### ISSUE TITLE
how to run openoil3d with 2d currents field?

### ISSUE THREAD

**Issue by llx206** [OpenDrift/opendrift#116]
hello
1. How to calculate horizontal movement of oil in water column when there’s only surface current provided? How the model define this situation?
For example, oil in water column run horizontally with surface current data (norkyst800_subset_16Nov2015.nc) in example_openoil3d.py.

2.The sea_floor_depth_below_sea_level was set as value of 10000 in example_openoil3d.py. but nearshore water is normally considered shallow, if follow the default setting, oil may not get that low, in which case the oil was calculated as hitting bottom. So how to set this value instead of the default value? 

Thanks in advance

**Comment by knutfrode** [comment]
Hi,

If the ocean model contains only one layer (surface), this is used throughout the water column (i.e. extrapolated towards the seafloor).

Normally you would have the ocean depth (variable ```sea_floor_depth_below_sea_level```) from your ocean model. Then particles will only be mixed down to this depth. The value of 10000m only serves as a kind of backup for the case where seafloor depth is not available.
