### ISSUE TITLE
Problems with user landmask

### ISSUE THREAD

**Issue by bmooremaley** [OpenDrift/opendrift#117]
I'm trying to run a simulation with my own landmask, but am running into a persistent error that I can't seem to troubleshoot:

ValueError: Simulation stopped within first timestep. "Missing variables: ['land_binary_mask']", 'The simulation stopped before requested end time was reached.'

although earlier in the debug output it actually looks like a problem with the interpolation. I've attached my run script and forcing files here.

[opendrift_test.tar.gz](https://github.com/OpenDrift/opendrift/files/3315807/opendrift_test.tar.gz)

**Comment by knutfrode** [comment]
Checking the landmask with the following command:
```$ readerinfo.py meshmask_opendrift.nc -p land_binary_mask```
indicates that there is some issue with the lon/lat-values.
![vancouver_landmask](https://user-images.githubusercontent.com/5222051/60019505-4e053f80-968e-11e9-98b3-fc9322c7414d.png)

Your longitudes vary between -123.17 and -124.54, but the landmask seems to include Seattle, further east (-122 longitude).
