### ISSUE TITLE
Deactivation of objects if sinked

### ISSUE THREAD

**Issue by shahbazbaig** [OpenDrift/opendrift#1186]
I am trying to run simulation for Object_type 73 which is about containers drifting based upon currents and wind components with Leeway model. I explored different config settings both for environment and processes but have not found how to handle if the containers have been sunk into water after couple of days to perform Search and Rescue based operations. 

If there are already such settings implemented please confirm.

**Comment by knutfrode** [comment]
Hi, There is no sinking in the Leeway model. Objects drift on the surface until they eventually hit land, where they become deactivated/stranded.

**Comment by shahbazbaig** [comment]
Hi, So do you know any model which can consider the sinking of model?

Thanks,

Shahbaz Baig
*Remote Sensing & GIS Specialist*
*MS Remote Sensing and GISc*

**Comment by knutfrode** [comment]
I believe no implementations of the Leeway S&R model contain sinking. And I am not familiar with other S&R drift models other than Leeway.
But most other OpenDrift modules contain sinking (or rising) as well as vertical advection and mixing.
It should also not be difficult to incorporate sinking feature in Leeway, but then one must somehow decide when and how often objects shall start sinking, and how fast.

**Comment by shahbazbaig** [comment]
I just want to add time that after a certain period there are possibilities
that container can be sink, just like it will sink in couple of hours if it
has been damaged while falling from vessel or days if not properly sealed.

Can you share your idea how we can incorporate it into leeway model if you
have understanding of Leeway implementation in OpenDrift?

**Comment by knutfrode** [comment]
This should be done in the `update` method of the relevant module.
I.e. here if you want to modify the Leeway model:
https://github.com/OpenDrift/opendrift/blob/master/opendrift/models/leeway.py#L356

There you could add some logics, and e.g. deactivate particles that should be sinking with 
`self.deactivate_elements(<condition for sinking>, reason='sinking')`

This would mean immediate deactivation at the location where sinking started.
If you would like to include the horizontal motion during sinking, you would need to build a model from scratch, as Leeway model is considering surface currents only. However, horizontal motion during sinking should probably be negligible, as scales of ocean depth is much smaller than horizontal scales.
