### ISSUE TITLE
Enhancement idea:  Support reading from an Intake catalog!

### ISSUE THREAD

**Issue by rsignell** [OpenDrift/opendrift#1187]
I found out about OpenDrift last week while visiting @ruoying He's modeling group at North Carolina State University.  They were struggling with performance using the native ROMS reader with `open_mfdataset()` on a large collection of NetCDF files.   

I think it would be cool to build a reader that reads ROMS files (and potentially other types of files) into Xarray using an [Intake](https://intake.readthedocs.io/en/latest/) catalog.   This would allow folks to then customize the characteristics of the dataset for reading in OpenDrift simply by modifying the catalog entry.    Also there are a growing number of zarr format datasets and collections of NetCDF files that have been transformed by [kerchunk](https://fsspec.github.io/kerchunk/) into virtual datasets readable by the Zarr library, and these would be accessible as well!

**Comment by gauteh** [comment]
Sounds great. It is possible to pass a xarray.Dataset to the generic reader already, this enables zarr datasets and possibly intake as well?

**Comment by rsignell** [comment]
Oh, perhaps we need to look at that.  Our first thought was to modify the roms native reader, since the NCSTATE use case was with ROMS output.  We took a stab here: https://github.com/OpenDrift/opendrift/pull/1188  but don't really know what we are doing. 

But the example dataset we are using there that doesn't need any credentials to pull data via Intake from a collection of NetCDF3-64-bit offset files on S3-compatible object storage, so it might be nice use case to try out.
