### ISSUE TITLE
Regarding the duration of the source (such as oil spill)

### ISSUE THREAD

**Issue by QidiMa** [OpenDrift/opendrift#1189]
Hi everybody,
 I have been using 'opendrive' for some time and its functions are really powerful and easy to use. Now I am running an oil spill model and want to add particles during the initial period of time. I want to know if it can be achieved.
Thanks in advance.

**Comment by knutfrode** [comment]
Hi,
I am not sure exactly what you mean, but here is a illustration of how to seed elements, e.g. over a time interval
https://opendrift.github.io/gallery/example_seed_demonstration.html

Here is the tutorial about seeding: https://opendrift.github.io/tutorial.html#seeding-elements

**Comment by QidiMa** [comment]
Thank you,
This is exactly what I want. I didn't read the document carefully enough. Thank you very much for your prompt recovery.
