### ISSUE TITLE
ROMS and wetting/drying masks

### ISSUE THREAD

**Issue by kthyng** [OpenDrift/opendrift#1196]
Hi! I need to override the constant values set in `consts.py` for "sea_floor_depth_below_sea_level" because in ROMS the depths are negative instead of positive and the default range defined is 0 to 12000. I have tried a few approaches for this, most recently:

Initial setup:
```
reader = reader_ROMS_native.Reader(loc)
ocean_drift_sim = OceanDrift(loglevel=20)
ocean_drift_sim.add_reader([reader])
```

then:
```
key = "sea_floor_depth_below_sea_level"
c = {}
c[f'environment:fallback:{key}'] = ocean_drift_sim.get_configspec()[f'environment:constant:{key}']
c[f'environment:fallback:{key}'].update({"min": -12000, "max": 0})
ocean_drift_sim._add_config(c)
ocean_drift_sim.set_config(f'environment:fallback:{key}', -10000)
```

Also, separately, tried this:
```
ocean_drift_sim.get_configspec()['environment:constant:sea_floor_depth_below_sea_level']["min"] = -12000
ocean_drift_sim.get_configspec()['environment:constant:sea_floor_depth_below_sea_level']["max"] = 0
```

But when I actually then seeded the simulation and ran it, I still got log messages like:
```
11:22:54 WARNING opendrift.readers.basereader.variables:635: Invalid values (-6.475353 to -0.3697905) found for sea_floor_depth_below_sea_level, replacing with NaN
11:22:54 WARNING opendrift.readers.basereader.variables:638: (allowed range: [0, 12000])
```

or in the case that I changed the fallback value:
```
16:26:17 WARNING opendrift.readers.basereader.variables:635: Invalid values (-10000.0 to -10000.0) found for sea_floor_depth_below_sea_level, replacing with NaN
16:26:17 WARNING opendrift.readers.basereader.variables:638: (allowed range: [0, 12000])
```

So, neither of these approaches seemed to "stick" and it seems that what is hard-wired into "consts.py" isn't meant to be overridden. Any suggestions for how to proceed? Thanks.

**Comment by kthyng** [comment]
The ROMS reader does seem to think the depths should be negative, for example:

https://github.com/OpenDrift/opendrift/blob/15546beb529f0d94629dc971a00b6edcb80dbf2b/opendrift/readers/reader_ROMS_native.py#L74-L78

unless I am over-interpreting those lines as being more meaningful than they are.

**Comment by kthyng** [comment]
@knutfrode Ah I realize now I conflated the depths of the drifter with the overall seafloor depth. Thank you for that clarification! I dug in and see the reason for some seafloor depths being negative: this model was run with wetting and drying on. Negative grid cells are where wetting and drying is allowed to occur, and then also in permanently masked areas (those all have a fixed negative value). Has opendrift been used in models/areas with wetting and drying?

**Comment by kthyng** [comment]
Just wanted to follow up here — any advice on using OpenDrift with wetting and drying model output?  Is there any special handling in this case? I can imagine if the cell is wet or dry then a tracking algorithm would just work as usual, but might need some special care in the case that a cell becomes dry underneath a drifter — does it become stranded in that case?

**Comment by kthyng** [comment]
> Coastline stranding is determined by the binary landmask (land_binary_mask) and not the ocean depth variable (sea_floor_depth_below_sea_level) 

Ok that makes sense, though what about in the scenario that the following warning occurs which says depths have been changed to nan — does that add the nan-ed location to the landmask in effect? It looks to me from some cases I'm running and plotting that these grid cells with negative depth are in fact still being used but the warning makes it sound otherwise.

```
11:27:05 INFO    opendrift.models.basemodel:1989: 1999-02-01 02:00:00 - step 3 of 4 - 100 active elements (0 deactivated)
11:27:32 WARNING opendrift.readers.basereader.variables:635: Invalid values (-11.243423 to -0.09407605) found for sea_floor_depth_below_sea_level, replacing with NaN
```


> However, you'd might here instead want particles to "wait" on the dried location, and then one could (internally) instead set self.elements.moving to 0 for the elements where depth is negative ... With this solution, one can keep the assumption in ROMS reader that land_binary_mask is 2D/static, as sea_floor_depth_below_sea_level is used instead

The variable `sea_floor_depth_below_sea_level` is static in time. `mask_rho` shows the cells that are never active as land and everything that could ever be active as active.  `sea_floor_depth_below_sea_level` has negative depths where wetting and drying can occur, but it depends on the time-varying sea surface height on top of `sea_floor_depth_below_sea_level` for whether a location is wet or dry. So to try the functionality in the sediment module, which I think is a good idea, I would want to check the value of `sea_floor_depth_below_sea_level` + `sea_surface_height` to see if a cell is wet or dry.

**Comment by knutfrode** [comment]
There is a "safety-mechanism" in OpenDrift to ensure that environment variables have reasonable values, e.g. avoiding problems with corrupted file in an operational setup.
`sea_floor_depth_below_sea_level` is expected to be between 0 and 12000:
https://github.com/OpenDrift/opendrift/blob/master/opendrift/readers/basereader/consts.py#L20

One could here set the minimum value to e.g. -10 (?) to allow for drying cells.

It should be fine to check `sea_floor_depth_below_sea_level` + `sea_surface_height`, but the latter must then also be added to required variables in the actual module. It may however have 0 as a default value to be used whenever is is not available from any readers.

**Comment by kthyng** [comment]
As a follow up, I used the wet/dry mask as the land binary mask and allowed it to vary in time to solve my problem. Thanks for your guidance.

**Comment by knutfrode** [comment]
Very good!

**Comment by knutfrode** [comment]
Perhaps you can set the fallback value for seafloor depth to 0:
`>>> o.set_config('environment:fallback:sea_floor_depth_below_sea_level', 0)`
(This can also be hardcoded within your module, by setting `fallback` to 0 for `sea_floor_depth_below_sea_level` in `required_variables`dictionary)

Then `self.environment.sea_floor_depth_below_sea_level` will be set to 0 whenever an "illegal value" (i.e. <0) is encountered. 
And then you could use this as the condition for a drying cell in your module.
You will then also get 0 if it becomes larger than maximum (12000m), but you can probably assume that this is not going to happen (unless a corrupted file).

**Comment by kthyng** [comment]
It looks like the "bad" values are always replaced with nan regardless of the fallback value:

https://github.com/OpenDrift/opendrift/blob/7aae898f383052e803e28aef6d32434327f4520d/opendrift/readers/basereader/variables.py#L642-L650

If we were to change the minimum depth value to -10 to allow for drying cells (in consts.py) would that allow the drifters to move freely in the cells that are temporarily dry? Or is the depth used for some part of the drifter movement such that having a negative depth would cause an issue?

If that would be an issue, the only thing I can think of is making the depth also vary in time (like the mask) and have it update with the water column depth (h+zeta) each time step. I might be able to make that change outside of opendrift and input the modified Dataset to opendrift (with the new version that allows for inputting Datasets to the ROMS reader) but would still need to modify the ROMS reader to allow for time-varying depth.

**Comment by knutfrode** [comment]
I believe thse NaN-values are later replaced with the fallback value?
Otherwise I don't think negative ocean depth would make a problem somewhere, in contrary to positive z-value (particle depth, or rather height (positive upwards), not to be confuse with seafloor depth) for which there are some checks in some of the modules.

It would be a pity having to physically modifying the input forcing fields, as it should be possible to fix somehow with the code. Can you try to set the `valid_min` to -10 here:
https://github.com/OpenDrift/opendrift/blob/master/opendrift/readers/basereader/consts.py#L20
If that works, I can see if there is (or make) a way to do this without needing to modify that file.

**Comment by kthyng** [comment]
@knutfrode Yes changing the consts.py code does fix the issue of the warning that my wet/dry cells have been nan'ed out.

```
    'sea_floor_depth_below_sea_level': {'valid_min': -10, 'valid_max': 12000,
                         'long_name': 'Depth of seafloor'},
```

With that change, I don't get any more warnings like

```
12:13:24 WARNING opendrift.readers.basereader.variables:635: Invalid values (-2.4052637 to -2.4052637) found for sea_floor_depth_below_sea_level, replacing with NaN
```

**Comment by knutfrode** [comment]
Good.
I now made this a permanent change in OpenDrift, as it does not seem to interfer with anything else:
https://github.com/OpenDrift/opendrift/commit/debdf6b53e6ef1fb6a7f7340f368de43071c2f57

**Comment by knutfrode** [comment]
Does this solve the problem, or are there more issues related to this?

**Comment by kthyng** [comment]
@knutfrode Yes thank you, this resolves this issue. I plan to submit a PR for the ROMS reader with my changes for using the wet/dry mask as well as a few other things. Still working on it for now though. Thanks for your help!

**Comment by knutfrode** [comment]
Closed by https://github.com/OpenDrift/opendrift/pull/1264
