### ISSUE TITLE
Inquiry about 'get_variables_along_trajectory' Attribute Error in OpenDrift

### ISSUE THREAD

**Issue by HatYaz** [OpenDrift/opendrift#1220]
Subject: Inquiry about 'get_variables_along_trajectory' Attribute Error in OpenDrift

Dear OpenDrift Specialist,

I hope this message finds you well. I am currently working on a project involving the use of OpenDrift for trajectory simulations. While attempting to use the 'get_variables_along_trajectory' method as documented, I encountered an AttributeError.

Here is the relevant code snippet:
cur_traj = o.get_variables_along_trajectory(variables=['x_sea_water_velocity', 'y_sea_water_velocity'],
                                          lons=lon_mtr,
                                          lats=lat_mtr,
                                          times=times_sim)

The error message I received is as follows:

AttributeError: 'OceanDrift' object has no attribute 'get_variables_along_trajectory'

I have reviewed the OpenDrift documentation, and it seems that 'get_variables_along_trajectory' should be a valid method for the 'OceanDrift' class. Could you please provide guidance on resolving this issue or clarify if there have been any changes in recent versions of OpenDrift that may affect the usage of this method?

Thank you in advance for your assistance.

**Comment by HatYaz** [comment]
Thanks. Worked fine now. 
Kindly keep me in the loop for any new updates since I am actively involved in a project using opendrift.
Regards,
Hatem

**Comment by knutfrode** [comment]
At second thought, it seems more logical that this method is a sub-method of `env` as this is a method that could be called from an Environment without a simulation object. 
Thus we should probably keep it as it is, so that the syntax to use is: `o.env.get_variables_along_trajectory()`

**Comment by HatYaz** [comment]
Hi 
I am using opendrift Version: 1.14.8
Here my line: 
cur_traj = o.get_variables_along_trajectory(variables=['x_sea_water_velocity', 'y_sea_water_velocity'],
                                               lons=lon_mtr,
                                               lats=lat_mtr,
                                               times=times_sim)
and I had: 
AttributeError: 'OceanDrift' object has no attribute 'get_variables_along_trajectory'

I am wondering if in this version you made the cnage to : o.env.get_variables_along_trajectory ??

**Comment by knutfrode** [comment]
Yes, correct syntax is `o.env.get_variables_along_trajectory()`

**Comment by HatYaz** [comment]
Thanks Knut. Where can I find the recent updates done on OpenDrift?
