### ISSUE TITLE
Packaging

### ISSUE THREAD

**Issue by JoyMonteiro** [OpenDrift/opendrift#123]
Hello,

Thanks for the great project! Makes life simpler for many of us out there.
are there any plans to distribute the package via PyPI or conda-forge?

As far as I can see, the only issue for a PyPI release is that PROJ4, libgdal and libnetcdf will have to be pre-installed. This should not be an issue for Linux or Mac since package managers
can take care of this.

**Comment by knutfrode** [comment]
Hi,

Yes, I agree that conda or PyPi packaging would be great.
I have never made such packages myself, but might look into that soon.
In the meantime, any links to step-by-step tutorials (e.g. omitting the Proj4/libgdal/libnetcdf issues) or other useful references would be welcome.

**Comment by JoyMonteiro** [comment]
I'm more familiar with PyPI, so here goes:

Since the project is using setuptools, then once you are ready to release a
package, the process is very simple.

* [Create a source distribution and wheel](https://packaging.python.org/guides/distributing-packages-using-setuptools/#packaging-your-project). Since opendrift is pure python, you can build a universal wheel.

* You can then register for an account on https://test.pypi.org/ to test out your deployment.

* Package uploading is normally done using [twine](https://pypi.org/project/twine/)

* Once you ensure that the package sucessfully installs from test pypi, you can use the same process to upload it to PyPI.

This and other details are available [here](https://packaging.python.org/tutorials/packaging-projects/)

* If you think that you would prefer Travis to automatically upload to PyPI when a tagged commit (release) is successfully tested, [that is fairly easy to setup as well](https://docs.travis-ci.com/user/deployment/pypi/)

**Comment by gauteh** [comment]
Opendrift is now packaged to conda.
