### ISSUE TITLE
Simulation attributes / animation attributes

### ISSUE THREAD

**Issue by Jallel30** [OpenDrift/opendrift#124]
Hi! I'm a noob using the Opendrift software, and I was looking for the commands to modify some attributes (particle size and color, legend position, graphic title and if I can add some logos aside of the graphic, among others).
Can anybody help me? Is there any list of attributes available?

**Comment by knutfrode** [comment]
The ```plot()``` and ```animation()``` methods have several extra parameters which may be provided, although still with minimal documentation:
https://github.com/OpenDrift/opendrift/blob/master/opendrift/models/basemodel.py#L2930
https://github.com/OpenDrift/opendrift/blob/master/opendrift/models/basemodel.py#L2570

Also, you may get a handle to the Basemap instance and pyplot instance (with further access to ```gca```), and further modify as you like:
```
map, plt = o.plot(......)
```
