### ISSUE TITLE
Missing data problem with telemac reader

### ISSUE THREAD

**Issue by taoansf** [OpenDrift/opendrift#1246]
Hello,

I am experiencing a problem of missing_data with a high resolution simulation using telemac reader as showon in the picture below.

![missing_data](https://github.com/OpenDrift/opendrift/assets/22460776/ee754850-8f1f-4691-b3d1-22ee663c4900)

I have done many tests and noted that the problem is related with the seeding method using this script of 3 hours seeding.
 _o.seed_elements(lon=lon, lat=lat, number=1000, time=[start_time,start_time+timedelta(hours=3)],z=-2,
                    terminal_velocity=-0.0002)  # 0.2 mm/s settling speed_

If I use an instantaneous seeding the problem does not occurs.

Is there any way to avoid this problem using some configuration that guarantees that the reader's buffer covers the seeding area? 

I already tried using the method of adjusting o.max= speed and reader.buffer= to high values, but I was unsuccessful.

This is my run script

_P1 = ['P1',-39.026076,-14.767201]

#definindo a data de lancamento
start_time = datetime(2021,10,1,0,0,0)
#end_time=datetime(2021,10,30,23,0,0)
#duracao=end_time-start_time#timedelta(hours=duracao)

proj="EPSG:32724"
telemac3d = reader_telemac_selafin.Reader(simulacao,proj4=proj)
#telemac3d.buffer=1000000000000000000000000000000
#telemac3d.set_buffer_size(max_speed=3, time_coverage=timedelta(hours=12))
o = SedimentDrift(loglevel=20)  # 0 for debug output
o.add_reader(telemac3d)
#linha de costa
o.add_reader(landmask)
o.set_config('general:use_auto_landmask', False)
#o.set_config('general:coastline_action', 'stranding')
o.set_config('general:seafloor_action', 'deactivate')
o.set_config('drift:horizontal_diffusivity', 0.02)#difusao horizontal 0.02 m2/s
o.set_config('vertical_mixing:diffusivitymodel', 'windspeed_Large1994')
o.set_config('environment:fallback:ocean_vertical_diffusivity', 0.0001) # m2/s
o.set_config('vertical_mixing:resuspension_threshold', 3.0)#velocidade de ressuspensao, 3 para nunca ressuspender
#o.max_speed=50.0
#o.time_coverage=timedelta(hours=48)

lat=P1[2]
lon=P1[1]
horas=3
o.seed_elements(lon=lon, lat=lat, number=1000, time=[start_time,start_time+timedelta(hours=3)],z=-2,
                    terminal_velocity=-0.0002)  # 0.2 mm/s settling speed

o.run(time_step=600, time_step_output=1800, duration=timedelta(days=3))_

With best regards,

Taoan

**Comment by taoansf** [comment]
Hello,

I create a simple test to check if the my problem is the selafin reader.  This manner, I create a generic netcdf from telemac currents data and run opendrift using this netcdf reader. The problem was not solved by changing reader format.

I attached my test for community evaluation. I'm suspicious that there may be a problem related to the resolution of my data. Unfortunately I still haven't been able to find a way to configure opendrift to work with it.

[test.zip](https://github.com/OpenDrift/opendrift/files/14539487/test.zip)

With best regards,

Taoan

**Comment by taoansf** [comment]
Hello community,

A new observation related with my problem of missing data...  The problem does note occurs if I disable the use of my landmask from shapefile.

This manner, the problem is not caused by the high resolution data.

This post https://github.com/OpenDrift/opendrift/issues/359#issuecomment-694278186 indicate the use of this configuration to set shapefile mask to work _o.fallback_values['land_binary_mask'] = 0_
I try to use this configuration but I got this error message
_Traceback (most recent call last):
  Cell In[20], line 1
    o.fallback_values['land_binary_mask'] = 0
AttributeError: 'SedimentDrift' object has no attribute 'fallback_values'_

I would be grateful for any suggestions.

With best regards,

Taoan

**Comment by knutfrode** [comment]
Hi, issue 359 is using an outdated syntax for setting fallback values. The correct is now
`o.set_config(key, value)`
which is for your case:
`o.set_config('environment:fallback:land_binary_mask, 0)`

**Comment by taoansf** [comment]
Hello knutfrode,

Yes, the setting is working properly now and solved the missing data problem.

Thank you very much for the support.

Taoan
