### ISSUE TITLE
Particles not moving

### ISSUE THREAD

**Issue by AndresSepulveda** [OpenDrift/opendrift#125]
Hi,

I am releasing particles using output from CROCO. The velocity fields look ok in the original NetCDF file, but the particles never move when released (over the ocean)

This is the python code being used

[drift.py.txt](https://github.com/OpenDrift/opendrift/files/3478732/drift.py.txt)

and this is the output

[2019-08-07_15-32-39_305186.txt](https://github.com/OpenDrift/opendrift/files/3478726/2019-08-07_15-32-39_305186.txt)

where one KeyError that appears is

15:32:53 INFO: Exception:
15:32:53 INFO: 'mask_rho'
15:32:53 DEBUG: Traceback (most recent call last):
  File "/home/mosa/new_opendrift/opendrift/opendrift/models/basemodel.py", line 932, in get_environment
    z[missing_indices], self.use_block, self.proj)
  File "/home/mosa/new_opendrift/opendrift/opendrift/readers/basereader.py", line 444, in get_variables_interpolated
    block=block)
  File "/home/mosa/new_opendrift/opendrift/opendrift/readers/basereader.py", line 323, in _get_variables
    env = self.get_variables(variables, time, x, y, z, block)
  File "/home/mosa/new_opendrift/opendrift/opendrift/readers/reader_ROMS_native.py", line 356, in get_variables
    self.mask_u = self.Dataset.variables['mask_rho'][:]
KeyError: 'mask_rho'

but also everything seems to be zero

15:32:53 DEBUG: ---------------------------------------
15:32:53 DEBUG: Finished processing all variable groups
15:32:53 DEBUG: ------------ SUMMARY -------------
15:32:53 DEBUG:     x_sea_water_velocity: 0 (min) 0 (max)
15:32:53 DEBUG:     y_sea_water_velocity: 0 (min) 0 (max)
15:32:53 DEBUG:     x_wind: 0 (min) 0 (max)
15:32:53 DEBUG:     y_wind: 0 (min) 0 (max)
15:32:53 DEBUG:     land_binary_mask: 0 (min) 0 (max)

My configuration is

------------------------------------------------------
Software and hardware:
  OpenDrift version 1.0.6
  7 GB memory
  4 processors (x86_64)
  Basemap version 1.1.0
  NumPy version 1.13.3
  SciPy version 0.19.1
  Matplotlib version 2.1.1
  NetCDF4 version 1.3.1
  Python version 2.7.15+ (default, Nov 27 2018, 23:36:35) [GCC 7.3.0]
------------------------------------------------------

**Comment by knutfrode** [comment]
It appears that this croco-file does not have masks defined at rho-coordinate points, like other ROMS files. Could you please check with ```ncdump -h <file>``` if the file contains some other masks?

**Comment by AndresSepulveda** [comment]
The file with the velocity fields doesn't. But I influede a grdfile that was included in the calling to the reader does (see the included .py file before)

**Comment by knutfrode** [comment]
The gridfile would only provide georeference (lon/lat arrays), so the masks have to be included in the main netCDF file.
Perhaps these have been omitted when post-processing the output from croco?

**Comment by AndresSepulveda** [comment]
That was it. I merged the grid file into the velocity file, as it is quite small. Thanks.

**Comment by Angel-Ga** [comment]
Hi, I have the same problem with the masks, can you tell me how did you merge it so that you can make your particles move?

**Comment by Angel-Ga** [comment]
> Hi, I have the same problem with the masks, can you tell me how did you merge it so that you can make your particles move?



> That was it. I merged the grid file into the velocity file, as it is quite small. Thanks.

Hi, I have the same problem with the masks, can you tell me how did you merge it so that you can make your particles move?
