### ISSUE TITLE
MemoryError for openoil simulation from shape file + seed

### ISSUE THREAD

**Issue by IGanch** [OpenDrift/opendrift#127]
Hi,
I'm running an openoil simulation with 64 bit python, seeding particles from two sources - particular coordinates and from a shape file. I've been doing this with quite a few examples and it worked out good. Yesterday I stumbled upon a `MemoryError` for one shape file, which was a bit bigger than the others and after separating it in two the simulation ran without problems. 
However I've tried another example with a new shape file which covers quite small area and I got the same `MemoryError` again.
Any ideas how to fix it without having to separate the file in smaller parts?
Here is the error message:
```
Traceback (most recent call last):
  File "BS_opendrift/BS_seed_shapefile_currents.py", line 37, in <module>
    oiltype=oiltype2)#, oil_film_thickness=0.05)
  File "/home/irina/opendrift/opendrift/models/basemodel.py", line 1749, in seed_from_shapefile
    self.seed_within_polygon(lons, lats, num_elements, **kwargs)
  File "/home/irina/opendrift/opendrift/models/basemodel.py", line 1585, in seed_within_polygon
    x, y = np.meshgrid(xvec, yvec)
  File "/home/irina/miniconda2/envs/opendrift_p2_oil/lib/python2.7/site-packages/numpy/lib/function_base.py", line 4211, in meshgrid
    output = [x.copy() for x in output]
MemoryError
```

Cheers!

**Comment by knutfrode** [comment]
Hi,

How many elements are seeding here? Does it help if you reduce the number of elements?
This might also be caused by wrong projection information in the shapefile, I have encountered that before. If you could attach one such shapefile, I could have a look.

**Comment by IGanch** [comment]
Hey,
in this case I'm seeding 200 elements from the shape file and 200 from the coordinate source. I've tried also with 10 elements each, getting the same error.
I'll attach the shape file. It's possible that there are some projection errors as I'm converting netcdf files to shape files, however with the 20 other files I've tried it was OK.
Thanks a lot!




[shp.tar.gz](https://github.com/OpenDrift/opendrift/files/3533802/shp.tar.gz)

**Comment by knutfrode** [comment]
In your shapefile there are 125 features. Seeding works fine except for the very last one, which seems degenerate. The 5 points (below) are all on one line, thus the area of the polygon is close to zero.
If you remove this one, it should be ok.

[[27.74345929 42.52551347]
 [27.74382452 42.5255111 ]
 [27.74370278 42.52551189]
 [27.74333755 42.52551426]
 [27.74345929 42.52551347]]

**Comment by knutfrode** [comment]
In the meantime I made an [update](https://github.com/OpenDrift/opendrift/commit/e707b6a4cab6c3230e3acd65c149c4538a19a5f9), making ```seed_from_shapefile``` more robust.
Seeding works fine from your file now.

**Comment by IGanch** [comment]
I've updated the model and now the simulation runs with the shapefile. 
Thanks a lot for the fast response and solution!
