### ISSUE TITLE
Save simulation 

### ISSUE THREAD

**Issue by Jallel30** [OpenDrift/opendrift#128]
Hello everyone,
I was wondering if there’s a code line or something that let me save the trajectories of the simulations in .shp; and if it’s possible saving just the cartography where the particles end in the simulation.
Also, I wanted to know what is the output format of the simulations.

Thanks!!

**Comment by knutfrode** [comment]
Hi,
There is presently not a method to save trajectories to shapefiles. But this could "easily" be written by anyone with interest and relevant knowledge.

The [native output is netCDF](https://github.com/OpenDrift/opendrift/wiki/Sample-output-file), containing not only trajectories, but all the properties and the environment (wind, temperatures, current...) for each element at each time step.
There are also methods to write output to GeoTiff (```write_geotiff```) or netCDF (```write_netcdf_density_map```)  density maps, but this is based on counting the number of elements within bins, and thus discards information about individual elements.

**Comment by mlicer** [comment]
Hello everyone, if i may expand the trajectory question a bit: is there a way to include trajectories plots in the .gif animation? I don't mind writing this visualization myself, but i'd prefer to use an opendrift *kwarg option if it already exists...

**Comment by knutfrode** [comment]
Yes, you can get trajectory lines below the moving points like this:
```
>>> o.animation(show_trajectories=True, filename='animation.mp4')
```

Note that is is recommended to save as MP4 instead of GIF as this gives much smaller files, and then rather convert to GIF afterwards if needed (e.g. this online service https://ezgif.com/video-to-gif)

**Comment by mlicer** [comment]
Dear Knut, thanks for your reply! This does work, thank you. 
But it only works after i `git reset --hard 90ce36235661bcca4fbb76eb24c49287c0d3a9df`
Should it work out of the box for `git clone https://github.com/OpenDrift/opendrift.git`? If it should, something is wrong with my install i guess...

**Comment by gauteh** [comment]
Hi @mlicer, it should work with latest master as well (I just tested with the example.py script). Do you have a minimal example which breaks or a log of the error message. If not, coudl you try the example.py file modified to `show_trajectories` ?

**Comment by knutfrode** [comment]
There is presently no way to save a figure directly for a given time step, but I agree it would be useful. 
At the moment we are working on replacing Basemap with Cartopy in ```plot``` and ```animation``` methods, by just transferring current functionality. However, quite soon we might look at redesigning these methods to allow such functionality.

**Comment by mlicer** [comment]
Dear @gauteh, @knutfrode  - i can confirm that `show_trajectories` does work on the latest master. I guess mine was a bit outdated. The error was of the 'unknown kwarg' type so i think i must have been using an older class without it.
Thank you both for your help!

**Comment by gauteh** [comment]
Great! Is there anything else in this issue or should we close it?

**Comment by mlicer** [comment]
I guess you've cleared everything, thanks!
