### ISSUE TITLE
Bug in ROMS native reader

### ISSUE THREAD

**Issue by ivicajan** [OpenDrift/opendrift#1281]
Hi,
think you should add "angle" as a variable you want to keep when using mfdataset (multiple files). Otherwise, you can't rotate roms currents. This does not affect a single file read.
Basically, in line 156 of opendrift/readers/reader_ROMS_native.py should add "angle" among other variables (Vtransform etc).

Cheers,
Ivica

**Comment by knutfrode** [comment]
Hi,

Kristin Thyng recently made a method `angle` which dynamically loads the angle whenever needed:
https://github.com/OpenDrift/opendrift/blob/master/opendrift/readers/reader_ROMS_native.py#L376

This seems to work well, as all tests are passing.
Are you getting any problems related to this?

**Comment by ivicajan** [comment]
Hi Knut,
if you look at the 156 line then you'll see that you are keeping just a subset of static variables and there is no angle. This is using Xarray drop_variables option and is relevant only when you open multiple files via Xarray.

I do have a problem if I load multiple roms files in a folder (i.e. roms =  reader_ROMS_native.Reader('roms_his_204*.nc')

In case I modify line 156 from the original:
                                    'Cs_r', 'hc', 'Vtransform']
into:
                                    'Cs_r', 'hc', 'Vtransform', 'angle'] 

it is working OK.

Cheers,
Ivica

**Comment by MoraneC** [comment]
Hi all,
@ivicajan @knutfrode, I had the same issue with multiple roms files. When adding 'angle', at l.156 in reader_ROMS_native, as you did, it worked for me as well.

Best,

Morane

**Comment by knutfrode** [comment]
I do not have Roms native files readily available for testing, but trust you are right.

`angle` was removed from the opened Dataset in this commit:
https://github.com/OpenDrift/opendrift/commit/006cee6f53c966999d9e195c4ae46e4848ae0bdd
@kthyng It is ok to add back `angle` on line 156, or would that interfere with anything else?
Have you tried the ROMS reader yourself with multiple files (e.g. wildcards in filename)?

**Comment by ivicajan** [comment]
Hi Knut,
yes, it is safe to add suggested change.
Tried with multiple files (*.nc) when it is invoking xr.open_mfdataset and using drop_variables option.

Cheers,

Ivica
________________________________

**Comment by kthyng** [comment]
@knutfrode I am pretty sure my intention in removing `angle` from that list was to keep it from being dropped, so that was an accident. Sorry about messing that up!

**Comment by knutfrode** [comment]
No problem, but then it makes all sense.
I have now corrected this in master: https://github.com/OpenDrift/opendrift/pull/1284/files
Thus closing this issue.
