### ISSUE TITLE
Model time series data in multiple files

### ISSUE THREAD

**Issue by nsoontie** [OpenDrift/opendrift#133]
I'm looking for advice when building a reader for model time series data stored in multiple files, eg. 20190910.nc, 20190911.nc, 20190912.nc where each file stores hourly outputs for the date represented by the file name. That is, each files contains timestamps 00:30, 01:30, ... 23:30 for that day.

My first approach was to build a reader for each file, add the reader to a list and then add the list of readers to the opendrift object.
```python
readers = []
for f in files:
   r = reader_netCDF_CF_generic.Reader(f)
   readers.append(r)
o.add_reader(readers)
```
but I realized that this was incorrect because the particle velocities go to zero at times between the file timestamps (eg. 23:30 to 00:30). There is no reader that covers this time period.

My next approach was to create a single reader by passing the list of files to the reader initializer and then add that reader to the opendrift object
```python
reader = reader_netCDF_CF_generic.Reader(files)
o.add_reader(reader)
```
At first, I received an error that netCDF4.MFDataset cannot work with netCDF 4 files. I changed the file format to netCDF4_classic and was successful. And the particle velocities were continuous during the whole simulation as expected (image below)

![image](https://user-images.githubusercontent.com/9750865/65374783-5c9ccc00-dc68-11e9-884e-9c0912da7be1.png)

Two questions:
1. Is the behaviour in my first approach expected? 
2. Are there any plans to modify reader_netCDF_CF_generic so that it will work the netCDF4 files?

**Comment by knutfrode** [comment]
Hi,
Yes, for 1) this is as expected.

Thus method 2) is recommended to fill the gap between the files. The problem is that python-netcdf does not support MFDataset for netcdf 4, but if you install xarray (and perhaps dask as well), then the reader will use this instead. Then it is not necessary to convert the files to classic.

**Comment by nsoontie** [comment]
Thanks for the quick response! I'm glad to have some assurance that my first approach is incorrect.

I will look at xarray and dask. It's too bad that python-netcdf does not support netCDF 4 files at the moment.

**Comment by knutfrode** [comment]
It is enough to just install xarray (and possibly dask). Thereafter you may use OpenDrift as before, as the reader will detect xarray and use it instead of python-netcdf.

**Comment by nsoontie** [comment]
It doesn't look like the reader_netCDF_CF_generic or reader_netCDF_CF_unstructured use xarray but reader_RMOS_native does.

**Comment by knutfrode** [comment]
You seem to be right!
I can update the generic reader to have this functionality as well, but will unfortunately not have time until next week, at earliest.

**Comment by nsoontie** [comment]
I submitted a pull request for using xarray in reader_netCDF_CF_generic

**Comment by knutfrode** [comment]
Excellent, I will have a look at this tomorrow.
Did you test if the xarray-solution works for the netCDF_CF_generic-reader?

**Comment by nsoontie** [comment]
Great! I'm not sure it's the best solution but it works for me so I thought I would share. 

I did run a successful ocean drift simulation using xarray in the generic reader with my own data but I didn't test with any of the example scripts on the OpenDrift repo.

**Comment by knutfrode** [comment]
I added a fix for the case when user does not have Xarray. Now all tests pass in either case.
Thank you for the useful contribution.

**Comment by nsoontie** [comment]
Thank you for the very useful software package!
