### ISSUE TITLE
Landmask of Antarctica is missing

### ISSUE THREAD

**Issue by KatrinMelanie** [OpenDrift/opendrift#1365]
Hi all,
I would like to simulate a plastic spillage in antarctica, but on all of the maps the landscape of antarctica is missing. 
Do you have an idea what the reason for that could be and how I can fix the issue?

![Figure_1](https://github.com/user-attachments/assets/11d97d9e-737f-4968-acc3-112b4b8b026e)

Thanks in advance.

**Comment by knutfrode** [comment]
Hi,

Oh yes, there seem to be an issue with the plotting here!
But the landmask is still used during simulations, and it will also show if you plot with a raster landmask:
`o.plot(fast=True)` 
So perhaps you can do this as a temporary workaround, and I will look into the missing vector landmask later.

If your ocean model also have a landmask available, you can also use this one as demonstrated in this example:
`o.plot(background='land_binary_mask', hide_landmask=True)`
https://opendrift.github.io/gallery/example_model_landmask.html#sphx-glr-gallery-example-model-landmask-py

**Comment by KatrinMelanie** [comment]
Hi, 

thanks a lot for your answer. 

I figured out what the problem is: For the GSHHS data there are different levels. For the first level the landscape of the antarctica is not included. 

See here: 
L1: boundary between land and ocean, except Antarctica.
L2: boundary between lake and land.
L3: boundary between island-in-lake and lake.
L4: boundary between pond-in-island and island.
L5: boundary between Antarctica ice and ocean.
L6: boundary between Antarctica grounding-line and ocean.

**Comment by knutfrode** [comment]
You are right, thank you!
I will add a fix for this probably next week.

**Comment by knutfrode** [comment]
I made now this small fix, by including `land=[1,5,6]` to GSHHFeature
https://github.com/OpenDrift/opendrift/pull/1372/files
Hopefully this is a complete solution.

**Comment by knutfrode** [comment]
Closing, please re-open if still an issue.
