### ISSUE TITLE
Wave input 

### ISSUE THREAD

**Issue by mmm197** [OpenDrift/opendrift#1375]
Dear developers,

I have an issue when I put the result from SWAN to Opendrift, and I don't know much about Python. From my point of view, I need to add a new Readers for SWAN output. 

Could you please tell me how to use the wave results from SWAN as the input for the plastic module?

Thanks in advance.

**Comment by knutfrode** [comment]
Hi,

If the SWAN output is available as CF-compliant netCDF-files (hopefully the case), you can use the existing reader_netCDF_CF_generic to add the data.
You could then also simply do:
`o.add_readers_from_list([<SWAN-files.nc>])`

**Comment by mmm197** [comment]
Thank you so much!
I tried it, and it worked.
