### ISSUE TITLE
Error when running SedimentDrift simulation with constant ocean vertical diffusivity.

### ISSUE THREAD

**Issue by LanaLubecke** [OpenDrift/opendrift#1392]
This should be a quick fix:

Instead of 
`'ocean_vertical_diffusivity': {'fallback': 0.02},`

write

`'ocean_vertical_diffusivity': {'fallback': 0.02, 'profiles': True},`

**Comment by knutfrode** [comment]
Yes, this was a rather serious bug for the SedimentDrift module.
Thank you for the fix!
