### ISSUE TITLE
deactivating initial spill spreading (Fay spreading)

### ISSUE THREAD

**Issue by augustosepp** [OpenDrift/opendrift#1405]
Morning all,

I'm conducting an OpenOil validation exercise comparing simulated spill shapes and positions with satellite-derived observations. The model performance is satisfactory when reproducing the evolution of new, point-source spills. However, when trying to simulate the development of aged spills, i.e., hours-long well-developed spills observed by satellites and seeded using shp files, the model performance decreases significantly, often underperforming "persistence" (i.e. the assumption that the latest oil spill observation is the most accurate estimate of spill future states). 

After going through my results and trying several alternative model configurations, I start to think that the initial spill spreading process, Fay or Fay equivalent, is playing a major role in decreasing the forecast skills and, if possible, I would like to deactivate it. 

According to Lehr et al., (2002), NOAA ADIOS-2 oil spill model includes a Fay-equivalent spreading process, however I could not track the process in the OpenOil code. I am new in OpenDrift and I may have missed the point here. After such a long intro, my questions are: how is the initial spill spreading treated in OpenOil (assuming it does exist and I've been unable to find it) and how could I switch it off?

Many thanks in advance for the support! all the best,
augusto sepp

**Comment by knutfrode** [comment]
Hi Augusto,
This is an interesting validation exercise.

In fact, initial spreading (e.g. Fay) was never implemented in OpenDrift.
I had planned to, but in the meantime we had several validation campaigns where we found (like you) that the drift actually validated very well without this type of spreading.
```
Brekke, C., Espeseth, M. M., Dagestad, K.-F., Röhrs, J., Hole, L. R., & Reigber, A. (2021). Integrated analysis of multisensor datasets and oil drift simulations—a free-floating oil experiment in the open ocean. Journal of Geophysical Research: Oceans, 126, e2020JC016499. https://doi.org/10.1029/2020JC016499
Röhrs, J., Dagestad, K.-F., Asbjørnsen, H., Nordam, T., Skancke, J., Jones, C. E., and Brekke, C.: The effect of vertical mixing on the horizontal drift of oil spills, Ocean Sci., 14, 1581-1601, https://doi.org/10.5194/os-14-1581-2018, 2018.
Jones, C.E., Dagestad, K.-F., Breivik, Ø., Holt, B., Röhrs, J., Christensen, K.H., Espeseth, M.M., Brekke, C., Skrunes, S. (2016): Measurement and modeling of oil slick transport. Journal of Geophysical Research – Oceans, Volume 121, Issue 10, October 2016, Pages 7759–7775. http://doi.org/10.1002/2016JC012113
```
My interpretation is that this spreading is rather insignificant compared to the other drift mechanisms, including diffusivity/uncertainty in particular.
In OpenOil there is by default some uncertainty added to the wind and currents (can be modified with `set_config`), which has the same effect as diffusivity - i.e. horizontal spreading
https://github.com/OpenDrift/opendrift/blob/master/opendrift/models/openoil/openoil.py#L487

**Comment by augustosepp** [comment]
Super thanks, Knut! All clear now.
