### ISSUE TITLE
error in fvcom

### ISSUE THREAD

**Issue by MCodeHmakerG** [OpenDrift/opendrift#1410]
FVCOM Fatal Error!
 GET_FILE_TIME: COULD NOT TRANSLATE TIME STRING
 FILE RETURNED: 
 Stopping FVCOM

%%
 =END  FILE IO TIME TYPE ====
 ===== FILE IO TIME INFO ====
 =    TMTYPE  :: CHARACTER STRING DATE
 !========PREV IO==========
 !    Day #    :                     0
 ! MicroSecond #:                     0
 ! (Date Time=1858-11-17T00:00:00.000000Z)
 !==========================
 !========NEXT IO==========
 !    Day #    :                     0
 ! MicroSecond #:                     0
 ! (Date Time=1858-11-17T00:00:00.000000Z)
 !==========================
 !========IO INTERVAL==========
 !    Day #    :                     0
 ! MicroSecond #:                     0
 ! (Human Time=d 0000000::h00:m00:s0.000000)
 !==========================
 =STK_LEN     ::           1
 =PREV_STKCNT ::           0
 =NEXT_STKCNT ::           0
 =MAX_STKCNT  ::           0
 =PREV_WGHT   ::  0.000000000000000E+000
 =NEXT_WGHT   ::  0.000000000000000E+000
 =TIMEZONE    ::UTC
 =END  FILE IO TIME TYPE ====
 =NEXT_WGHT   ::  0.000000000000000E+000
 =TIMEZONE    ::UTC
 =END  FILE IO TIME TYPE ====
 %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
 FVCOM Fatal Error!
 GET_FILE_TIME: COULD NOT TRANSLATE TIME STRING
 FILE RETURNED: 
 Stopping FVCOM
 %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
Abort(-1) on node 1 (rank 1 in comm 0): application called MPI_Abort(MPI_COMM_WORLD, -1) - process 1
[cli_1]: readline failed
Abort(-1) on node 2 (rank 2 in comm 0): application called MPI_Abort(MPI_COMM_WORLD, -1) - process 2
Abort(-1) on node 0 (rank 0 in comm 0): application called MPI_Abort(MPI_COMM_WORLD, -1) - process 0
forrtl: error (78): process killed (SIGTERM)

Stack trace terminated abnormally.
forrtl: error (78): process killed (SIGTERM)
Image              PC                Routine            Line        Source             
fvcom              0000000000A81104  Unknown               Unknown  Unknown
%%

What happened? I add the ts_init_file to my fvcom model,and the problem is happening,help me,thanks!

**Comment by knutfrode** [comment]
This does not seem to be related to OpenDrift.
