### ISSUE TITLE
performance_test.py: VariableNotCoveredError: Variable not available: sea_surface_elevation

### ISSUE THREAD

**Issue by lencart** [OpenDrift/opendrift#1424]
The test `performance_test.py` requests the variable `sea_surface_elevation` from `reader_netCDF_CF_generic.get_variables()`.

This variable is mapped to `sea_surface_height` inside `basemodel.__init__()` using the global dictionary `variable_aliases` (line 80 of `readers/basereader/__init__.py`).

Suggested quick fix:
In line 71 of `tests/benchmarks/performance_test.py`, request `sea_surface_height` instead of `sea_surface_elevation`.

**Comment by knutfrode** [comment]
I now updated this, and also updated the numbers in the test, as it was very old (dating back to Python 2.7.....)
https://github.com/OpenDrift/opendrift/commit/b3f5c78593b1f232a5e078799119c63c5275dcc1
