### ISSUE TITLE
Error when reading multiple files...

### ISSUE THREAD

**Issue by ocgabs** [OpenDrift/opendrift#1432]
Hi,
I am using the generic netcdf reader with BRAN2020 files. After modifying some variable and dimensions names my particles run happily when I use a single file, but when I try to do longer runs using multiple files, with the following line... The start and end time of the reader is correctly printed, but then I get the error below... 

I will very much appreciate any help.

Thanks,
Gaby

reader_curr_BRAN_u = reader_netCDF_CF_generic.Reader((BRAN_path+'surf_ocean_u_2023_ * _opendrift.nc'))
reader_curr_BRAN_v = reader_netCDF_CF_generic.Reader((BRAN_path+'surf_ocean_v_2023_ * _opendrift.nc'))

opendrift/lib/python3.11/site-packages/dask/array/core.py", line 1564, in __len__
    raise ValueError(msg)
ValueError: Cannot call len() on object with unknown chunk size.

A possible solution: https://docs.dask.org/en/latest/array-chunks.html#unknown-chunks
Summary: to compute chunks sizes, use

   x.compute_chunk_sizes()  # for Dask Array `x`
   ddf.to_dask_array(lengths=True)  # for Dask DataFrame `ddf`

 File "/home/561/ca5240/opendrift/opendrift/models/basemodel/__init__.py", line 2100, in run
    raise ValueError('Simulation stopped within '
ValueError: Simulation stopped within first timestep. "Missing variables: ['x_sea_water_velocity']", 'The simulation stopped before requested end time was reached.'

**Comment by knutfrode** [comment]
Hi,

Vector components must be in the same file/reader. But this should be possible to achieve by creating and merging datasets with Xarray, and then create an OpenDrift reader from this merged dataset.

**Comment by knutfrode** [comment]
Closing, please re-open if still relevant.
