### ISSUE TITLE
Problem reading variables in a netcdf in latest v. opendrift

### ISSUE THREAD

**Issue by MarianoTonini** [OpenDrift/opendrift#1458]
Hi all, 
                         I recently installed opendrift (version 1.12.0) with miniconda3 and mamba on Ubuntu-Linux. Everything seems to work correctly, even the included examples, they read and work perfect. 
But when using Croco-Roms own files the particles do not move from the initial position and the fields have zero value. 
I made several attempts with other CROCO files and also with data from the Glorys global model and I still have the same problem. The error seems to be in the reader.  But I can't figure out how to fix it. 

I attach one of the outputs to check the values. 

I appreciate any help! 

Mariano.
[output_opendrift_02.txt](https://github.com/user-attachments/files/18130336/output_opendrift_02.txt)

**Comment by AndresSepulveda** [comment]
Just to add information, all works well (same input file) in my system with an older version of OpenDrift

>> OpenDrift version 1.7.3
>> Platform: Linux, 4.19.0-26-amd64
>> 125.79486846923828 GB memory
>> 56 processors ()
>> NumPy version 1.26.4
>> SciPy version 1.7.0
>> Matplotlib version 3.4.1
>> NetCDF4 version 1.5.6
>> Xarray version 2024.2.0
>> OilLibrary version 1.1.3
>> Python version 3.9.2 | packaged by conda-forge | (default, Feb 21
>>
>> 2021, 05:02:46) [GCC 9.3.0]

In my case the input file is read correctly 

x_sea_water_velocity: -0.0428189 (min) -0.0322442 (max)
y_sea_water_velocity: -0.0390062 (min) -0.00149806 (max)

in the newer version the velocities are all 0.

x_sea_water_velocity: 0 (min) 0 (max)
y_sea_water_velocity: 0 (min) 0 (max)

Andrés

**Comment by knutfrode** [comment]
Could any of you provide a small sample Croco-file so that I can debug?
Ideally from a recent version of Croco, and smaller than 0.5 MB, e.g. with two timesteps and small area. Then we could include it in the test-folder of the repository.

**Comment by MarianoTonini** [comment]
Hi Knotfrode, my apologies for the delay. Attached is a small sample of the file I used. Kindly, Andrés helped me by testing the same file, and it works in his machine. I think the problem could be related to the reader, specifically with the lat/lon location of the variables. It seems like the velocities are not being read in the same area.
Thanks a lot for the help!

Best,
Mariano.

[nest_avg_drift02_zoom.nc.zip](https://github.com/user-attachments/files/18186993/nest_avg_drift02_zoom.nc.zip)

**Comment by knutfrode** [comment]
Hi,
The problem is that ROMS-croco files are not CF-compatible. There was a hack to deal with this, but had been deactivated in the meantime. I have now updated and reactivated this, so that this sample file is readable with the ROMS reader.
https://github.com/OpenDrift/opendrift/commit/089d28d1c0b93a1c0b088884856244b185da1474

However, it would be preferred if the ROMS/Croco files were CF-compatible in the first place, then such hardcoded hacks would not be necessary. There would in fact not be a need for a specific ROMS reader at all.

**Comment by knutfrode** [comment]
It is probably better to update with `git pull` than inserting those lines manually, as other things might also have changed in the meantime.
From the sample file above it seems that time variable (for e.g. currents etc) is `time` and not `scrum_time`. Anyway, these seem to be identical. I get the following output from readerinfo. Do you get the same?


```
$ readerinfo nest_avg_drift02_zoom.nc
===========================
Reader: roms native
Projection: 
  None
Coverage: [pixels]
  xmin: 0.000000   xmax: 10.000000   step: 1   numx: 11
  ymin: 0.000000   ymax: 20.000000   step: 1   numy: 21
  Corners (lon, lat):
    (-64.72, -42.62)  (-64.55, -42.62)
    (-64.72, -42.86)  (-64.55, -42.86)
Vertical levels [m]: 
  Not specified
Available time range:
  start: 2004-10-16 12:00:00   end: 2004-10-18 12:00:00   step: 1 day, 0:00:00
    3 times (0 missing)
Variables:
  upward_sea_water_velocity
  x_sea_water_velocity
  y_sea_water_velocity
  sea_surface_height
  sea_water_temperature
  sea_water_salinity
  sea_floor_depth_below_sea_level
  land_binary_mask
  sea_water_speed - derived from ['x_sea_water_velocity', 'y_sea_water_velocity']
===========================

```

**Comment by MarianoTonini** [comment]
The readerinfo output is the same as you shown. 
I update the code with 'get pull' but the answer is the same. 
The debug log in each step show that the values of the velocity are zero,

18:22:04 DEBUG   opendrift.models.basemodel.environment:903: ------------ SUMMARY -------------
18:22:04 DEBUG   opendrift.models.basemodel.environment:905:     x_sea_water_velocity: 0 (min) 0 (max)
18:22:04 DEBUG   opendrift.models.basemodel.environment:905:     y_sea_water_velocity: 0 (min) 0 (max)
18:22:04 DEBUG   opendrift.models.basemodel.environment:905:     sea_surface_height: 0 (min) 0 (max)
18:22:04 DEBUG   opendrift.models.basemodel.environment:905:     x_wind: 0 (min) 0 (max)
18:22:04 DEBUG   opendrift.models.basemodel.environment:905:     y_wind: 0 (min) 0 (max)
18:22:04 DEBUG   opendrift.models.basemodel.environment:905:     upward_sea_water_velocity: 0 (min) 0 (max)
18:22:04 DEBUG   opendrift.models.basemodel.environment:905:     ocean_vertical_diffusivity: 0 (min) 0 (max)
18:22:04 DEBUG   opendrift.models.basemodel.environment:905:     sea_surface_wave_significant_height: 0 (min) 0 (max)
18:22:04 DEBUG   opendrift.models.basemodel.environment:905:     sea_surface_wave_stokes_drift_x_velocity: 0 (min) 0 (max)
18:22:04 DEBUG   opendrift.models.basemodel.environment:905:     sea_surface_wave_stokes_drift_y_velocity: 0 (min) 0 (max)
18:22:04 DEBUG   opendrift.models.basemodel.environment:905:

**Comment by knutfrode** [comment]
Ok, and the particles are seeded within the spatial and temporal coverage of the reader?
The full log should tell you why currents are zero.

**Comment by MarianoTonini** [comment]
Hi, 
The particles are seeded taking into account both spatial and temporal coverage.
The error in the debug log seems to be related to the 'hc' variable, but I'm not sure if this is the cause of the issue with reading the currents.
Attached is the file containing the reader info and the debug log.
Thank you very much for your help; I truly appreciate your support.

[croco_drift_test_info_debug_log.txt](https://github.com/user-attachments/files/18212450/croco_drift_test_info_debug_log.txt)

**Comment by MarianoTonini** [comment]
I think I found the cause of not reading, I incorporated to the croco files the s_rho and hc variables that were missing to read the depth sigma layers. 
With that I managed to make the particles move. 

Thanks for all the help,
