### ISSUE TITLE
Can't save in netCDF

### ISSUE THREAD

**Issue by hidden-ja** [OpenDrift/opendrift#168]
Hi everyone,

I try to save my simulation in netcdf file with this code" o.run (outfile='final.nc')", but  it generates this error:

21:13:35 DEBUG: Fetching variables from global_landmask
21:13:35 DEBUG: Fetched env-before
21:13:35 DEBUG: No time interpolation needed - right on time.
21:13:35 DEBUG: Obtained data for all elements.
21:13:35 DEBUG: ---------------------------------------
21:13:35 DEBUG: Finished processing all variable groups
21:13:35 DEBUG: ------------ SUMMARY -------------
21:13:35 DEBUG:     land_binary_mask: 0 (min) 0 (max)
21:13:35 DEBUG: ---------------------------------
21:13:35 DEBUG: 		12 active elements
21:13:35 DEBUG: 		-46.28812408447266 <- latitude  -> -43.87070658044315
21:13:35 DEBUG: 		-74.67529466890058 <- longitude -> -72.57157135009766
21:13:35 DEBUG: 		z = 0.0
21:13:35 DEBUG: ---------------------------------
21:13:35 DEBUG: Writing and closing output file: final.nc
21:13:35 INFO: Wrote 10 steps to file final.nc
21:13:35 DEBUG: Making netCDF file CDM compliant with fixed dimensions
21:13:35 DEBUG: Importing from final.nc
21:13:35 DEBUG: Removed 528 elements.
21:13:35 DEBUG: Setting imported config: general:use_auto_landmask -> True
21:13:35 DEBUG: Setting imported config: general:auto_landmask_resolution -> h
21:13:35 DEBUG: Setting imported config: general:coastline_action -> stranding
21:13:35 WARNING: Could not set config: general:time_step_minutes -> 60
21:13:35 WARNING: Could not set config: general:time_step_output_minutes -> None
21:13:35 WARNING: Could not set config: seed:ocean_only -> True
21:13:35 WARNING: Could not set config: drift:max_age_seconds -> None
21:13:35 WARNING: Could not set config: drift:scheme -> euler
21:13:35 WARNING: Could not set config: drift:stokes_drift -> True
21:13:35 WARNING: Could not set config: drift:current_uncertainty -> 0.0
21:13:35 WARNING: Could not set config: drift:current_uncertainty_uniform -> 0.0
21:13:35 WARNING: Could not set config: drift:wind_uncertainty -> 0.0
21:13:35 WARNING: Could not set config: drift:relative_wind -> False
21:13:35 WARNING: Could not set config: drift:lift_to_seafloor -> True
21:13:35 WARNING: Could not set config: drift:truncate_ocean_model_below_m -> None
21:13:35 WARNING: Could not set config: drift:deactivate_north_of -> None
21:13:35 WARNING: Could not set config: drift:deactivate_south_of -> None
21:13:35 WARNING: Could not set config: drift:deactivate_east_of -> None
21:13:35 WARNING: Could not set config: drift:deactivate_west_of -> None
21:13:35 WARNING: Could not set config: drift:use_tabularised_stokes_drift -> False
21:13:35 WARNING: Could not set config: drift:tabularised_stokes_drift_fetch -> 25000

Can you think of any solution? or how to fix this problem?

**Comment by knutfrode** [comment]
Hi, there is no error here, just some warnings which arise when importing config-settings from the saved netCDF file.

These warnings are not severe, however they are now removed in the latest version.
