### ISSUE TITLE
reader for atmo model like WRF but using lon/lat 2d variables at native latlong proj

### ISSUE THREAD

**Issue by ivicajan** [OpenDrift/opendrift#170]
Dear developers,
before starting I would like to know if already somebody already did it. 

I am looking for reader capable of reading netCDF atmo model output with winds (like WRF for example). Variable names of wind components U10/V10 or Uwind/Vwind doesn't actually matter as we can put them into mapping variables for x_winds/y_winds. However, longitude/latitude or LON/LAT are 2d fields and there is no info on projection type, guess they are on native latlong. There is no need for rotation or some fancy transformation.

Thanks in advance,
Ivica

p.s. I tried with generic, added standard_name attribute to longitude/latitude but not working

**Comment by knutfrode** [comment]
Hi,

2D grids of longitude/latitude should be sufficient for the generic netCDF reader, as long as your version of OpenDrift is not more than ~one year old.

If you could make available a small subset of such a file, I can have a look at it.

**Comment by joeelrahi** [comment]
Hello,

I have encountered the same problem while trying to read bathymetry data (from GEBCO), which is provided in netCDF--LON/LAT in 2D. My OpenDrift version was less than a year old, but still, the generic reader couldn't extract the data.

It turned out that the problem is not with the GenericReader but with the NetCDF Conventions used in the dataset I was using. 

Solution: Create your own input file that is written according to netCDF Conventions (https://www.unidata.ucar.edu/software/netcdf/conventions.html)

If you think this might be helpful I can share with you the python script that does the conversion :)

kind regards,
Joe

**Comment by knutfrode** [comment]
Yes, this reader is supposed to comply with the netCDF CF convention. However, it is challenging to make code which can handle all possible datasets that satisfy the CF convention, as this is rather "wide". So there might still be CF-compliant datasets which the reader does not handle.

For coordinate variables, the ideal (fastest and most accurate) is to have X, Y and a coordinate definition (proj4). If not found, the reader looks for longitude/latitude. If these are 1D arrays, projection is assumed to be 'latlon'. If these are 2D arrays, a 2D-interpolator is instead made to convert between indices and lon/lat. Accuracy is still very good, but somewhat slower than using analytical projection calculations, at least for large domains (many pixels).

You may see the present logic for parsing the coordinate variables here:
https://github.com/OpenDrift/opendrift/blob/master/opendrift/readers/reader_netCDF_CF_generic.py#L161
https://github.com/OpenDrift/opendrift/blob/master/opendrift/readers/reader_netCDF_CF_generic.py#L298

The parsing of general variables is solely based on the presence of CF attribute ```standard_name```

**Comment by ivicajan** [comment]
Thanks for your response!

I am using the latest version from github, so it is not the issue of
version. Unfortunately, there is no way of getting X or Y projected
variables as I do not have info for that.
On my server I can rename variables on the fly using ncml (opendap) so can
make any variable name/attr combination (if I know the desired combination).

Attached is small chunk (of 3 time steps) with post-processed variables. As
I wrote I can make any combination, just let me know which one works ;)
(and should be lon/lat coordinates).

Thanks once again!

Regards,
Ivica

**Comment by knutfrode** [comment]
Did you forget the attachment?

**Comment by ivicajan** [comment]
Nope, guess it was rejected on github. I could send it privately on your email?

Sent from my mobile, possible typos

________________________________

**Comment by knutfrode** [comment]
Yes, you can send to knutfd@met.no

**Comment by knutfrode** [comment]
There was a couple of lines in the reader which I believe was obsolete, and which are now removed.
So please update your code, and try again.

The file is readable for me now, however the current components are not detected since they do not have ```standard_name``` attribute.

**Comment by ivicajan** [comment]
Thanks!

I just git pull the latest version and I can confirm I can now load the
file and get coordinates in lon/lat.
However, can't get x_wind and y_wind even I ncrename variables into
x_wind/y_wind.
Is there something else I need to change to be able to load winds?

Thanks

Ivica

**Comment by ivicajan** [comment]
aghhh my bad, forgot to add standard_name
