### ISSUE TITLE
New installation of

### ISSUE THREAD

**Issue by AndresSepulveda** [OpenDrift/opendrift#180]

**Comment by AndresSepulveda** [comment]
Hi, I just installed the latest version of Opendrift

Software and hardware:
  OpenDrift version 1.1.1
  unknown GB memory
  56 processors ()
  NumPy version 1.17.3
  SciPy version 1.3.2
  Matplotlib version 2.2.4
  NetCDF4 version 1.4.2
  Python version 3.7.3 | packaged by conda-forge | (default, Mar 27 2019, 23:01:00) [GCC 7.3.0]

and I have some problems with the examples, for example with loading reader_basemap_landmask

    from opendrift.readers import reader_basemap_landmask
ImportError: cannot import name 'reader_basemap_landmask' from 'opendrift.readers' (/home/matlab/opendrift/opendrift/readers/__init__.py)

o also with some of the standard examples:

python example_long_shipdrift.py

nd_frequency_moment: 0.000000
14:58:29 INFO: Adding a dynamical landmask with max. priority based on assumed maximum speed of 2 m/s. Adding a customised landmask may be faster...
Traceback (most recent call last):
  File "example_long_shipdrift.py", line 36, in <module>
    o.run(steps=24, stop_on_error=True)
  File "/home/matlab/opendrift/opendrift/models/basemodel.py", line 2069, in run
    from opendrift.readers import reader_global_landmask
  File "/home/matlab/opendrift/opendrift/readers/reader_global_landmask.py", line 18, in <module>
    from opendrift_landmask_data import Landmask
  File "/home/matlab/miniconda3/envs/opendrift/lib/python3.7/site-packages/opendrift_landmask_data-0.1-py3.7.egg/opendrift_landmask_data/__init__.py", line 2, in <module>
  File "/home/matlab/miniconda3/envs/opendrift/lib/python3.7/site-packages/opendrift_landmask_data-0.1-py3.7.egg/opendrift_landmask_data/mask.py", line 6, in <module>
  File "/home/matlab/miniconda3/envs/opendrift/lib/python3.7/site-packages/rasterio/__init__.py", line 22, in <module>
    from rasterio._base import gdal_version
ImportError: libkea.so.1.4.7: cannot open shared object file: No such file or directory


Any idea of what is missing?

**Comment by gauteh** [comment]
Hi, we have recently removed the basemap reader as we are moving to Python 3 only and Cartopy. Where does the first error occur? There should not be any references to basemap left? Make sure you upgrade the examples as well. The latter error looks like there is something wrong with the installation of gdal or with the conda environment. Have you tried creating a fresh environment as per the instructions here: https://opendrift.github.io/install.html ?

**Comment by gauteh** [comment]
If you need basemap you can do:

```
pip install https://github.com/matplotlib/basemap/archive/a551c2361314670dc7d95143190d3d48ba750d20.zip
```

the examples in the latest release (if you follow the instructions) are not migrated to cartopy yet, and basemap could not be installed automatically for the conda package so the above command might be necessary still (from within the conda environment).

**Comment by knutfrode** [comment]
It seems like your conda environment is not up-to-date, as it uses netCDF 1.4.2 (which by the way has a severe performance bug).

I recommend to create a new environment by:
```
conda env remove -n opendrift
conda env create -f environment.yml
conda activate opendrift
```

**Comment by gauteh** [comment]
Closing, probably outdated conda environment.
