### ISSUE TITLE
Vertical migration in sigma models?

### ISSUE THREAD

**Issue by AndresSepulveda** [OpenDrift/opendrift#204]
Hi,

I am looking at the pelagic egg code and it mentions that the option

self.environment_profiles['sigma'] 

is not yet implemented. What could be an option for a sigma-coordinate model? Bypass
lavae buoyancy and only consider vertical movement due to water w-component+larvae's vertical velocity? 

Any experience in this is well appreciated.

Andres

**Comment by joeelrahi** [comment]
Hello Andres,

I have developed my own model (based on Opendrift) which included stage growth and vertical migration. I enforced vertical migration using vertical velocity (Vz), and the trigger is naturally sunrise and sunset ( If that's your case I advise you to use pyephem astronomic package).


Regarding the sigma-coordinate system, if the regular drift model runs then I think the same approach I used is viable. Perhaps you don't have to bypass the larvae buoyancy, just use a factored vertical swimming velocity that takes buoyancy into account. 

Hope I can help you better as I worked intensely on this topic, so please write me if you have other questions.

regards,
Joe

**Comment by knutfrode** [comment]
I believe that is a very old comment, and I cannot remember it. 
```environment_profiles```are only available as function of ```z```, however, this should not be a problem, as sigma-coordinates of e.g. ROMS native files are converted to z-coordinates by the ROMS native reader.

**Comment by knutfrode** [comment]
As we discussed before, @joeelrahi , it would be nice to include your model in the repository in the future, as the present pelagicegg is just a very basic demo model, and not really useful for serious studies.

**Comment by joeelrahi** [comment]
I'm looking forward to share my model and contribute to the wiki, perhaps by adding a section about Individual-Based Modelling and modelling biological growth wrt environmental cues.

My paper is currently under review and there might be few additional tweaks to the model, as soon as it gets published I will share my work.

**Comment by gauteh** [comment]
Close, re-open if needed.
