### ISSUE TITLE
miniconda path problem

### ISSUE THREAD

**Issue by AndresSepulveda** [OpenDrift/opendrift#214]
Hi, I am having problems using opendrift in a new machine. I installed everything using miniconda

$ conda config --add channels conda-forge  # recommended, but not necessary
$ conda create -n opendrift python=3
$ conda activate opendrift
$ conda install -c opendrift -c conda-forge -c noaa-orr-erd opendrift

and added

export PYTHONPATH=/home/chonos/miniconda3/pkgs/opendrift-1.2.0-py_0/site-packages/opendrift

to .bashrc

so, after doing

conda activate opendrit

I try to run a script and I get

ModuleNotFoundError: No module named 'opendrift'

What is the correct way to add the package installed via miniconda?

Thanks,

Andres

**Comment by gauteh** [comment]
You should not add the installed path to your PYTHONPATH. It should be
available in the activated environment. Make sure the python interpreter
launched is the one from your conda environment.

tor. 16. jan. 2020, 17:32 skrev Andres Sepulveda <notifications@github.com>:

**Comment by gauteh** [comment]
Closing, need more information.
