### ISSUE TITLE
Basemodel:  invalid value encountered in sqrt

### ISSUE THREAD

**Issue by Caffa** [OpenDrift/opendrift#233]
WARNING:py.warnings:/Users/caffae/anaconda3/envs/opendrift/lib/python3.8/site-packages/opendrift/models/basemodel.py:3288: RuntimeWarning: invalid value encountered in sqrt
  scalar = np.sqrt(u_component**2 + v_component**2)

I've been trying to run an opendrift simulation with a timeinterval of 5 mins which resulted in this error.

**Comment by knutfrode** [comment]
This error occurs in the plotting method. Did the simulation succeed before that?
Can you make plot/animation without using the ```background``` keyword?
