### ISSUE TITLE
Stop when all elements have been deactivated?

### ISSUE THREAD

**Issue by AndresSepulveda** [OpenDrift/opendrift#256]
Hi,

I am running a simulation were all particles are released at the beginning. It is possible to set it to stop when all elements have been deactivated?

**Comment by knutfrode** [comment]
Hi,

A simulation will always stop when all elements have been activated, even if the simulation duration is set to a longer period.

**Comment by AndresSepulveda** [comment]
it seems the particles that reach the boundary of the domain (and are stuck there) are still considered as active. The ones that reach the coast are set as stranded as per

o.set_config('general:coastline_action', 'stranding')

Is there a similar line for the open boundaries?

**Comment by knutfrode** [comment]
This probably means that you have ```fallback_values``` for current and other parameters (e.g. 0 current), so that these values are used instead of model data, when outside of the model domain.

To make the particles deactivate outside the reader domain, you may remove the fallback_values, by e.g. 
```
del o.fallback_values['x_sea_water_velocity']
```

**Comment by AndresSepulveda** [comment]
Great, that works. These show now as "missing_data".

**Comment by knutfrode** [comment]
Good
