### ISSUE TITLE
Plot from existing .nc file?

### ISSUE THREAD

**Issue by AndresSepulveda** [OpenDrift/opendrift#260]
Is it possible to reproduce the plot generated by  o.plot 

using an existing .nc file generated by a  o.run ?

**Comment by knutfrode** [comment]
Yes, you may re-import from file with:

```
>>> import opendrift
>>> o = opendrift.open(<filename>)
>>> o.plot(<...plot options...>)
```

This is also possible from commandline, with the various scripts:
https://github.com/OpenDrift/opendrift/tree/master/opendrift/scripts

e.g. 
```$ opendrift_plot.py <filename>```
