### ISSUE TITLE
Forcing input and grid info in different files 

### ISSUE THREAD

**Issue by vic1309** [OpenDrift/opendrift#261]
I have outputs of the Canadian Arctic Prediction System but the files do not contain the lat/lon values of the grid points. However, I have other file which contains such values. Is it possible to add the lat/lon file in Opendrift? Any other suggestions?

Thank you in advance!

**Comment by knutfrode** [comment]
Such a feature is implemented for the ROMS native reader, where one can provide the filename of a "gridfile" with coordinates:
https://github.com/OpenDrift/opendrift/blob/master/opendrift/readers/reader_ROMS_native.py#L35

No such general feature is implemented for the netCDF_CF-reader, as there is no standard way for a "gridfile" format. However, this may fairly easily be implemented ("hacked") by a user.

**Comment by vic1309** [comment]
Thank you, Knut!
