### ISSUE TITLE
o.run within a loop?

### ISSUE THREAD

**Issue by AndresSepulveda** [OpenDrift/opendrift#262]
Hi all,

I want to release particles from several locations, one at a time as my computer freezes if I try all of them at once, and the resulting file is too big.

For this I use a loop

```
for amers in range(1,lats.size):
  file_nc= "AMER_"+str(amers)+"_1p_loco.nc"
  for horas in range(1,total_steps):
     o.seed_elements(lons[amers], lats[amers], z=-20, radius=radii, number=particles,
                time=time+time_step*horas, diameter=0.0014,
                neutral_buoyancy_salinity=31.5,density=1035)

  o.run(steps=total_steps,time_step=3600,outfile=file_nc)

```

The first step works ok, but for the second step I get this error:

> Traceback (most recent call last):
>   File "ObyO_csv_loco_trond.py", line 65, in <module>
>     o.run(steps=total_steps,time_step=3600,outfile=file_nc)
>   File "/home/loco/opendrift_1p2/opendrift/models/basemodel.py", line 2302, in run
>     self.state_to_buffer()  # Append final status to buffer
>   File "/home/loco/opendrift_1p2/opendrift/models/basemodel.py", line 2425, in state_to_buffer
>     self.io_write_buffer()
>   File "/home/loco/opendrift_1p2/opendrift/export/io_netcdf.py", line 93, in write_buffer
>     var[:, self.steps_exported:self.steps_exported+num_steps_to_export] = \
>   File "netCDF4/_netCDF4.pyx", line 4950, in netCDF4._netCDF4.Variable.__setitem__
>   File "netCDF4/_netCDF4.pyx", line 5207, in netCDF4._netCDF4.Variable._put
> IndexError: size of data array does not conform to slice
 
It seems that there is a problem when writing the new NetCDF file.

Digging a bit further, the first NetCDF file created has 4319 particles released

> netcdf AMER_1_1p_loco {
> dimensions:
>         trajectory = 4319 ;
>         time = 4321 ;

while the second part has almost twice the number of trajectories.

> netcdf AMER_2_1p_loco {
> dimensions:
>         trajectory = 8364 ;
>         time = UNLIMITED ; // (0 currently)

So the question becomes, how do I reset the number of seeded elements in each loop. Is this correct?

Thanks,

Andres

**Comment by knutfrode** [comment]
You are here trying to run several repeated simulations with the same object (```o```).
This is not expected to work, but a proper error message is not yet implemented.

Instead, you should create a new object before each run: ```o = YourModel()```
Then you also need to add the same readers each time. However, the reader(s) may be created before the loop, and added several time within the loop.

Note that there is a method ```o.reset()``` which could instead be called once per loop. However, I am not sure if this is completely safe, so recommend the above solution.

**Comment by knutfrode** [comment]
Btw, if your output file gets to big, you could consider outputting at a coarser time step, by e.g. adding to run():  ```time_step_output = timedelta(hours=24)```

**Comment by AndresSepulveda** [comment]
Thank you. That is working. I haven't tried the `o.reset()` option yet.

**Comment by AndresSepulveda** [comment]
I had to add the `o.reset()` at the end of the loop, as it was getting slow and the run froze.

```
for amers in range(7,lats.size):
  o = PelagicEggDrift(loglevel=0)  # Set loglevel to 0 for debug information
  o.add_reader([reader_loco])
# If hitting the coast  -> strandend
  o.set_config('general:coastline_action', 'stranding')
# If leaving the domain -> missing_data
  del o.fallback_values['x_sea_water_velocity']
  file_nc= "AMER_"+str(amers)+"_1p_loco.nc"

  for horas in range(1,total_steps):
     o.seed_elements(lons[amers], lats[amers], z=-20, radius=radii, number=particles,
                time=time+time_step*horas, diameter=0.0014,
                neutral_buoyancy_salinity=31.5,density=1035)
  o.run(steps=total_steps,time_step=3600,time_step_output=timedelta(hours=24),outfile=file_nc)
  o.reset()
```

**Comment by knutfrode** [comment]
I would not think that ```o.reset()``` should make a difference in this case, as you now anyway create a new object at the beginning of each loop?

Btw, your seeding in a loop is perhaps quite slow? It would be faster if you use time as an array as input to a single seed-call. I am not 100% sure this works, as a new rewrite of the seed-method is planned soon.

**Comment by gauteh** [comment]
`o.reset()` might free up some memory, but maybe even better to just do `del o` when you do not need it anymore.
