### ISSUE TITLE
Oil Dispersion on OpenOil3D versus OpenOil

### ISSUE THREAD

**Issue by simonweppe** [OpenDrift/opendrift#263]
Hi Opendrift team,

I have a question about the oil dispersion process in the **OpenOil3D** module versus **OpenOil**. I read in **_Rhors et al., 2018_** that describes the **OpenOil3D** module that :

"Dispersion is not treated separately in OpenOil because it is explicitly calculated by the vertical mixing scheme in adjunction with wave breaking entrainment and droplet size distributions"

Does this means that when using **OpenOil3D**, one should switch off the dispersion process that is included in the **OpenOil** module i.e.
`o.set_config('processes:dispersion',  False)`

since it is handled explicitly in the module, by the sequence of wave entrainment, resurfacing, vertical mixing ? 

And in that case, the fraction of oil mass _dispersed_ at a given time could be obtained by the summing the mass of submerged oil at a given time ?

I see that `o.set_config('processes:dispersion',  False)` is used in some of the examples on oil spill, but not all.
 
Thanks

**Comment by knutfrode** [comment]
Traditionally in oil drift models, the smallest entrained droplets have been removed from the budget and tagged ```dispersed```. This means that that part of the oil is "lost", and will not resurface. It is not the same as ```dissolved```, although those small dropletes may eventually dissolve into molecoles, or be biodegraded.

So ```dispersed``` is slightly different from ```entrained / submerged``` oil droplets, as the latter may resurface sooner or later, more easily if radii are large or turbulence low (little wind).

The main problem with the ```dispersed``` category, is that the radius limit (typically set to 70 microns) is fairly arbitrary (these droplets could also resurface, given enough time, or simply being mixed upwards by turbulence).

With sufficient computer power and storage, we (@johannesro  and myself) therefore prefer to avoid the term ```dispersed```, by disabling it in oil drift simulations:
```o.set_config('processes:dispersion', False)```
This means that even the smallest droplets will be followed in 3D.
I have read a paper by Øystein Johansen (SINTEF) where he also discourages the use of the ```dispersion``` terminology, but I cannot remember which paper.

However, as some end users prefer to have this category in the budget for "historical reasons", the ```dispersion``` option is still available.
Its actual parameterization is borrowed (with reference) from the NOAA PyGNOME model:
https://github.com/OpenDrift/opendrift/blob/master/opendrift/models/openoil.py#L561

Note that ```dispersion```, like ```evaporation```, is implemented in OpenOil by removing a fraction of the oil mass from a given element ("superparticle"), and not by removing individual elements.

**Comment by simonweppe** [comment]
Thanks @knutfrode, really helpful and clear. 
I agree with the confusion that the term `dispersion` can bring in the literature.
