### ISSUE TITLE
question about install and running the example_leeway.py

### ISSUE THREAD

**Issue by limaolin1981611** [OpenDrift/opendrift#268]
I'm new about python and opendrift.
I have download the miniconda3, git, OpenDrift sourcecode and installed the OpenDrift according to Fresh development environment. I also have installed the pyCharm. But I found that I need to install some module that are not included in miniconda3. So I download the Anaconda3 and do the same thing as miniconda3 aboved. when I run the example_leeway.py, therr were some error as follows:
1.If I run the example_leeway.py in examples folder, there is "ModuleNotFoundError: No module named 'opendrift'". But if I copy the example_leeway.py to the upper folder, it's correct. I have add the opendrift to path.
2.If I run the  example_leeway.py in the upper folder, the error is "No module named 'opendrift_landmask_data'"
How can I soft the two errors above, thanks a lot.

**Comment by limaolin1981611** [comment]
I have solved the errors, thanks a lot

**Comment by knutfrode** [comment]
Ok, that's good to hear.
