### ISSUE TITLE
openoil 

### ISSUE THREAD

**Issue by dharanidharan12** [OpenDrift/opendrift#27]
I am changing viscosity and density in the model, but there are no changes taking place (Evaporation remains same)
how to change those values .... 
please help!!

Thanks in Advance!!!

**Comment by knutfrode** [comment]
The oil weathering in OpenOil is presently very basic, and based on tabulated values for each oil type (though there is wind-dependency). User-provided values of viscosity and density presently only affects the transport (through vertical mixing, so hence only for OpenOil3D).

I am working on an interface towards the NOAA oil library, for more direct physical calculations of evaporation and emusification. This will be available in OpenOil within a few months.
https://github.com/NOAA-ORR-ERD/OilLibrary

For more sophisticated oil weathering calculations, I recommend having a look at the NOAA PyGNOME drift and weathering model: https://github.com/NOAA-ORR-ERD/PyGnome

**Comment by dharanidharan12** [comment]
How to solve this kind of  **Tcl_AsyncDelete: cannot find async handler**
**Aborted (core dumped)**  ERROR..

I used to save image and video file , while saving both First Type Error occurs....

fpath1='/home/samplefolder/images/sample1.png'
fpath='/home/samplefolder/videos/sample2.mp4'
lw.plot(filename=fpath1)
lw.animation(filename=fpath)

ERROR 1:
**Segmentation fault (core dumped)**
========================================================
                         SECOND TYPE OF ERROR
========================================================

fpath1='/home/samplefolder/images/sample4.png'
fpath='/home/samplefolder/videos/sample3.mp4'
lw.plot(filename=fpath1)
lw.animation(filename=fpath)
INFO: Saving animation to /home/samplefolder/videos/sample3.mp4...
INFO: Deleting temporary figures...

**ERROR 2:**
**Tcl_AsyncDelete: cannot find async handler
Aborted (core dumped)**

Second type while saving the image and video I getting this kind of error..

How to solve this problem.
What I did Wrong Here!!!
Please Help!!
Thanks in Advance!!!

**Comment by knutfrode** [comment]
Apparently you are running OpenDrift in a batch script with no interactive display?
In that case you need to add these two lines at the very beginning of your script (before importing OpenDrift):
```
import matplotlib
matplotlib.use('Agg')
```

See here for more info:
http://matplotlib.org/faq/howto_faq.html#generate-images-without-having-a-window-appear

**Comment by dharanidharan12** [comment]
how to create the current and wind file for this 

> **llcrnrlon=80.206,  llcrnrlat=12.908, urcrnrlon=80.627, urcrnrlat=13.484**
latitudes and longitudes
Now I manually assign value as
lw.fallback_values['x_wind']
lw.fallback_values['y_wind']
lw.fallback_values['x_sea_water_velocity']
lw.fallback_values['y_sea_water_velocity']

How to create the exact file for netcdf reader. To make to leeway run with exact current and wind.

Thanks in Advance!!!

**Comment by knutfrode** [comment]
To obtain netCDF-files with winds and currents, you simply have to search
on the internet, or contact some groups running such models which would
cover your area and time of interest.

Knut-Frode

2016-10-26 13:32 GMT+02:00 Dharani_Dharan <notifications@github.com>:

**Comment by dharanidharan12** [comment]
How to work with reader_grib.py 
I found a line  **# Hardcoded "GRIB-tables" for now.**

So how to pass value dynamically...

Having grib file with current and wind speed .. 
Please HELP!!!!
Thanks in Advance!

**Comment by knutfrode** [comment]
If you can send me one example of such a GRIB-file (as small size as
possible), I can extract the GRIB-codes and update the reader.
Alternatively you can send me the output from "grib_ls <file>".
A dynamical solution will be made later.

2016-11-04 5:51 GMT+01:00 Dharani_Dharan <notifications@github.com>:

**Comment by dharanidharan12** [comment]
Added files for input 
[gribfiles.zip](https://github.com/knutfrode/opendrift/files/571018/gribfiles.zip)

**Comment by knutfrode** [comment]
I added now GRIB codes for KWBC so that this file is readable by OpenDrift. Please update your code with "git pull".
The resolution is however very coarse, so not sure it is very useful for trajectory calculations.
You can plot coverage from command line with ```readerinfo.py RTOFS-ATL20161030060901305.grb -p y_sea_water_velocity``` (if you have set PATH correctly to folder ~/opendrift/opendrift/scripts/)

**Comment by knutfrode** [comment]
I added now GRIB codes for KWBC so that this file is readable by OpenDrift. Please update your code with "git pull".
The resolution is however very coarse, so not sure it is very useful for trajectory calculations.
You can plot coverage from command line with ```readerinfo.py RTOFS-ATL20161030060901305.grb -p y_sea_water_velocity``` (if you have set PATH correctly to folder ~/opendrift/opendrift/scripts/)

**Comment by dharanidharan12** [comment]
How to make wind data file can be readable through reader_grib.py
[gfs20161104050500804.grb.zip](https://github.com/knutfrode/opendrift/files/573075/gfs20161104050500804.grb.zip)

**now i tried to call the file using reader.grib.py -- it shows error like 
    self.times = [times[k] for k in self.indices[var]]
UnboundLocalError: local variable 'var' referenced before assignment**

but its working fine while using the current data file  alone.

Please Help!!!
Thanks in Advance!

**Comment by knutfrode** [comment]
I updated now the GRIB reader to also identify wind data from KWBS. Please update your code and try again.

**Comment by dharanidharan12** [comment]
Thanks !!!  
It's working now.
I did the same change in code on **previous update.**  But it Didn't take effect WHY?.  What I did wrong in previous update...

**Comment by knutfrode** [comment]
It is important that OpenDrift is installed with "python setup.py develop
--user"
and not with "python setup.py install", because you then need to re-install
every time the code is updated.

2016-11-07 13:14 GMT+01:00 Dharani_Dharan <notifications@github.com>:

**Comment by dharanidharan12** [comment]
no appearance of spill object..
What I am missing here,  Having doubt in the spill points(lon=281.826; lat=12.755;)
Whether the points I mention is right or not?

reader_basemap = reader_basemap_landmask.Reader(llcrnrlon=260.006, llcrnrlat=10.001, urcrnrlon=300.000, urcrnrlat=30.484, resolution='h', projection='merc')

lon=281.826; lat=12.755;

Basemap is created successfully, but spill object is not visible..

Please Help!!!
Thanks in Advance!

**Comment by knutfrode** [comment]
Try with negative longitudes, e.g. -78.174 instead of 281.826. That works for me.
Also, on this large scale, intermediate resolution basemap ('i' instead of 'h') is probably sufficient, and is much faster to generate.

**Comment by dharanidharan12** [comment]
[us.zip](https://github.com/knutfrode/opendrift/files/594581/us.zip)
for me its not taking effect.
My py file
[USn.py.zip](https://github.com/knutfrode/opendrift/files/594599/USn.py.zip)

**Comment by knutfrode** [comment]
You must use negative longitudes also for generation of the Basemap, not only when seeding.

**Comment by dharanidharan12** [comment]
It's working for OpenOil
But no changes while using  in leeway..
I changed the basemap latitude and longitude as negative points only, 
But there is no point of spill is seen.

**Comment by dharanidharan12** [comment]
sorry It's my mistake
Sorry for Troubling you.
I changed in one file and runs some other file.  
It's working fine only.
Thank you!!
Sorry for the Trouble..

**Comment by dharanidharan12** [comment]
1. How to get the final spill latitude and longitude position.

2. How to get all points during model run (Each and Every position based on time interval).

Thanks in Advance!!!

**Comment by knutfrode** [comment]
The final position of the elements is available after the run as arrays ```o.elements.lon``` and ```o.elements.lat```
The full history of positions and other properties is available in the 3D-array ```o.history```
This is also explained in the documentation: https://github.com/OpenDrift/opendrift/wiki/How-to-run-a-trajectory-simulation#5-running-the-model

**Comment by dharanidharan12** [comment]
how to add multiple objects in leeway.
for example:
 1. Person
 2. Ship/Boat
In single run how to define multiple objects 
Thanks in Advance!!!

**Comment by johannesro** [comment]
If the objects belong to the same drift simulation class, you can simply
call the seed function several times but with different properties.

If the objects belong to different simulation classes, this will not be
possible and you have to repeat you simulation with different classes.

Johannes Röhrs, PhD
Norwegian Meteorological Institute
www.met.no / www.yr.no

johannes.rohrs@met.no
+47 41654886

**Comment by dharanidharan12** [comment]
During model run, how to add current value manually using leeway.

Thanks in Advance!

**Comment by dharanidharan12** [comment]
how to pass minimum and maximum value using 

lw.fallback_values['x_sea_water_velocity'] = -0.083
lw.fallback_values['y_sea_water_velocity'] = -0.092

**Tired to pass as list** 
Have to give both minimum and maximum value as [ -0.083, -0.085]. 

Got Error as **float argument required, not list**
