### ISSUE TITLE
Unknown error -  shapely.geos.Geometry

### ISSUE THREAD

**Issue by AndresSepulveda** [OpenDrift/opendrift#274]
Hi,

I am getting the following error at the end of the calculations. The output NetCDF file is created and has several records, not sure if all of them. Any clue what it means? Seems associated to the final file.

![error_opendrift_not_too_big](https://user-images.githubusercontent.com/8628027/79576352-2229cf00-8091-11ea-9688-99ab4804f874.png)

**Comment by knutfrode** [comment]
I have not seen this error before, but given the log messages above, I would believe your output file is still complete(?)

Googling the error message gives some indications that you might have a corrupt shapely library:
https://github.com/Toblerity/Shapely/issues/566
https://github.com/SciTools/cartopy/issues/871

Perhaps you can try to reinstall it as suggested by those pages.

**Comment by knutfrode** [comment]
Did you manage to solve this problem?

**Comment by gauteh** [comment]
Closing, need more information.
