### ISSUE TITLE
how to convert the cst file and shp file to landmask?

### ISSUE THREAD

**Issue by llx206** [OpenDrift/opendrift#282]
Dear authors,
     I want to run a simulation using my own coastline data of cst and shape fomat. How to convert the cst file and shp file to landmask.

[coastline_data.zip](https://github.com/OpenDrift/opendrift/files/4619724/coastline_data.zip)

**Comment by gauteh** [comment]
llx206 writes on May 13, 2020 5:56:
> Dear authors,
>      I want to run a simulation using my own coastline data of cst and shape fomat. How to convert the cst file and shp file to landmask.

Are these alternate formats? Do you use either cst or shape?

**Comment by llx206** [comment]
i want to use cst format as  attachment, but i don't know how to convert it to landmask.

**Comment by gauteh** [comment]
Hi, we do not have a reader currently for these formats. Looking at https://www.xmswiki.com/wiki/SMS:Coastline_Files_*.cst I think the shape files are the most common / generic ones. They could be rasterized and used as landmask, or we would have to create a new reader which can use arbitrary shapes. This would be very similar to the existing global landmask reader.

**Comment by gauteh** [comment]
Are you able to try the changes in #285? See examples/example_shape_landmask.py.

**Comment by gauteh** [comment]
Shp files can be used as landmask: https://opendrift.github.io/gallery/example_shape_landmask.html
