### ISSUE TITLE
Installing in CENTOS?

### ISSUE THREAD

**Issue by AndresSepulveda** [OpenDrift/opendrift#287]
Does anyone here has some experience installing OpenDrift in a CentOS machine (CentOS Linux release 7.5.1804 (Core))?

There are  modules for python that I can't install

sudo yum install -y python3-mpltoolkits.basemap

and even for the OS system

sudo yum install -y libgeos-dev

gives me troubles.

Any advice is appreciated.

Andres

**Comment by knutfrode** [comment]
Hi
Basemap has been replaced with CartoPy in OpenDrift since last year, so installation is now easier. Miniconda is recommended:

https://opendrift.github.io/install.html

**Comment by AndresSepulveda** [comment]
ok, thanks. We are using OpenDrift connected to a web-server and our programmes says he can't use conda for this, that is why we want to install it from scratch. It has worked well in Ubunto machines, but this is a CentOS, and some libraries are different, it seems.

**Comment by knutfrode** [comment]
Ok, but then this is the updated list of required libraries (not anymore including Basemap, but now Cartopy):
https://github.com/OpenDrift/opendrift/blob/master/environment.yml

I (as most users) have only used Conda recently, but it would be useful with also some non-conda-installation instructions here:
https://opendrift.github.io/install.html
So please report back if you (or anyone else) find a convenient recipe.

**Comment by AndresSepulveda** [comment]
Sure, I can't edit the documentation part, so here is what we have done. The source of our trouble is that we call the python code using PHP and we don't know of a way to load the paths defined in the conda installation. 
[README_en.txt](https://github.com/OpenDrift/opendrift/files/4683819/README_en.txt)

**Comment by gauteh** [comment]
Are you running a python executable/script through fork / system call or
using python bindings in PHP? If it is the first, you can use conda run.

tir. 26. mai 2020, 19:10 skrev Andres Sepulveda <notifications@github.com>:

**Comment by gauteh** [comment]
Closing, need more information. Please re-open if needed.

**Comment by AndresSepulveda** [comment]
Well, we are basically giving up.

 We will try to use Dockers to make our Ubuntu-based configiration in this CentOS machine.

**Comment by gauteh** [comment]
Ok, you might be able to use pip with virtualenvs, but that won't really be a big difference from conda. If you have some example PHP code of how you interface to opendrift I might be able to see something more. Otherwise, using Ubuntu through docker sounds like a good plan.
