### ISSUE TITLE
Using OpenDrift with multiple single-record ROMS files

### ISSUE THREAD

**Issue by dpereiro91** [OpenDrift/opendrift#288]
Hi,

I am trying to run the OceanDrift3D model with ROMS. It works perfectly when the output of the ROMS model is in a single, multiple-record NetCDF file. However, the output of my ROMS setup consists of several NetCDF files. Each NetCDF file has just one time record (i.e. the length of the time dimension is 1). The time step between successive files is 1 hour. Accordingly, files are named as follows: "NEATL_2018050100.nc" for the 1st of May 2018 00:00, "NEATL_2018050101.nc" for the 1st of May 2018 01:00, etc. 

I tried to add to the model instance as many readers as ROMS NetCDF files using a for loop (code shown below). However, the following error is thrown:

13:28:52 INFO: OpenDriftSimulation initialised (version 1.2.0)
13:28:52 INFO: Opening dataset: D:\ROMS\NE_Atlantic\OUTPUT\HOURLY\NEATL_2018050100.nc
13:28:52 INFO: Opening file with Dataset
13:28:53 INFO: 'gls_cmu0'
13:28:53 INFO: Did not find complete set of GLS parameters
13:28:53 INFO: Making Splines for lon,lat to x,y conversion...
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<string>", line 42, in <module>
  File "C:\Users\dpereiro\Miniconda3\envs\opendrift\lib\site-packages\opendrift\readers\reader_ROMS_native.py", line 230, in __init__
    super(Reader, self).__init__()
  File "C:\Users\dpereiro\Miniconda3\envs\opendrift\lib\site-packages\opendrift\readers\basereader.py", line 184, in __init__
    self.time_step.total_seconds()) + 1
AttributeError: 'NoneType' object has no attribute 'total_seconds'

The cause of this error looks clear: in reader_ROMS_native.py there is the following code:

        if len(self.times) > 1:
            self.time_step = self.times[1] - self.times[0]
        else:
            self.time_step = None

So, since len(self.times) is 1, time_step is set to None and thus the error above.

I am wondering if there is a proper way of dealing with multiple, single-record NetCDF files like in my application when working with OpenDrift. Or should I merge all the NetCDF in a single one before using OpenDrift?

I have another question: my particle-tracking application would involve vertical motion of drifters, not only due to vertical currents 'w', but also due to drifters having an intrinsic density different than that of seawater, and thus experimenting buoyancy or sinking. I have seen the OpenDrift3D model (https://opendrift.github.io/autoapi/opendrift/models/opendrift3D/index.html) would suit my needs, but it is currently "under construction". Do you think it is possible to use this module as it is right now? Or is there a model that better suits this particle dynamics?

Thanks very much for you answer. I have found OpenDrift a really interesting project! Below is my Python code:

import sys
""" Add opendrift to PATH """
sys.path.append("H:\opendrift")

from opendrift.models.oceandrift3D import OceanDrift3D
from opendrift.readers import reader_ROMS_native
from datetime import datetime, timedelta

""" Set time """
idate = datetime(2018, 5, 1, 0) # starting date
edate = datetime(2018, 6, 1, 0) # end date

""" Set seeding conditions """
# Number of seeds
N = 100
# Longitude
x = -6
# Latitude
y = 46
# Radius [m]
r = 100000

""" Build time list """
time = []
while idate <= edate:
    time.append(idate)
    idate += timedelta(seconds=3600)

""" Set ROMS Grid and History file names """
grd = r"Y:\ROMS\INPUT\NE_Atlantic\GRID\ne_atlantic_r4_v2.nc"
his = [r"D:\ROMS\NE_Atlantic\OUTPUT\HOURLY\NEATL_" + \
       i.strftime("%Y%m%d%H") + ".nc" for i in time]

""" Set output file name """
out = "neatl_dft.nc"

""" Initialize model instance """
o = OceanDrift3D(loglevel=0)

""" Add reader to the model """
for i in his:
    o.add_reader(reader_ROMS_native.Reader(i, gridfile=grd))

""" Seed elements """
o.seed_elements(lon=x, lat=y, z=0, \
                number=N, radius=r, \
                    time=o.readers[list(o.readers.keys())[0]].start_time)
                
""" Run model """
o.run(end_time= o.readers[list(o.readers.keys())[-1]].end_time, \
      time_step=60, time_step_output=60, outfile=out)

**Comment by knutfrode** [comment]
Hi,

Regarding your ROMS files, they should be aggregated together using wildcards simply like this:
```
>>> r = reader_ROMS_native('NEATL_201805*.nc')
>>> o.add_reader(r)
```

OceanDrift3D should be right for your use, and is a subclass of OpenDrift3D, and therefore contains all its functionality. So you may add buoyancy to your particles at time of seeding:
```
>>> o.seed_elements(lon, lat, z=z, time, terminal_velocity=.001)  # 1 mm/s positive buoyancy
```

This functionality is only 2 weeks old, so you should have an updated repository for this to work.

**Comment by dpereiro91** [comment]
Thanks very much for your answer. Under this new functionality, is it currently possible to use a time-varying terminal-velocity under the same run (e.g. the drifter may experience density changes and thus sink and then refloat back to the surface)? 

Thanks.

**Comment by knutfrode** [comment]
Yes, this is possible. 
OpenOil3D is very basic and does not update the terminal velocity during the simulation. But you may make a subclass and implement this as you like. In the ```update``` method of your module, you can update the terminal velocity each timestep as:
```
>>> self.elements.terminal_velocity = ....<e.g. some function of self.environment>
```

```self.elements.terminal_velocity``` is an array with one value for each element/particle
Here is an example of how this is done in OpenOil3D module:
https://github.com/OpenDrift/opendrift/blob/master/opendrift/models/openoil3D.py#L297

**Comment by dpereiro91** [comment]
Thanks very much for your answer. I am wondering, if using wildcards is necessary to work with multiple input files, does this mean that all the input files must be kept under the same directory? Is there any workaround  when input files are located in different drives? Say, for instance, that files from 2016 are D:/2016/ROMS_* and files from 2017 are E:/2017/ROMS_*. In order to add them to the reader, is it the best solution to move all the files into the same directory or is there any workaround? 

Also, I have seen that MFDataset does not support NetCDF4. The following error is thrown: 

ValueError: MFNetCDF4 only works with NETCDF3_* and NETCDF4_CLASSIC formatted files, not NETCDF4

Should NetCDF4 files be converted to classic NetCDF or is there any alternative solution?

Thanks very much for your time and consideration.

**Comment by knutfrode** [comment]
I am not sure about wildcards. You could try with "*:/201?/ROMS*", but I doubt that would work. I am also not very familiar with Windows, but you could try googling, as this is a problem independent of OpenDrift.

Regarding netCDF4-files, it is true that Python-netCDF can nok make aggregates. But Xarray can do this, and for that reason the netCDF readers have been updated to use Xarray if it is installed.
There might be some undesired side-effects in using Xarray, but you could give it a try.

**Comment by gauteh** [comment]
Closed, re-open if necessary.
