### ISSUE TITLE
Particles caught at the boundary between two models

### ISSUE THREAD

**Issue by trondkr** [OpenDrift/opendrift#29]
We use two different ocean models (KINO + SVIM) to run particles along the Norwegian coast. This works nicely but there seems to be some particles that get caught in the intersection between the two model domains. Its like they get trapped and continue to follow the outline of the boundary between models. I attach two plots showing the model domain for the KINO model and the particle tracking.

![torsk_28102016_wgs84_polygon_7_kino_opendrift_15022012_to_15052012](https://cloud.githubusercontent.com/assets/3648387/19997467/0bc5c284-a267-11e6-921b-95d132264172.png)

[map_NS8KM_and_KINO1600M.pdf](https://github.com/knutfrode/opendrift/files/570790/map_NS8KM_and_KINO1600M.pdf)

**Comment by knutfrode** [comment]
I guess this could happen if the models have inconsistent current direction
at the boundary, with a northerly current component for the southern/inner
model, and a southerly component at the larger/outer domain. The particles
would then be pushed back-and forth, and would propagate sideways along the
boundary. But the artefact-line seems to be nearly 300 km, and it should be
unlikely(?) that such situation would persist for such long time/distance.
However, it could also be that the artefact-line consists of several
smaller such "boundary-trappings". An animation, with
o.animation(filename='animation.mp4'), could perhaps help the
interpretation of what is going on.

2016-11-04 8:18 GMT+01:00 Trond Kristiansen <notifications@github.com>:

**Comment by johannesro** [comment]
Hi Trond,

do you have a plot of the horizontal velocities of both models?
As far as I remember from your presentation, KINO was nested into Svim,
right? In that case, there really shouldn't be such inconsistent
velocities, but boundary conditions are difficult to get nice.
What kind of boundary scheme are you using in KINO for u,v and U,V? Are you
using a sponge zone?

Are both model run with the same tides?

A quick fix could be to use more stochastic dispersion in opendrift.

Greetings
Johannes



Johannes Röhrs, PhD
Norwegian Meteorological Institute
www.met.no / www.yr.no

johannes.rohrs@met.no
+47 41654886
