### ISSUE TITLE
Question about land_binary_mask

### ISSUE THREAD

**Issue by limaolin1981611** [OpenDrift/opendrift#316]
There are 2 questions about land_binary_mask:
1.In the example_leeway.py, I added and did not add the reader_landmask, but the output was the same. So when do i need to add reader_landmask?
2.I seed elements at 38.9N 121.6E, but the map of output is not correct, the pictures are as follows
![mmexport1592830123122](https://user-images.githubusercontent.com/62914884/85340329-7f6e5080-b518-11ea-9745-b0d5b36b5a18.jpg)
![leeway_point_run](https://user-images.githubusercontent.com/62914884/85340368-8f863000-b518-11ea-926c-d8b80a1deeb0.png)

**Comment by knutfrode** [comment]
I believe this bug was fixed a couple of weeks ago.
Could you update to latest version, and see if that helps?

**Comment by knutfrode** [comment]
Regarding question 1: It is not anymore necessary to add a landmask reader explicitly, as this will be done automatically at the start of the simulation.

**Comment by limaolin1981611** [comment]
Thanks for your reply. I have tried the latest version, and it's correct now.
Another question, I have installed the 32-bit Anaconda3, and tried to install the opendrift according to "Fresh development environment". When I runed th3.1e "conda env create -f environment.yml",  it's not correct, the output were as followes:
ResolvePackageNotFound:
- pygrib
-gdal[version='>=3.1']
-libgdal='>=3.1']

I tried to install pygrib using 'conda install pygrib', but it's not correct too:
The following packages are not available from current channels:
  -pygrib
Current channels:
......
......

**Comment by gauteh** [comment]
limaolin1981611 writes on July 2, 2020 1:15:
> Thanks for your reply. I have tried the latest version, and it's correct now.
> Another question, I have installed the 32-bit Anaconda3, and tried to install the opendrift according to "Fresh development environment". When I runed th3.1e "conda env create -f environment.yml",  it's not correct, the output were as followes:
> ResolvePackageNotFound:
> - pygrib
> -gdal[version='>=3.1']
> -libgdal='>=3.1']
>
> I tried to install pygrib using 'conda install pygrib', but it's not correct too:
> The following packages are not available from current channels:
>   -pygrib
> Current channels:
> ......
> ......

Do you have conda-forge in that list? Try:

conda config --add channels conda-forge

If you are missing more opendrift packages you can also add:

conda config --add channels noaa-orr-erd
conda config --add channels opendrift

Regards, Gaute

**Comment by limaolin1981611** [comment]
yes, I have tried the 'conda config --add channels conda-forge', and "Waring: 'conda-forge' already in 'channels' list, moving to the top". I also tried the 'conda config --add channels noaa-orr-erd' and 'conda config --add channels opendrift'. But it's not worked.
