### ISSUE TITLE
Format of date and time

### ISSUE THREAD

**Issue by AndresSepulveda** [OpenDrift/opendrift#318]
Hi,

 In order to change the title of my plots I want to obtain only the date from

mosa_native = reader_ROMS_native.Reader(filename_nc)
initime = mosa_native.start_time
fintime = mosa_native.end_time

I currently get the date+hour:minute:seconds

How can I select that part of the variable?

**Comment by knutfrode** [comment]
You may override the title as you like, e.g.:

```
>>> o.plot(title='%s to %s UTC' % (o.start_time.strftime('%Y-%m-%d'), o.time.strftime('%Y-%m-%d')))
```

**Comment by AndresSepulveda** [comment]
Great, thanks. That works fine.
