### ISSUE TITLE
Inconsistency between wind- and wave driven mixing

### ISSUE THREAD

**Issue by johannesro** [OpenDrift/opendrift#33]
There is a inconsistency between vertical mixing of oil droplets between using wind- and the respective wave parameterization. The test_physics module has a test for both. 

Wave-driven mixing uses
 o.fallback_values['sea_surface_wave_period_at_variance_spectral_density_maximum'] = 5.8
o.fallback_values['sea_surface_wave_significant_height'] = 2.5
and yields the following vertical profile:
![wave](https://cloud.githubusercontent.com/assets/8707755/21342870/6b969372-c694-11e6-8a62-719d953b4c9f.png)

Using a wind-driven mixing with corresponding intensity
o.fallback_values['x_wind'] = 10
gives
![wind](https://cloud.githubusercontent.com/assets/8707755/21342904/8ec0054a-c694-11e6-9e1d-0e03e4d9d6df.png)

If fallback values for both are given, which is the methods that is most realistic to apply, 
we get:
![wind_and_wave](https://cloud.githubusercontent.com/assets/8707755/21342920/a968713e-c694-11e6-842f-3a96df975670.png)

All three methods should give similar results if the parameterizations were correctly implemented. I'll  be working on this now.
@knutfrode let me know if you have any ideas about this.

**Comment by knutfrode** [comment]
It is good if you can check this to improve consistency.
I guess the method [significant_wave_height()](https://github.com/OpenDrift/opendrift/blob/master/opendrift/models/physics_methods.py#L188
) in module "physics_methods" should be central.

I have just one note about this plotting function which might be misleading sometimes: For a given profile and number/fraction of elements at the surface, the ratio of surface to submerged elements depends on the vertical bin size (typically 1m or 2m). The smaller the bins, the larger fraction of elements appear to be at the surface. However, as long as bins are the same, profiles should at least be comparable.

**Comment by johannesro** [comment]
Using 

o.fallback_values['sea_surface_wave_period_at_variance_spectral_density_maximum'] = 5.8
did not work due to a bug in wave_period()
this explaines the difference between case 1 and 3.

There was still a difference between case 2 and the other two cases because a wind speed of 10m/s yields a wave period of 8.5s and not 5.8s (the latter is used in test_physics.py). Is this a bug or was the wave period actually 5.8s in the Jones et al reference case? 

Conclusively, the degree to which particles are mixed downwards from the surface is very dependent on wave period. Short waves are steeper and have more whitecaps given constant wave height.

**Comment by johannesro** [comment]
There was also a bug in the plot_vertical_distribution, now the actual dz is used for the bins.

**Comment by knutfrode** [comment]
Good that you fixed bugs.
In the Jones paper, wave model (WAM4) gave Hs around 2.1-2.4 m and period (sea_surface_wave_period_at_variance_spectral_density_maximum) around 5.6-5.7 s.
Winds from Arome around 10-12 m/s were used, but WAM4 was forced with EC winds I believe, so not really consistent here.
Wave entrainment rate was however not calculated from wave input, but was simply a tuning parameter. Waves were only used for Stokes drift.

**Comment by johannesro** [comment]
Ok, than the similarity between 5.8 and 8.5 was just a coincidence. The two cases are not directly comparable, but that is not a problem.
