### ISSUE TITLE
conda env create -f environment.yml  failed

### ISSUE THREAD

**Issue by limaolin1981611** [OpenDrift/opendrift#332]
I have installed 64-bit Anaconda3 and opendrift correctly. But I need to install 32-bit Anaconda3. After I installed it, I tried to install the opendrift according to "Fresh development environment". When I runed the "conda env create -f environment.yml", it's not correct, the output were as followes:
ResolvePackageNotFound:

pygrib
-gdal[version='>=3.1']
-libgdal='>=3.1']
I tried to install pygrib using 'conda install pygrib', but it's not correct too:
The following packages are not available from current channels:
-pygrib
Current channels:
- http://conda.anaconda.org/conda-forge/win-32
- http://conda.anaconda.org/conda-forge/noarch
- http://repo.conda.anaconda.com/pkgs/main/win-32
- http://repo.conda.anaconda.com/pkgs/main/noarch
......

I also tried the 'conda config --add channels noaa-orr-erd' and 'conda config --add channels opendrift'. But it's not worked.

**Comment by knutfrode** [comment]
gdal and libgdal is mainly used for seeding withtin shapefiles etc, so you might remove those from environment.yml if you don't need this feature.

Regarding pygrib, you might try an alternative installation, e.g. https://stackoverflow.com/questions/35640117/installing-pygrib-package

Is there a particular reason why you need 32 bit? 
Note that OpenDrift does not anymore support Python2.

**Comment by limaolin1981611** [comment]
I want to use opendrift in vs2008(32-bit), so I need to use 32-bit Anaconda3.

**Comment by limaolin1981611** [comment]
I need to use C++(VS 2008) and Opendrift to finish a Project. How can I to use 64-bit Anaconda3 in 32-bit VS2008
