### ISSUE TITLE
How Can I use bat file of cmd to run the leeway demo? 

### ISSUE THREAD

**Issue by limaolin1981611** [OpenDrift/opendrift#333]
I have installed the Anaconda correctly and added the  envionment variables to the Path. Then, I can use cmd to run the leeway demo step by step. But if I write all commands in the bat file, it's not worked. How Can I use the bat file to run the leeway demo automatic. The commands of bat file are as follows:

E:
cd Project\SAR\opendrift-master
conda activate opendrift
pause
python leeway_fun.py
pause

**Comment by limaolin1981611** [comment]
According to https://docs.conda.io/projects/conda/en/latest/user-guide/troubleshooting.html#using-conda-in-windows-batch-script-exits-early, I have solved the problem. I changed to commands as follows:
E:
cd Project\SAR\opendrift-master
CALL conda activate opendrift
python leeway_fun.py
pause

**Comment by knutfrode** [comment]
Good. Thanks for sharing the solution.
