### ISSUE TITLE
Connectivity indices

### ISSUE THREAD

**Issue by knutfrode** [OpenDrift/opendrift#339]
@AndresSepulveda I am planning to calculate the connectivity between locations based on simulated trajectories.
I noticed in [this post](https://www.researchgate.net/post/Is_there_a_general_Lagrangian_particle_simulation_software_for_ocean_currents_to_create_connectivity_matrices_between_populations) that your colleague has written some code for this.
Is this something you could share? It could eventually be integrated into OpenDrift as an analysis tool.

**Comment by AndresSepulveda** [comment]
Hi Knut,

Sorry, I just discovered this post. We do have some code, but it is in Octave and in R, not in Python (I am happy to share it, anyways).

The issue becomes a bit complicated if one seeds many files around a list of initial seeding points. So far we are constructing the code with two input files: the trajectories and the release points (a CSV), that also act as end points in our connectivity study.

**Comment by knutfrode** [comment]
Hi,

Yes, it would be interesting to have a look at this code, even if not Python. You may send it to knutfd@met.no, or share by other means as you prefer. Or if you attach it to this issue, it could be of use to others as well.

Also I would be interested in links to any papers where yourself or others have used such analysis.

**Comment by AndresSepulveda** [comment]
Here is a R code to calculate the "total" distance traveled, depending on the starting point. "Total" here is considered as between final and initial point, so if it comes back to a nearby point it will be a small value. A  neccessary improvement is to integrated the traveled distance.

![LatVsDistance](https://user-images.githubusercontent.com/8628027/91596125-b6a31880-e932-11ea-93c9-2441de2494ea.png)
![HistogramDistance](https://user-images.githubusercontent.com/8628027/91596156-c3277100-e932-11ea-9d9a-603d94795c7a.png)


[plot_OpenDrift_TotalDisplacement_Knut.txt](https://github.com/OpenDrift/opendrift/files/5143409/plot_OpenDrift_TotalDisplacement_Knut.txt)

**Comment by knutfrode** [comment]
Thank you, I will have a look.
