### ISSUE TITLE
Seeding depending on NetCDF input file times

### ISSUE THREAD

**Issue by AndresSepulveda** [OpenDrift/opendrift#341]
Hi,

I am seeding particles for as many days the NetCDF file is being read has using

  o.seed_elements(lon=confobj.st_lons,
                        lat=confobj.st_lats,  radius = 1000,
                        number=confobj.releaseParticles,
                        time=[reader_physics.start_time,reader_physics.end_time],
                        z=-10)

since this is not optimal (particles at the last time step will not move), how can I substract/add X number of days in

                        time=[reader_physics.start_time,reader_physics.end_time],

I've tried

                        time=[reader_physics.start_time,reader_physics.start_time´+timedelta(days=3)],

and it doesn't work.  Any help is appreciated....

Andrés

**Comment by knutfrode** [comment]
I would think this should work?
`time = [reader_physics.start_time, reader_physics.start_time-timedelta(days=3)]`
Otherwise, which error does this give you?

**Comment by AndresSepulveda** [comment]
The definition of time works,  just not in the way I want it to work.  

In this call

  o.seed_elements(lon=confobj.st_lons,
  lat=confobj.st_lats, radius = 1000,
  number=confobj.releaseParticles,
 time=[reader_physics.start_time,reader_physics.start_time+deltatime(days=3)],
 z=-10)

there are three release points (in confobh.st_lons), 60 particles, and time works. But only 60 particles total are released.

The idea was that at each time step, 60 particles are to be released, at each of the release points (within a 1000m radius).

Is there a way to do it in a single call to seed_elements or do I nedd to create a loop?

**Comment by AndresSepulveda** [comment]
As for the loop option, this can be done with 

    tini = reader_physics.start_time - reader_physics.start_time + timedelta(days=3)
    for day in range(int(tini.days)):
        o.seed_elements(lon=confobj.st_lons,
                        lat=confobj.st_lats,  radius = 1000,
                        number=confobj.releaseParticles,
                        time=reader_physics.start_time + timedelta(days=day),
                        z=-10) 

But I get 180 particles released, not  540 = 3 * 3 * 60  (days * locations * number of particles ). What am I missing...

**Comment by knutfrode** [comment]
I think it is better here to rather loop over the stations, and seed over the given time span.
Or perhaps enven clearer would be to use a double loop: (stations, days)

It is possible to do the seeding in a single call, but then you need to construct arrays of all the variables (lon, lat, number, time, radius) of the same length (product of all dimensions, 3*3*60), using e.g. meshgrid.
Generally, all of these variables can have length 1 (scalar), 2 [start and end, as for time span], or length N, where N is the number of releases. Even `number` may in this case be an array, with the amount of particles per release. However, this might become tricky and hard to understand, to maybe the cleares in your case would be to use a double loop (stations, days)

Btw, The seeding method is quite slow for large releases, as is uses recursive calls internally. A re-write of this method is planned, including a clearer, updated documentation.

**Comment by AndresSepulveda** [comment]
Thanks, that will work for now

    for punto in range(len(confobj.st_lons)):
       for day in range(int(tini.days)):
           o.seed_elements(lon=confobj.st_lons[punto],
                        lat=confobj.st_lats[punto],  radius = 1000,
                        number=confobj.releaseParticles,
                        time=reader_physics.start_time + timedelta(days=day),
                        z=-10)

**Comment by knutfrode** [comment]
A last comment: if lon/lat and time are all arrays with 3 elements, it is ambigous, as the seeding method cannot know whether each time correspond to each position, or wherever you want all combinations (as in your case). Therefore a loop is here necessary, or a meshgrid-solution.
