### ISSUE TITLE
question about polygon in leeway

### ISSUE THREAD

**Issue by limaolin1981611** [OpenDrift/opendrift#346]
I use two polygons to seed in leeway, the points are as follows: 

(1)polygon 1
lon_input=[115.5, 115.5, 116.5, 116.5, 116]
lat_input=[21.5, 22.5, 22.5, 21.5, 21]

(2)polygon 2
lon_input=[115.5, 115.5, 116.5, 116.5, 116, 116, 115]
lat_input=[21.5, 22.5, 22.5, 21.5, 21, 23, 22]

the outputs of seed in leeway are as follows:
![leeway_polygon_seed](https://user-images.githubusercontent.com/62914884/89186645-abc4c480-d5ce-11ea-8455-957ebc33b1b3.png)
![leeway_polygon_seed1](https://user-images.githubusercontent.com/62914884/89186663-b1baa580-d5ce-11ea-9f4b-b2c70c472287.png)

The question is how does picture 2 comes out?

**Comment by knutfrode** [comment]
The second polygon is ill-shaped, and crosses itself. There is no check for this in OpenDrift, so output is then unpredictable.

If you change the 23 to 20 in `lat_input`, you get a real polygon.

**Comment by limaolin1981611** [comment]
yes, If I change the the 23 to 20 in lat_input, the output is right as follow:
![leeway_polygon_seed](https://user-images.githubusercontent.com/62914884/89415562-9a122700-d75e-11ea-9b92-56191a3f9c3f.png)
There is another question, How can I find the most popular position in the polygon?

**Comment by limaolin1981611** [comment]
yes, If I change the the 23 to 20 in lat_input, the output is right as follow:
![leeway_polygon_seed](https://user-images.githubusercontent.com/62914884/89415908-23c1f480-d75f-11ea-81e4-75701caffd3c.png)

There is another question, How can I find the most popular position in the polygon?

**Comment by knutfrode** [comment]
What do you mean by "most popular position"?
The elements should be evenly distributed within polygons, if radius=0. From your plot I see that you have a small radius/perturbation/uncertainty, which can be set to 0 if preferred.

**Comment by knutfrode** [comment]
Closing this issue. Please re-open if still relevant.
