### ISSUE TITLE
Release particles from the bottom?

### ISSUE THREAD

**Issue by AndresSepulveda** [OpenDrift/opendrift#354]
Hi,

I would like to release particles from the bottom, in a cylinder with a certain height and radius. 

Is there a way to automatically define de depth of the release point, giving only lat and lon?

**Comment by knutfrode** [comment]
The depth can be fetched from any reader which contains the variable `sea_floor_depth_below_sea_level`
e.g:
```
from opendrift.readers.reader_netCDF_CF_generic import Reader
r = Reader('https://thredds.met.no/thredds/dodsC/sea/norkyst800m/1h/aggregate_be')
x,y = r.lonlat2xy(lon=5, lat=60)
d = r.get_variables(['sea_floor_depth_below_sea_level'],
                    time=r.start_time, x=x, y=y)
print(d['sea_floor_depth_below_sea_level'][0][0])

135.53109741210938
```

Note that it is also possible to provide e.g. `z=seafloor+10` to the seeding method to seed elements 10m above seafloor. This will then do the above to obtain the seafloor depth, and thus a corresponding reader must be added to the object first:
```
from opendrift.models.oceandrift import OceanDrift
o = OceanDrift(loglevel=20)
o.add_reader(r)
o.seed_elements(lon=5, lat=60, z='seafloor+10', time=r.start_time)
print(o.elements_scheduled)

...
lon: [5.]
lat: [60.]
z: [-126.28499]
...
```

It is not possible to seed a "vertical cone" from one depth to another (as is possible from one lon,lat position to another), so arrays of lon, lat, radius and z should be prepared externally before seeding, or with a loop over depths (`Z`) with `z=seafloor+Z`

**Comment by AndresSepulveda** [comment]
Thanks, this advice was useful, I finally did this:

 x,y = mosa_native.lonlat2xy(lon=lon,lat=lat)
 d = mosa_native.get_variables(['sea_floor_depth_below_sea_level'],
    time=mosa_native.start_time,x=x,y=y)

 print('Depth of site')
 print(d['sea_floor_depth_below_sea_level'][0][0])
 ada=float(d['sea_floor_depth_below_sea_level'][0][0])

 totpart = 100
 auxdepths = range(totpart)
 maxdepth = 30.
 depths=[(tmplist/(max(auxdepths)*1.))*maxdepth for tmplist in auxdepths]

 sf_d=np.empty(totpart)
 for i in range(totpart):
    sf_d[i]=-1*ada+depths[i]

 o.seed_elements (lon ,lat ,radius =300 ,number =totpart ,z =sf_d ,
   time =s_time)
