### ISSUE TITLE
Lack of vertical movent.

### ISSUE THREAD

**Issue by AndresSepulveda** [OpenDrift/opendrift#355]
[salida.log](https://github.com/OpenDrift/opendrift/files/5087245/salida.log)

Hi, I am using a CROCO file with u, v, and w velocities and OceanDrift module. However the particles stay at the same depth. The w velocity is there, so it should be read and used by default, isn't it?

Log attached for details.

**Comment by knutfrode** [comment]
The log doesn't say whether your croco file contains `w`, but you are using OceanDrift v1.2.3, which is a 2D model. If you were using OceanDrift3D instead, you should get vertical movement as well.

However, from version 1.3.0, OceanDrift3D has been merged into OceanDrift, which is now a 3D-model, where vertical motion can be disabled if desired:
```
>>> o.disable_vertical_motion()
```

https://opendrift.github.io/history_link.html

**Comment by AndresSepulveda** [comment]
Ok, my bad. I tought I was using v1.3.0, thanks.
