### ISSUE TITLE
leeway 

### ISSUE THREAD

**Issue by dharanidharan12** [OpenDrift/opendrift#36]
How to add Pressure, waves, temperature in leeway

**Comment by knutfrode** [comment]
I am not sure what you mean by this. Leeway moves objects due to surface currents and wind, from tabulated (measured) drift properties for various object categories. Pressure, waves and temperature are not a part of this algorithm.

Generally, any OpenDrift model specifies which parameters are needed in as self.required_variables
https://github.com/OpenDrift/opendrift/blob/master/opendrift/models/leeway.py#L76
And these variables (read by readers) are then used within the models update() method to update position and properties of the relevant elements during the run.

**Comment by dharanidharan12** [comment]
In Openoil
how to covert current value as x and y values.
for example : current =5 , by how  to calculate or split x current and y current values

**Comment by knutfrode** [comment]
OpenDrift consequently uses CF-convention for naming of variables:
http://cfconventions.org/Data/cf-standard-names/40/build/cf-standard-name-table.html

Components of current are named 'x_sea_water_velocity',
'y_sea_water_velocity'
So any models which "require" some variables can use any readers which can
provide the same variables.

2017-02-16 14:10 GMT+01:00 Dharani_Dharan <notifications@github.com>:

**Comment by dharanidharan12** [comment]
In Leeway:
how to calculate the **wind speed** and **wind direction** using the x_wind and y_wind.
I have added a file . 
please help me to calculate the wind speed and wind direction. 
Also for current direction and current speed.
using

[simple1.py.zip](https://github.com/OpenDrift/opendrift/files/784808/simple1.py.zip)
 lw.fallback_values['x_wind']= -2.18083
lw.fallback_values['y_wind']= 1.54903
lw.fallback_values['x_sea_water_velocity'] = 0.025127
lw.fallback_values['y_sea_water_velocity'] = 0.436427

here i given values based on grib file . But don't know how to calculate wind speed, wind direction, current speed, current direction.

Please Help!!!
Thanks In Advance!!!

**Comment by dharanidharan12** [comment]
**To calculate wind direction and wind speed:**
wind_direction =round(57.29578 * (math.atan2(y_wind,x_wind))+180)
wind_speed = round(float(np.sqrt(x_wind * x_wind + y_wind * y_wind) * 3.6),2)

Whether these formulas are right ???

But don't know to calculate current speed and current direction.
Please Help !!!

**Comment by dharanidharan12** [comment]
what is the units of x_wind , y_wind , x_sea-water_velocity and y_sea_water_velocity.
Please help !!! Mention all the units in opendrift.

Thanks in Advance!!!

**Comment by johannesro** [comment]
All units are SI units.

Johannes Röhrs, PhD
Norwegian Meteorological Institute
www.met.no / www.yr.no

johannes.rohrs@met.no
+47 41654886

**Comment by ZenKa24** [comment]
Dear Knut,

Why you don't consider the effect of waves on objects in Leeway? Because I think that significant hight wave and wave direction have a strong effect on objects on the sea surface.

**Comment by johannesro** [comment]
Hi ZenKa,

The effekt of waves on leeway objects is already implicitely included in
the used empirical leeway coefficients that the model uses.

If you want to describe the Stokes drift explicitely, you can use your own
leeway coefficients and supply OpenDrift with Stokes drift data from a wave
model, or use the build-in parameterization of Stokes drift by wind speed.
In the latter case, I would not expect differences from using the empirical
leeway coefficients that already include the effect of the Stokes drift.

Greetings
Johannes

Johannes Röhrs, PhD
Norwegian Meteorological Institute
www.met.no / www.yr.no

johannes.rohrs@met.no
+47 41654886

**Comment by ZenKa24** [comment]
So, How can I know to choose exactly wind_drift_factor for my case?

**Comment by knutfrode** [comment]
The leeway coefficients are given in this file for each category:
https://github.com/OpenDrift/opendrift/blob/master/opendrift/models/OBJECTPROP.DAT

Please see at the bottom for explanation and references.
Note that this includes both downwind and cross-wind components.

```wind_drift_factor``` as used in e.g. [OceanDrift](https://github.com/OpenDrift/opendrift/blob/master/opendrift/models/oceandrift.py) and [OpenOil](https://github.com/OpenDrift/opendrift/blob/master/opendrift/models/openoil.py) corresponds to the downwind leeway coefficient. In [OceanDrift](https://github.com/OpenDrift/opendrift/blob/master/opendrift/models/oceandrift.py) and [OpenOil](https://github.com/OpenDrift/opendrift/blob/master/opendrift/models/openoil.py) you can specify this factor as you like, but in Leeway model it is tabulated from empirical experiments.

**Comment by ZenKa24** [comment]
So, If I want to simulate a sunken ship, for example, I only choose objType which considering all of describing the drift properties of an object (nine columns), Is'n it?

**Comment by knutfrode** [comment]
Yes, that is correct.

**Comment by ZenKa24** [comment]
Many Tak, Knut-Frode and Johannes :+1:

**Comment by dharanidharan12** [comment]
In Leeway:
for example:
While using **objType = 3.** 
in seeding elements:
 **number=2**
why there is a much change of drift for each object. 
All number of object have to move in  same way, why there is a lot of changes between each of the object. WHY???

**Comment by knutfrode** [comment]
This is expected behaviour. Leeway is a stochastic-empirical model, where the Leeway coefficients for each object category (file OBJECTPROP.DAT) represent both the mean and standard deviation of both the along-wind and cross-wind coefficients.
Besides, objects may drift to the left or right of the wind, and it is normally not possible to know the orientation in advance; thus half of the elements are initially right-oriented, and the other half left-oriented. The probability of shifting (jibing) is 4% per hour.
You can read more about the principle behind the Leeway model here: https://arxiv.org/abs/1111.0750

**Comment by dharanidharan12** [comment]
What  properties of oil are   specified in **oilprop.dat**  file .. Please name the Properties..
And where we are using those properties.
for example:
LIGHT (draugen)		15
2.00	10.0	10.0	        10.0
0.00	0.0	823.0	0.0	3.1	3.1	-33.0	0.0
0.25	23.8	868.3	7.6	59.4	67.9	-3.6	15.7
0.50	27.0	874.2	15.8	99.2	131.5	0.6	31.3
1.00	29.9	879.5	28.7	157.7	269.1	4.4	46.4
2.00	32.5	884.2	45.9	238.5	588.9	7.9	60.4
3.00	34.0	886.8	55.8	299.8	938.0	9.8	68.9
6.00	36.3	891.1	67.1	437.3	1826.1	13.0	82.4
9.00	37.7	893.6	69.4	542.6	2409.2	14.9	90.2
12.00	38.6	895.3	69.9	630.1	2832.9	16.2	95.7
24.00	40.8	899.3	70.0	895.8	4040.3	19.2	107.5
48.00	43.0	903.3	70.0	1265.7	5708.6	22.3	118.8
72.00	44.3	905.6	70.0	1551.1	6995.5	24.1	126.5
96.00	45.2	907.3	70.0	1801.3	8124.3	25.4	132.6
120.00	46.0	908.7	70.0	2030.5	9158.0	26.5	137.6
480.00	51.9	919.4	70.0	5206.8	23483.3	35.1	158.7

**Comment by dharanidharan12** [comment]
**Please Help!!!.. I lost all my work.. Now freshly starting it...**
my system got crashed. so I freshly installed ubuntu
and for **opendrift** installed the requirements

**while running the opendrift folder examples.py file** 

Getting error like:
 **from opendrift.readers import reader_basemap_landmask**
 **ImportError: No module named opendrift.readers**

set path through 
**export PATH=$PATH:$OPENDRIFT_FOLDER/opendrift/scripts/**


while checking the path through:

echo $PATH

output:
/home/user1/miniconda2/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:-master/opendrift/scripts/:$/usr/local/bin/opendrift/scripts/:$/opendrift/opendrift/scripts/

**Comment by dharanidharan12** [comment]
for trying  **./scripts/readerinfo.py**
Getting Error like:
**Please add opendrift folder to your PYTHONPATH**

How to add opendrift folder in pythonpath..

**Comment by knutfrode** [comment]
You need to add $OPENDRIFT_FOLDER/opendrift/ to your PYTHONPATH:
export PYTHONPATH=$PYTHONPATH:<your_opendrift_folder>/opendrift/

This should have been done automatically if you ran setup.py
Please see installation section:
https://github.com/opendrift/opendrift/wiki#download-and-installation

**Comment by dharanidharan12** [comment]
**Not Working!!! What I did wrong ???**
Having opendrift in home folder.
opendriftfolder: **/home/myname/opendriftfoder**

Tried through:
**export PYTHONPATH=$PYTHONPATH:/home/myname/opendriftfoder/opendrift/**
checked echo $PYTHONPATH

:/home/myname/Downloads/opendrift/opendrift/scripts/:/home/myname/opendrift/opendrift/:/usr/local/bin/
Not worked. how to make it work.

checked  echo $PATH
/home/myname/miniconda2/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:$/Download/opendrift-master/opendrift/scripts/:$/home/myname/opendrift/scripts/:$/home/myname/opendrift/opendrift/scripts/

**Comment by knutfrode** [comment]
Your PYTHONPATH should point to the main opendrift folder, not to its subfolder which is also named opendrift. This might be confusing, but is a standard python package convention.

Also only PATH should also point to the /scripts/-folder, not PYTHONPATH.

**Comment by dharanidharan12** [comment]
leeway and openoil supports which time standard. 
for example:
 UTC or GMT

**Comment by knutfrode** [comment]
OpenDrift uses UTC, which is the same as GMT.

2017-04-20 11:51 GMT+02:00 Dharani_Dharan <notifications@github.com>:

**Comment by dharanidharan12** [comment]
In Leeway 
how to pass windspeed  and winddirection directly in leeway, without using x_wind and y_wind values. 
I having the windspeed value
example: 7.02 m/s 
how to implement windspeed value to calculate 
1. downwind_leeway
2.crosswind_leeway
please help!!!

**Comment by dharanidharan12** [comment]
In Leeway: if reading files not available.i.e No reader files.Then,  How to pass windspeed manually.
Please Help!!!

**Comment by knutfrode** [comment]
Then you can set ```fallback_values``` as explained in the docs, or use
```constant_reader```:
https://github.com/OpenDrift/opendrift/blob/master/opendrift/readers/reader_constant.py

2017-04-28 7:15 GMT+02:00 Dharani_Dharan <notifications@github.com>:

**Comment by dharanidharan12** [comment]
How latitude and longitude are given as negative values like -180,-90
In Basemodel.py file
(self.elements.lon.min() < -180) or 
( self.elements.lon.min() > 360) or 
(self.elements.lat.min() < -90) or 
( self.elements.lat.max() > 90)

**Comment by knutfrode** [comment]
Are you getting problems with longitudes < 180?
If so, you can try to change -180 to -360 in that first line. You may also
try to change  < to <= for latitudes, but I guess it will be extremely rare
to have elements exactly at the poles.

2017-05-12 15:42 GMT+02:00 Dharani_Dharan <notifications@github.com>:

**Comment by dharanidharan12** [comment]
I passing winddirection as 90 degree but it moving along 270 degree.
while passing 45 degree it moving from 255 degree...

lon = 80.8843; lat = 13.095;
reader_basemap = reader_basemap_landmask.Reader(llcrnrlon=80.0, llcrnrlat=12.5, urcrnrlon=82.0, urcrnrlat=14.5, resolution='i', projection='merc')

I added windspeed,winddirection in fallbackvalues.
using fallbackvalues I passed wind direction. but got some error in degrees.
Please Help..
Here I attached the file. 
[sample1.py.zip](https://github.com/OpenDrift/opendrift/files/1007572/sample1.py.zip)
![may17_1](https://cloud.githubusercontent.com/assets/20634645/26152470/b175810a-3b24-11e7-8c93-ec9be593ebb7.png)

**Comment by dharanidharan12** [comment]
How to correct direction degree for wind.
[sample1.py.zip](https://github.com/OpenDrift/opendrift/files/1009791/sample1.py.zip)

Please Help!!!

**Comment by dharanidharan12** [comment]
In **Leeway**, while passing **current direction** , **the object moves along with the current** .
Passing wind direction and current direction objects moves fine with the directions.
But **passing wind direction alone, the object doesn't takes effect**. 
How to rectify this issue???

Please Help!!!
Thanks in Advance!!!

**Comment by knutfrode** [comment]
OpenDrift does not support ingesting winddir and windspeed, but only components (x_wind, y_wind), and likewise for current. So apparently this is functionality which you have added yourself.

With 'winddir' and 'currentdir' there is always danger of confusing 'direction from' and 'direction to', where the first is standard for wind, and the latter is standard for currents.
Interpolating and averaging directions is also often not meaningful, so using components is safer.
If calculating components form direction and speed, you must also take into account that x and y is not necessarily East and West, this depends on the actual map projection, which might be different for each reader.

**Comment by dharanidharan12** [comment]
**In Openoil:** 
Why??? Effect of current is more, While Effect of Wind is lesser 
The Object falls based on current ...
Is it Right?? Please Help!!!

**Comment by knutfrode** [comment]
For OpenDrift, as in any other ocean drift model, it is assumed that
elements/objects follow the current, but with only a few percent of the
wind (wind drag). For oil at the ocean surface the wind drag is 2%, which
comes in addition to the Stokes drift component (another ~1.5% of the wind).

2017-07-04 9:50 GMT+02:00 Dharani_Dharan <notifications@github.com>:
