### ISSUE TITLE
About miss NOAA database

### ISSUE THREAD

**Issue by ZenKa24** [OpenDrift/opendrift#38]
Dear authors,
I have installed OilLibrary for my Oil model which I am using. However, when I ran oil model I got this error:
ValueError: Oil type "ARABIAN MEDIUM, API" not found in NOAA database

Would you please help me fix this error? Or If I want to reinstall OilLibrary what I should do that?
I install it on ubuntu 12.04 (64bit).

Thanks and best regards,

**Comment by knutfrode** [comment]
This seems to be a problem with your OilLibrary installation, and not with OpenDrift.
It is probably a good idea to reinstall the OilLibrary from scratch:
```
$ git clone https://github.com/NOAA-ORR-ERD/OilLibrary.git
$ cd OilLibrary/
$ pip install -r requirements.txt # This is not mentioned on NOAA page
$ python setup.py develop
$ python setup.py test  # to check that everything is ok
```
Your Ubuntu is quite old, by the way. It will probably solve some problems if you could update to a newer version.

**Comment by ZenKa24** [comment]
I did it but I got this error:
Installed /home/haivan/OilLibrary
Processing dependencies for oil-library==0.0.9
Finished processing dependencies for oil-library==0.0.9
OilLibrary database exists - do not remake!

Maybe I need remove old version. What I should do to remove old version?

**Comment by knutfrode** [comment]
Yes, you should delete the old version, simply by deleting the whole
OilLibrary-folder.

2017-03-03 10:45 GMT+01:00 ZenKa24 <notifications@github.com>:

**Comment by dharanidharan12** [comment]
I tried to install OilLibrary, but sqlalchemy providing error like cannot import name RelationshipProperty

While using sudo python setup.py install
Getting error like:
from sqlalchemy.orm.relationships import (RelationshipProperty,
ImportError: cannot import name RelationshipProperty

While using sudo python setup.py develop
ImportError: cannot import name RelationshipProperty
OilLibrary database generation returned: 1

How to solve this issue..
please Help!!!

**Comment by dharanidharan12** [comment]
**'NOAA oil library must be installed from: '
ImportError: NOAA oil library must be installed from: https://github.com/NOAA-ORR-ERD/OilLibrary**

I have Installed the OilLibrary already, from the OilLibrary folder, test result is success.
But can't able to get the OilLibrary from the opendrift folder. 
file name: **example_oil_budget_noaa.py**

What I did Wrong???

**Comment by knutfrode** [comment]
NOAA OilLibrary has changed in the meantime, so some things did not work anymore. I have now updated OpenDrift, so if you update to latest version it should work.

**Comment by HanhHelen** [comment]
Dear authors,
When I installed OilLibrary (on Win64) , I have the problems:
-Oillibrary database generation failed
-AttributeError: 'module' object has no attribute 'convert'
Would you please give me your hand?
