### ISSUE TITLE
Simulation with wind data from ERA5

### ISSUE THREAD

**Issue by IGanch** [OpenDrift/opendrift#385]
Hello!
I am trying to add some wind data from the Copernicus Climate ERA5 data sets for simulating oil spills. This doesn't work out very good as it doesn't recognize the variable name u10 and v10 as x_wind and y_wind. 
I tried renaming the variables in the NetCDF exactly as x_wind and y_wind and the reader still doesn't see them as valid wind data. Any suggestions how I could solve that? 
Cheers,
I.

**Comment by knutfrode** [comment]
Hi,

The variable names do not matter, it is their attribute `standard_name` which has to be `x_wind` and `y_wind`, respectively.
So you could add/modify their `standard_name`, or you may provide a mapping dictionary, as in this example:
https://opendrift.github.io/gallery/example_macondo.html

**Comment by IGanch** [comment]
This sounds like the solution I'd need, however I get the error:

`Traceback (most recent call last):
  File "BS_example_point-source_cur_OpenOil.py", line 20, in <module>
    reader_currents = reader_netCDF_CF_generic.Reader(r'C:\Users\path\to
file\07072018_430am-10072018_430am_cur-h.nc',standard_name_mapping={'eastward_sea_water_velocity':'x_sea_water_velocity', 'northward_sea_water_velocity':'y_sea_water_velocity'})
TypeError: __init__() got an unexpected keyword argument 'standard_name_mapping'`

Many thanks for your prompt reply!

**Comment by knutfrode** [comment]
This feature was introduced very recently. Could you try again after updating your code with `git pull`?

**Comment by IGanch** [comment]
Long story short - I don't have admin rights and still don't have git installed. 
However I installed opendrift with conda forge just this Wednesday, was it implemented later, or regardless the recent installation I still don't have the latest update?
Thanks!!

**Comment by IGanch** [comment]
So I solved the git pull issue and OpenDrift is up-to-date. The error has changed
`Traceback (most recent call last):
  File "BS_example_point-source_cur_OpenOil.py", line 51, in <module>
    o.run(duration=timedelta(hours=12), time_step=1800, time_step_output=3600)
  File "c:\users\paht'\here\opendrift\opendrift\models\basemodel.py", line 2047, in run
    raise ValueError('Readers must be added for the '
ValueError: Readers must be added for the following required variables: ['x_wind', 'y_wind']`
I added the reader by 
`reader_currents = reader_netCDF_CF_generic.Reader(r'C:\Users\...\currents\07072018_430am-10072018_430am_cur-h.nc', r'C:\Users\...\wind\07072018-10072018_4am-wind-h.nc',standard_name_mapping={'eastward_sea_water_velocity':'x_sea_water_velocity', 'northward_sea_water_velocity':'y_sea_water_velocity','10 metre U wind component':'x_wind', '10 metre V wind component':'y_wind'})`
Many thanks for your answer!

**Comment by knutfrode** [comment]
I believe you should replace '10 metre U wind component' (long name) with
'u10' (variable name) in your mapping dict.

**Comment by IGanch** [comment]
No, the same error comes with the variable names.

**Comment by IGanch** [comment]
Yes, this made it work. Thank you very much!
