### ISSUE TITLE
Stranding

### ISSUE THREAD

**Issue by John-Luick** [OpenDrift/opendrift#416]
Apparently some submodels have stranding and some do not. Plastdrift, for example, apparently does not. I had previously been using openoil, and that led me to assume that they all had stranding by default. Then, I used Plastdrift. I imported the output netcdf from Plastdrift and spent more time than I care to admit trying to work out why the seeds, which stranded with an openoil run, refused to strand in the same customised animation script I made for openoil. The netcdf file contains variables like "moving" which normally contain the stranding information, but which do not seem to have anything in the case of Plastdrift output. My question is, is there a switch for o.run that can turn on stranding in any submodule, or if not, which ones have stranding as a fallback (like openoil) and which do not? Note that I am not asking that stranding be added (I can live without it). Thanks, John

**Comment by knutfrode** [comment]
Yes, default coastline interaction is set independently for each model.
But you may override to desired behavior with ``set_config``, as explained here: https://opendrift.github.io/interaction_with_coastline.html

Btw, the `moving` attribute is not related to stranding (which rather deactivates particles), but e.g. to sediments which may become settled (moving=0), but later resuspended (moving=1).

**Comment by gauteh** [comment]
Closing this, please comment if issue is unsolved.
