### ISSUE TITLE
Issues with seed_from_shapefile

### ISSUE THREAD

**Issue by OakesHolland** [OpenDrift/opendrift#417]
Hi!

I am using opendrift to backtrack particles from Antarctic/subantarctic coastal sites with the OceanDrift module. I have run the code fine when using o.seed_elements with a 5km radius from a lat/lon location. However I would like to run these models again by seeding from some shapefiles I have created. 

So I tried this:

`o.seed_from_shapefile('D:/Data/GEBCO/AAT_Locations/macca_100_clip.shp',
                     number = 10000,
                     time=datetime(2020, 4, 15, 0, 0))`

And this is the output from that.....

13:47:45 INFO: Seeding for layer: macca_100_clip (1 features)
13:47:45 INFO: Total area of all polygons: 317191276.3961414 m2
13:47:45 INFO: 	Seeding 10000 elements within polygon number 1
13:47:45 INFO: At least three points needed to make a polygon

I'm not sure why it is saying that last line, the shapefiles I'm using are polygons?  It's not coming up with an error per se, but if I try to o.run() it says I haven't seeded anything. 

Would you have any ideas of why this is happening or any tips on how to fix it?

Thank you,
Oakes Holland
PhD Candidate
Queensland University of Technology

**Comment by knutfrode** [comment]
Hi. If you can make available this shapefile, then I can have a look.

**Comment by OakesHolland** [comment]
Thanks for the quick reply, I have attached.

[macca_100_clip.zip](https://github.com/OpenDrift/opendrift/files/5479401/macca_100_clip.zip)

Cheers,
Oakes

**Comment by knutfrode** [comment]
I get the same error.
Attached is a plot of your shapefile (from QGIS).
![shapefile](https://user-images.githubusercontent.com/5222051/97978554-00462e80-1dce-11eb-99c5-1d2e3482fdb8.png)
I don't think this shapefile will work, as it is not clear which contour to seed within.
Also there is a small "doughnut" to the south, which could make a problem.

If you are not able to fix this shapefile, an alternative is to use `seed_from_polygon`directly (`seed_from_shapefile` is a wrapper around this one).

**Comment by OakesHolland** [comment]
Thank you - I appreciate your help!  I'll look into it.

**Comment by knutfrode** [comment]
Closing this issue. Please re-open if still relevant.
