### ISSUE TITLE
Caspian modelling

### ISSUE THREAD

**Issue by Oklyagina** [OpenDrift/opendrift#426]
Dear all, 
I use OpenDrift (v 1.3.3) to study movement of particles in the Caspian Sea. In the Opendrift.run I get the following output: _Moving 100 out of 100 points from land to water; WARNING: No ocean pixels nearby, cannot move elements._ , though the seeding start coordinates are right in the middle of the sea (red point on picture)
![seed_problem](https://user-images.githubusercontent.com/64158084/98567516-161d8d00-22c1-11eb-8497-5663e19a4f87.PNG)
The same code works perfectly well for the Baltic sea. 
What might be the reason for this and how can I solve it?

**Comment by knutfrode** [comment]
I wonder if the problem is because Caspian is not recognised as a lake and not a Sea, and thus not treated as ocean by the landmask.
As a first step, can you please add this, before your seed-command:
``>>> o.set_config('seed:ocean_only', True)`` 

And you might also need to add:
``>>> o.set_config('general:use_auto_landmask', False)``

**Comment by Oklyagina** [comment]
Dear Knutfrode, thank you for the prompt answer.
I did that, but the warning is still here:
![seed_problem](https://user-images.githubusercontent.com/64158084/98572641-e7a2b080-22c6-11eb-979a-f0bad6b05826.PNG)

**Comment by knutfrode** [comment]
I am sorry, the first config should be False, not True:
``>>> o.set_config('seed:ocean_only', False)``

**Comment by Oklyagina** [comment]
I changed it to False. The warning about ocean pixels is gone, but the simulation still stops within the first time-step.

**Comment by knutfrode** [comment]
Ok, that is progress.

But then you need an ocean model which also contains a landmask. Did you add an ocean model reader to your simulation? If so, you can print this one to see if it also contains `land_binary_mask`.

If you do not have landmask available, then the last resort is to deactivate it, but then particles might move over land.
This is done by setting a fallback-value as 0 (ocean), which was done like this in version 1.3.3:
`>>> o.fallback_values['land_binary_mask'] = 0`
([After version 1.4.0](https://opendrift.github.io/history_link.html) this is instead done like this: `o.set_config('environment:fallback:land_binary_mask', 0)`)

Btw, you are adding a landmask-reader in your code above. This is normally not necessary, as it is added automatically when the simulation starts, unless you have specified `use_auto_landmask` to False.
So I think in this case, you should not add the landmask reader, as it apparently does anyway not work for the Caspian, and might be the reason for stop in first timestep.

**Comment by Oklyagina** [comment]
Dear Knutfrode, I removed the landmask reader, and now the simulation works! Thank you very much for your help.
