### ISSUE TITLE
Sedimentdrift

### ISSUE THREAD

**Issue by dpereiro91** [OpenDrift/opendrift#427]
Hi,

I have seen that the SedimentDrift model is still "under development". I was wondering what the current limitations are and if it is advisable to use it as it is right now. I have seen in the code that a proper stranding algorithm still needs to be implemented. Apart from this, sediment settlement and resuspension seems to be already implemented, so perhaps the model is already suitable to investigate areas of sediment deposition. To sum up, is it a good idea to use the model as it is right now or is it better to wait until further developments?

Thanks in advance for your help.

**Comment by knutfrode** [comment]
The new SedimentDrift model is just a very thin subclass of OceanDrift.
https://opendrift.github.io/_modules/opendrift/models/sedimentdrift.html#SedimentElement

One difference is that the default `terminal_velocity` is negative (sinking particles), but either model can be configured oppositely.
So the main addition is that SedimentDrift implements settling and resuspension.
Settling should be quite straightforward (deactivation (moving=0) when sinking to bottom), but the present implementation if resuspension is just a placeholder (activation, moving=1), with resuspension if current speed exceeds 5 cm/s.

So you may use the model, but keep in mind that the resuspension algorithm is not realistic.

I have no immediate plans to work on this model, but @simonweppe and @trondkr have done some work in their own forks.
