### ISSUE TITLE
Switching from PREVIOUS to STRANDING?

### ISSUE THREAD

**Issue by AndresSepulveda** [OpenDrift/opendrift#448]
Hi,

 We are interested in peagicegg case were the particle  changes their interaction with the coast from PREVIOUS to STRANDING after a defined time (namely once the larvae has developed).

 Is this possible in the current code? Has anyone tried a similar approach?

Regards,

Andrés

**Comment by knutfrode** [comment]
This is presently not possible, as coastline action is a general setting for the whole simulation.
It could probably be hacked somehow, but perhaps it is simpler to simply use PREVIOUS, and rather deactivate larvae (not eggs) when they hit land in your `update()` method?
```
self.deactivate_elements(self.environment.land_binary_mask==1 & self.elements.larvae==1, reason='stranded larvae')
```
(pseudo-code, not tested)

**Comment by AndresSepulveda** [comment]
Thanks, we will try that.

**Comment by knutfrode** [comment]
Closing this issue. Please re-open if still relevant.
