### ISSUE TITLE
Fixing environment fields

### ISSUE THREAD

**Issue by Oklyagina** [OpenDrift/opendrift#449]
Good evening,

I am given a .nc file with the following available time:
![image](https://user-images.githubusercontent.com/64158084/100635750-f1598a00-3341-11eb-8710-b9f2915dbb2c.png)
The OceanDrift model uses fields of temperatures, velocities, etc. from this file only for the first time step in the simulation. Particles are stuck on one place after this time step.

Is it possible to somehow fix these fields for the whole time of simulation, or maybe predict their values for future steps using OpenDrift?

**Comment by knutfrode** [comment]
You can write
`r.always_valid = True`
before starting the simulation, where `r` is the actual reader.

**Comment by Oklyagina** [comment]
Thanks a lot!
