### ISSUE TITLE
CROCO file - NameError: name 'Dataset' is not defined  when using gridfile to add lat and lon

### ISSUE THREAD

**Issue by AndresSepulveda** [OpenDrift/opendrift#450]
Hi,

I am getting this error when using the reader_ROMS_native with a  CROCO file and its grid file

`(new_opendrift) matlab@debian:~/new_opendrift$ python3 deriva_ancud_tv.py
Vtransform not found, using 1
Traceback (most recent call last):
  File "deriva_ancud_tv.py", line 15, in <module>
    nordic_native = reader_ROMS_native.Reader('/data1/matlab/IFOP_TV/roms_avg_2018.nc',gridfile='/data1/matlab/IFOP_TV/roms_MIC_grd_v8b.nc')
  File "/home/matlab/new_opendrift/opendrift/opendrift/readers/reader_ROMS_native.py", line 160, in __init__
    gf = Dataset(gridfile)
NameError: name 'Dataset' is not defined
`

Is there a missing variable or a misnamed variable in the grid file?

**Comment by knutfrode** [comment]
It seems like line 160 has not been adapted to using Xarray instead of python-netCDF.
I believe you can change this line to:
```gf = xr.open_dataset(gridfile)```

If you confirm that this works, I can commit the change to master branch.

**Comment by AndresSepulveda** [comment]
Well, it works.  

But now,  a new issue arises: nothing happens. Even with loglevel=0 the only screen output is

`(new_opendrift) matlab@debian:~/new_opendrift$ python3 deriva_ancud_tv.py
Vtransform not found, using 1
01:49:37 DEBUG   root: Nothing to prepare for roms native`

I am using the attached code. u and v values look ok.

![ancud](https://user-images.githubusercontent.com/8628027/100699087-ccccd480-3378-11eb-8658-558977f7d341.png)

[deriva_ancud_tv.py.txt](https://github.com/OpenDrift/opendrift/files/5620360/deriva_ancud_tv.py.txt)

**Comment by knutfrode** [comment]
A new logger module has ben introduced. Perhaps you need to update environment once more:

conda env update -f environment.yml

**Comment by AndresSepulveda** [comment]
I did that but the screen output is still very limited.  With another CROCO file that was used succesfully I get the particles to move, but still no screen output, only things releated to the plotting step, even with o = OceanDrift(loglevel=0) 

Is the debuggin output directed to another place/file?

(new_opendrift) matlab@debian:~/new_opendrift$ python3 deriva_ancud_tv.py
09:53:30 DEBUG   root: Nothing to prepare for roms native
Invalid values (-10.384449 to -10.384449) found for x_sea_water_velocity, replacing with NaN
(allowed range: [-10, 10])
09:54:21 DEBUG   matplotlib.font_manager: findfont: Matching sans\-serif:style=normal:variant=normal:weight=normal:stretch=normal:size=10.0.
....

**Comment by gauteh** [comment]
Hi, can you run `git describe --tags --always` in the repository of opendrift? Are you sure you are using latest master? Note that we have made some fundamental changes to readers recently so there might be some instabilities on master yet.

When I run your example script I get the following output:
```
❯ python deriva_ancud_tv.py
14:43:24 DEBUG   opendrift: Adding 17 config items from basemodel
14:43:24 DEBUG   opendrift: Adding 4 config items from basemodel
14:43:24 DEBUG   opendrift: Adding 34 config items from basemodel
14:43:24 INFO    opendrift: OpenDriftSimulation initialised (version 1.4.2)
14:43:24 DEBUG   opendrift: Adding 13 config items from oceandrift
14:43:24 DEBUG   opendrift:   Overwriting config item seed:z
14:43:24 INFO    opendrift.readers.reader_ROMS_native: Opening dataset: /data1/matlab/IFOP_TV/roms_avg_2018.nc
14:43:24 INFO    opendrift.readers.reader_ROMS_native: Opening file with Dataset
... lots of errors due to missing files ...
```

**Comment by AndresSepulveda** [comment]
This is what I get

(new_opendrift) matlab@debian:~/new_opendrift/opendrift$ git describe --tags --always
v1.4.2-64-g2defb90

**Comment by gauteh** [comment]
This is a bit weird. Do you get log output if you run e.g.
example_leeway.py? It seems that `coloredlogs` is installed, but could you
make sure with `conda list`? You are not re-directing output anywhere? If
you just run `python` and type in yourself:

from opendrift.models.leeway import Leeway
o = Leeway(loglevel=0)

what output do you get? Otherwise it might also be worth fetching the
latest changes from opendrift and also maybe make a new environment if you
did not already. Make sure you use `pip install -e .` with the `-e` when
installing.

tir. 1. des. 2020 kl. 15:03 skrev Andres Sepulveda <notifications@github.com

**Comment by knutfrode** [comment]
There has recently been some updates and fixes to the logging.
Could you see if this problem still persists with the latest version (1.5.3)?

**Comment by AndresSepulveda** [comment]
I did 

(new_opendrift) matlab@debian:~/new_opendrift/opendrift$ conda env update -f environment.yml

and got

Collecting package metadata (repodata.json): done
Solving environment: done

Downloading and Extracting Packages
pygrib-2.1.3         | 240 KB    | ################################################################# | 100%
cartopy-0.18.0       | 1.9 MB    | ################################################################# | 100%
coloredlogs-15.0     | 62 KB     | ################################################################# | 100%
requests-2.25.1      | 51 KB     | ################################################################# | 100%
oil_library-opendrif | 2.0 MB    | ################################################################# | 100%
ffmpeg-4.3.1         | 91.9 MB   | ################################################################2 |  99% ffmpeg-4.3.1         | 91.9 MB   | ################################################################# | 100%
numpy-1.19.5         | 5.4 MB    | ################################################################# | 100%
pytest-6.2.1         | 432 KB    | ################################################################# | 100%
pip-20.3.3           | 1.1 MB    | ################################################################# | 100%
ca-certificates-2020 | 137 KB    | ################################################################# | 100%
future-0.18.2        | 712 KB    | ################################################################# | 100%
certifi-2020.12.5    | 143 KB    | ################################################################# | 100%
netcdf4-1.5.5.1      | 560 KB    | ################################################################# | 100%
xhistogram-0.1.2     | 17 KB     | ################################################################# | 100%
scipy-1.6.0          | 20.6 MB   | ################################################################# | 100%

afterwards I did
(new_opendrift) matlab@debian:~/new_opendrift/opendrift$ git describe --tags --always
v1.4.2-64-g2defb90

So seems I am still in 1.4.2

but the particles are moving now!

![ancud](https://user-images.githubusercontent.com/8628027/104790128-71627480-5775-11eb-9ed8-045355a0ae0a.png)

**Comment by gauteh** [comment]
Closing, please re-open if needed.
