### ISSUE TITLE
Thredd Import

### ISSUE THREAD

**Issue by Nichsouz** [OpenDrift/opendrift#499]
Hello,

I am trying to import 0.25 NCEP data from the following thredd https://rda.ucar.edu/thredds/catalog/files/g/ds084.1/2020/20200101/catalog.html 
but no success. 

I have also tried downloading .nc and .grib2 files to import "manually" into opendrift, but no success too. How can I do that?  

Regards,

**Comment by knutfrode** [comment]
If these are stores as GRIB-files behind the Thredds server, e.g. `standard_name` attributes might not be CF_compliant.
However, the OpenDAP-server at your URL seems to be password protected, and so I cannot test it.

If you have downloaded GRIB files, you might try if `reader_grib2` works:
https://github.com/OpenDrift/opendrift/blob/master/opendrift/readers/reader_grib2.py

If you have downloaded netCDF files which do not work, you could try to add `standard_name_mapping` as in this example:
https://opendrift.github.io/gallery/example_macondo.html
Mapping is from `variable name` (e.g. `u10`, `v10`) -> `standard_name` (e.g. `x_wind`, `y_wind`)

If that does also not work, please post the output from ncdump of the file.

**Comment by gauteh** [comment]
Closing, please re-open if needed.
