### ISSUE TITLE
module not found

### ISSUE THREAD

**Issue by AndresSepulveda** [OpenDrift/opendrift#54]
Hi, I have the following problem. If I do

mosa@parti-mosa:~/opendrift/tests$ python test_netcdf.py
Traceback (most recent call last):
  File "test_netcdf.py", line 22, in <module>
    from opendrift.readers import reader_ROMS_native
ImportError: No module named opendrift.readers

the module is not found.

However, from the command line, in python itself, it works

mosa@parti-mosa:~/opendrift$ python
Python 2.7.14 |Anaconda, Inc.| (default, Oct 16 2017, 17:29:19) 
[GCC 7.2.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import unittest
>>> 
>>> from opendrift.readers import reader_ROMS_native
>>> 

Seems there is some configuration missing. 

[UPDATE] The previous case work from the opendrift directory, but not while in opendrift/eamples or other places

The testall script seems to work, ends like this:

Ran 68 tests in 30.658s

OK (skipped=5)

**Comment by knutfrode** [comment]
It appears that ```PYTHONPATH``` is not set, and thus it only works when you are located within the opendrift-folder.
```PYTHONPATH``` should be set to point at the opendrift-folder when you run setup.py, but it can also be set manually, e.g. in .bashrc for Linux.
