### ISSUE TITLE
Translation ?

### ISSUE THREAD

**Issue by AndresSepulveda** [OpenDrift/opendrift#56]
Is there an easy way to change the language of the labels ("initial","stranded","active"). I could help with the terms in spanish!

**Comment by knutfrode** [comment]
There is no support for language translation. So you would have to both edit the configuration in basemodel.py:
https://github.com/OpenDrift/opendrift/blob/master/opendrift/models/basemodel.py#L115
and also edit the parts in the code where the respective config settings are used, e.g.
https://github.com/OpenDrift/opendrift/blob/master/opendrift/models/basemodel.py#L354

But in your application/wrapper you could make some mapping from spanish to english terms.
