### ISSUE TITLE
The problem with setting the ‘mass_oil‘

### ISSUE THREAD

**Issue by yaosailor** [OpenDrift/opendrift#564]
**Problem description:** When I was using the OpenOil module, setting the number of mass_oil was invalid.
**My code:**
`o.seed_elements(lon=lon_p, lat=lat_p, radius=100, number=2000, time=time, z=0,
                mass_oil=250.0, oiltype='HEAVY DISTILLATE MARINE ECA 50 2017')`
But in the result file(.nc), the variable 'mass_oi' is initially a constant of 0.451915.
`# num_elements=2000 m3_per_hour=1.0 duration_hours=1.0, kwargs['density']=903.8315 `
`        kwargs['mass_oil'] = (m3_per_hour*duration_hours/
                              num_elements*kwargs['density'])`

I think this part of the code causing the kwargs['mass_oil'] to be overwritten. [https://github.com/OpenDrift/opendrift/blob/da6bfa0417f13cf91ed373f8a91b19d44ef16f22/opendrift/models/openoil.py#L1318](url) 

I made this challenge for a while:
`  
      # kwargs['mass_oil'] = (m3_per_hour * duration_hours /
      #                       num_elements * kwargs['density'])
`
`    
        if 'mass_oil' not in kwargs:
            kwargs['mass_oil'] = (m3_per_hour * duration_hours /
                                  num_elements * kwargs['density'])
`

That’s it, I don’t know if I understand it correctly.

**Comment by knutfrode** [comment]
Documentation is lacking on this point, but `mass_oil` is an internal parameter (mass of oil per element) which is not supposed to be set by the user.
Instead you should use only `m3_per_hour`, which is the oil volume released per hour, or the total volume if seeded at a single time.

**Comment by yaosailor** [comment]
> Documentation is lacking on this point, but `mass_oil` is an internal parameter (mass of oil per element) which is not supposed to be set by the user.
> Instead you should use only `m3_per_hour`, which is the oil volume released per hour, or the total volume if seeded at a single time.

Thank you for your response！
