### ISSUE TITLE
Shipdrift grb files not working

### ISSUE THREAD

**Issue by dharanidharan12** [OpenDrift/opendrift#57]
how to make shipdrift work with grb files.
I Having grb files related to wind and current.
Please Help!!
Thanks in Advance!!!

**Comment by dharanidharan12** [comment]
**o = ShipDrift(loglevel=0)**
No movement of objects while using grb files in shipdrift

**o.add_readers_from_list(['/home/dharani/chennaisearch/static/test_data/chennaicoast/2017-11-13/gfs20171113050500667.grb','/home/dharani/chennaisearch/static/test_data/chennaicoast/2017-11-13/RTOFS-ATL20171113061101347.grb'])**
No effect of wind and current .
Why???
Please HELP!!!
Thanks in Advance!!!

**Comment by knutfrode** [comment]
The method add_readers_from_list only works for netCDF CF files/URLs.
For grib-files, you will have to create and add readers manually, as in
most of the example scripts.
