### ISSUE TITLE
Error "Geometry must be a Point or LineString" with `example_long_cmems.py`

### ISSUE THREAD

**Issue by ctroupin** [OpenDrift/opendrift#572]
Hello,

I'm running the example `example_long_cmems.py`.
The run was successful but when I run the command:
```python
o.animation(fast=True, clabel='Tidal current [m/s]', skip=1, scale=20, background=[ 'sea_ice_x_velocity', 'sea_ice_y_velocity'])
```
I got the following messages:
```python
09:07:16 WARNING opendrift.models.basemodel: Plotting fast. This will make your plots less accurate.
Geometry must be a Point or LineString
python3.8: geos_ts_c.cpp:3991: int GEOSCoordSeq_getSize_r(GEOSContextHandle_t, const geos::geom::CoordinateSequence*, unsigned int*): Assertion `0 != cs' failed.
Aborted (core dumped)
```

### Installation
* Linux Ubuntu
* Python 3.8
* oil-library 1.1.3
* OpenDrift 1.5.6
* opendrift-landmask-data 0.8

**Comment by knutfrode** [comment]
This example including the animation worked well for me now.
Did you install requirements using conda?
If so, perhaps you could try to update with:

```
$ conda activate
$ conda env remove -n opendrift
$ conda env create -f environment.yml  # from opendrift main folder
```

Do other examples with animations and background vector field show the same problem? You could e.g. try this one:
https://opendrift.github.io/gallery/example_leeway.html

**Comment by ctroupin** [comment]
Yes maybe that's the problem:
I installed with `pip` (trying not to mix up `pip` and `conda` installation) and everything was fine (except the plotting part).

So I'll start a fresh installation with conda is that can solve the problem.

Thanks!
