### ISSUE TITLE
Wind reanalysis reader

### ISSUE THREAD

**Issue by John-Luick** [OpenDrift/opendrift#574]
I wonder if I am missing something. I see several built-in readers for wind products like NCEP, AROME, and MEP, but none of their URLS or pathnames refer to any global wind data prior to 2020. My solution was to download ECMWF ERA5 data to my local drive, and write a little script that converts it to something the netcdf_CF_generic reader was happy with (admittedly, I just assumed netcdf_CF_generic would balk at the raw ERA5 data). So, is there a reader for reading older wind reanalysis data directly from ECMWF, NCEP, or anywhere? I mean globally, not somewhere off Svalbard.

That was my main question, but I will add an observation. The first time I tested OpenDrift with the converted data it did not apply wind forcing to the tracers. Luckily, I had print statements for both the wind data and the current data, which prints the corner lats and lons, which made it clear my convention for ordering the arrays in netcdf was different from what OpenDrift expected. When I changed to the array convention used by the AROME netcdf data, everything was fine and the wind blew the tracers as expected. I will go with it, but I have to say the AROME convention is not what I consider normal. Or maybe it's just me?
     
I'm happy to share my convert script if anybody wants it. But beware, it is matlab!

**Comment by knutfrode** [comment]
Hi,

The [readers](https://github.com/OpenDrift/opendrift/tree/master/opendrift/readers) themselves are linked to specific data formats (e.g. netCDF CF convention, netCDF unstructured, GRIB etc), and are independent of the models and coverage in time and space ("data sources").
So I assume you are instead referring here to the available list of data sources, which is used e.g. by the built-in GUI:
https://github.com/OpenDrift/opendrift/blob/master/opendrift/scripts/data_sources.txt

Some in this (priority) list are high-resolution datasets mainly covering the North-Atlantic, but some later in the list are global, e.g. NCEP, Hycom and Mercator.
As the GUI is mainly used for near-real-time short-time simulations for contingency/emergency, historical/reanalysis data are here of less relevance, but anyway I am not aware of many such datasets that are available via thredds.

So for historical simulations, you would have to do what you have done, namely to download/obtain files to local disk.
ERA-data should work with the netCDF-generic reader if they are [CF-compliant](https://cfconventions.org/).
If some `standard_name` are wrong or missing, you can apply a mapping as in this example:
https://opendrift.github.io/gallery/example_macondo.html

The order of the dimensions should also follow the CF-convention, namely: `[time], [depth], lat, lon`
where `time` and `depth` are optional (only for time-varying, or depth-varying variables), and `lat, lon` may be `y, x` for the case where projection is not Plate Carrée.
I think most available datasets follow this convention, although personally I think `x, y` / `lon, lat` would have been more natural.

**Comment by John-Luick** [comment]
Thank you for your very informative reply. The historic CMEMS data downloaded (using a python script) on my local drive can be read by reader_netcdf_CF_generic, but the historic ECMWF data downloaded (using the ECMWF GUI) on my local drive seems to need to be converted to CF (I could not get it to work using variable_mappings). By the way, one oddity of the ECMWF (ERA5) data is that wind and wave data must be downloaded separately. It will happily serve you a netcdf file with both wind and wave data, but the lats and lons apply correctly only to the wind data. The wave data is on a 2X coarser grid, so that the lats and lons don't apply correctly. I have reported this to them. It isn't obvious unless you are close to land.

Regarding the AROME data in the testdata folder, I just found it odd because the arrays are not in the usual order I normally expect when I ncread them into Matlab. For example the 2D latitude array has latitude increasing columnwise. This may be unique to my own methods and/or thinking. As long as the data corresponds, it should not matter.

Thank you again.

**Comment by John-Luick** [comment]
I will close this off now. But first, in case anyone is using the ERA data on different grids, ECMWF responded to my report, by saying that yes, if downloading netcdf from their website, variables with different resolutions (on different grids) should be downloaded separately to avoid the problem I described.
