### ISSUE TITLE
No legend labels in examples

### ISSUE THREAD

**Issue by EmmaCartuyvels** [OpenDrift/opendrift#59]
Hi all,

When running most of the examples (except those for OilSpil) I get the following warning:

UserWarning: No labelled objects found. Use label='...' kwarg on individual plots.
  warnings.warn("No labelled objects found. "

I'm relatively new to python, so maybe there is a simple solution to this but I haven't found it so far.

Thanks for any help!

**Comment by knutfrode** [comment]
Hi,

This should be no problem, it is just indicating that there is no text legend requested for those figures. The warning message apparently shows up for some versions of matplotlib o.a.

As long as the ```testall``` script returns no errors, you should be fine.

**Comment by EmmaCartuyvels** [comment]
Hi,
Thanks for your quick reply!
It is the only error it gives, still there is no plot or animation appearing.

**Comment by knutfrode** [comment]
The ```testall``` script gives no plots, it just checks that various calculations and simulations give results as expected.

The examples in the example-folder all ends by showing some animations and plots. Hopefully also in your case?

**Comment by EmmaCartuyvels** [comment]
No, only in the OilSpil examples.

**Comment by knutfrode** [comment]
Ok. Can you first update your code to the latest version ("git pull" if using git) and then check whether these two examples display animations at the end or not:
```example.py```  (using oil drift model)
```example_verticalmixing.py```  (using pelagic egg drift model)

**Comment by EmmaCartuyvels** [comment]
example.py gives an animation and map
example_verticalmixing.py gives nothing
I only downloaded yesterday, so that should be the latest version, rigth?

**Comment by knutfrode** [comment]
Ok. What is your operating system?

And what is the output you get from these Python commands?
```
>>> import os
>>> print os.environ.get('DISPLAY','')
```

**Comment by EmmaCartuyvels** [comment]
I'm using Pycharm on Anaconda.
I don't seem te be getting any output when running these commands.
Thanks for helping me with this!

**Comment by AndresSepulveda** [comment]
Both examples work fine with me. The last one produces two animations.

**Comment by knutfrode** [comment]
Ok, that is good to know Andres. What do you get from
```
>>> import os
>>> print os.environ.get('DISPLAY','')
```
In my case it returns ```':0'```

Emma: are you using Linux, Max or Windows operating system?

**Comment by EmmaCartuyvels** [comment]
Windows

**Comment by ctroupin** [comment]
Hi all,
I'm trying the same examples with Linux and PyCharm editor, no animation is generated so maybe related to the editor.

**Comment by knutfrode** [comment]
You might be right, ctroupin. I am not familiar with PyCharm, but googling indicates that it gives issues with environment variables, e.g.:
https://stackoverflow.com/questions/42708389/how-to-set-environment-variables-in-pycharm

Perhaps you can try to set the ```DISPLAY``` variable to ```:0```

The issue here seems to be that as the ```DISPLAY``` variable is not set, OpenDrift assumes that this is a non-interactive session, and uses a backend which may produce graphical files ('agg'), but nothing to screen.

**Comment by knutfrode** [comment]
I am now letting OpenDrift check if run within PyCharm, and in this case using a backend which may produce figures: https://github.com/OpenDrift/opendrift/commit/4215aaf4c45847d76f8337da8233bafeacb7f75b

https://stackoverflow.com/questions/29777737/how-to-check-if-python-unit-test-started-in-pycharm-or-not

So please update your OpenDrift code, and try if it works now.

**Comment by EmmaCartuyvels** [comment]
It works! Thank you so much!
Just one more question, I'm sure this one is on me, but I'm trying to read in .nc data and I'm struggeling to import it. It's from the Copernicus website.

20171122_d-INGV--RFVL-MFSeas2-MEDATL-b20171115_fc-sv03.00

**Comment by knutfrode** [comment]
If you can make available a sample of such a file, I can have a look.

2017-11-17 10:12 GMT+01:00 EmmaCartuyvels <notifications@github.com>:

**Comment by EmmaCartuyvels** [comment]
I've put some files on this google drive:

https://drive.google.com/open?id=1a6CJPg41GH5PuwZSfSZtwWE39Psz1wDa

**Comment by knutfrode** [comment]
For the first of these files (20171122_d-INGV--RFVL-MFSeas2-MEDATL-b20171115_fc-sv03.00.nc) I am getting the error ```RuntimeError: NetCDF: HDF error```

But for the other files it works well. Perhaps the file from 22nd Nov is corrupt? If so, you might try to download it once again.

The suitability of a file may be checked from commandline (not sure if it works on Windows/DOS?) like this:
```$ readerinfo.py 20171123_d-INGV--RFVL-MFSeas2-MEDATL-b20171115_fc-sv03.00.nc -p```

**Comment by EmmaCartuyvels** [comment]
I've managed to get in the files. Is there any way to see which variables your model has taken from the data and which ones are default?

**Comment by knutfrode** [comment]
Which variables which can be provided by a specific file/reader, can be seen by printing the reader object (```print <reader>```), as described here:
https://github.com/OpenDrift/opendrift/wiki/How-to-run-a-trajectory-simulation#2-adding-readers

After adding reader(s) to a simulation instance ```o```, printing the instance (```print o```) will show which variables are provided by which readers, and which will receive fallback (default) values.
If there are several readers providing the same variables, these will be taken in the order that the readers were added (as backup if outside the spatial or temporal coverage of the first reader(s))

In your case, the files cover a single timestep, and these can be merged together in a single reader by using wildcards  (* or ?) in the filenames, e.g.
```
>>> r = reader_netCDF_CF_generic('2017*_d-INGV--RFVL-MFSeas2-MEDATL-b20171115_fc-sv03.00.nc')
>>> print r
```
