### ISSUE TITLE
Doubt with landmask

### ISSUE THREAD

**Issue by oartal** [OpenDrift/opendrift#619]
Hi everyone

I'm a new user of opendrift. I'm using outputs from croco model for the particle simulation. My doubt is the following: I'm want use the landmask of my model for the animation and the figure, but finally adding the gshhs. Exist a form of ploting only my mask? This is my code.

o.set_config('general:use_basemap_landmask', 'false')
o.plot (background='land_binary_mask', filename ='figure.png')
o.animation(background='land_binary_mask',fast=True,color='z',filename='video.mp4')

Thanks in advance

**Comment by knutfrode** [comment]
Hi,

Your code should be ok, except that the config with basemask is outdated. Instead this should be:
```
o2.set_config('general:use_auto_landmask', False)
```

Se the animation/plot at the end of this example:
https://opendrift.github.io/gallery/example_model_landmask.html

**Comment by oartal** [comment]
Thanks you, it worked perfectly .

**Comment by josefilho77** [comment]
Hi Knut Frode and all,

I will bounce this issue because I am having some strange behavior of my particles when I run ut along my custom land_binary_mask.

It runs ok following the model_landmask example, but there is some strange stranding and deactivation of particles. Take a look:

https://user-images.githubusercontent.com/59928324/118262653-9220a980-b48b-11eb-8c1a-269eb1b29a13.mp4

Positions are marked in this one:
![t1](https://user-images.githubusercontent.com/59928324/118263068-2ab72980-b48c-11eb-997c-a2579b0ee921.png)


It is really strange a bunch of particles are stopping in the middle of the ocean (depth ~ 20m)

Do you have any idea what could be causing that?


Best regards,

**Comment by knutfrode** [comment]
Hi,

The plot says that 2483 particles are deactivated due to `missing_data`
Can you check the log what is the reason for this?
Perhaps you can also post a time-step or two from the log.

**Comment by josefilho77** [comment]
Sure. Until 51st step it returns timestep logs like this:

**Comment by knutfrode** [comment]
I think the elements are deactivated since they are leaving your area, which is ok.

However, I see from the log that z is positive (between 0 and 48.6m), but z has to be negative in the ocean.
So you probably has the wrong sign of z in your seeding method.

**Comment by josefilho77** [comment]
Hi Knut Frode, I managed to fiz the issue with Z location being negative...however, it still stranding in some random locations along my domain, as you can see on the figures:

![00wind_i](https://user-images.githubusercontent.com/59928324/118507144-56444900-b704-11eb-9b4e-94c92145c48b.png)


https://user-images.githubusercontent.com/59928324/118507235-6ceaa000-b704-11eb-8921-d7832ca32bb2.mp4


Do you think that is normal? For me, seems strange...

please, Take a look at two timesteps again:

11:42:03 INFO    opendrift.models.basemodel: 2013-07-15 02:00:00 - step 5 of 720 - 30793 active elements (927 deactivated)
11:42:03 DEBUG   opendrift.models.basemodel: 0 elements scheduled.
11:42:03 DEBUG   opendrift.models.basemodel: ======================================================================
11:42:03 DEBUG   opendrift.models.basemodel: ----------------------------------------
11:42:03 DEBUG   opendrift.models.basemodel: Variable group ['sea_floor_depth_below_sea_level', 'x_sea_water_velocity', 'y_sea_water_velocity', 'upward_sea_water_velocity', 'land_binary_mask']
11:42:03 DEBUG   opendrift.models.basemodel: ----------------------------------------
11:42:03 DEBUG   opendrift.models.basemodel: Calling reader E:\Doutorado_Geoc_UFPE\Simula_Final\Netcdfs\00wind_i.nc
11:42:03 DEBUG   opendrift.models.basemodel: ----------------------------------------
11:42:03 DEBUG   opendrift.models.basemodel: Data needed for 30793 elements
11:42:03 DEBUG   opendrift.readers.basereader.variables: Fetching variables from E:\Doutorado_Geoc_UFPE\Simula_Final\Netcdfs\00wind_i.nc
11:42:03 DEBUG   opendrift.readers.basereader.structured: Reader time:
		2013-07-15 02:00:00 (before)
		2013-07-15 02:30:00 (after)
11:42:03 DEBUG   opendrift.readers.basereader.variables: Checking x_sea_water_velocity for invalid values
11:42:03 DEBUG   opendrift.readers.basereader.variables: Checking y_sea_water_velocity for invalid values
11:42:03 DEBUG   opendrift.readers.basereader.variables: Checking land_binary_mask for invalid values
11:42:03 DEBUG   opendrift.readers.interpolation.structured: Nearest interpolation will be used for landmask, and linearNDFast for other variables
11:42:03 DEBUG   opendrift.readers.basereader.structured: Fetched env-block (size 1329x1500x1) for time before (2013-07-15 02:00:00)
11:42:03 DEBUG   opendrift.readers.basereader.structured: Interpolating before (2013-07-15 02:00:00) in space  (linearNDFast)
11:42:03 DEBUG   opendrift.readers.interpolation.structured: Initialising interpolator.
11:42:03 DEBUG   opendrift: NaN values for 501 elements, expanding data 1
11:42:03 DEBUG   opendrift: NaN values for 171 elements, expanding data 2
11:42:04 DEBUG   opendrift: NaN values for 75 elements, expanding data 3
11:42:04 DEBUG   opendrift: NaN values for 39 elements, expanding data 4
11:42:04 DEBUG   opendrift: NaN values for 26 elements, expanding data 5
11:42:04 DEBUG   opendrift.readers.basereader.structured: No time interpolation needed - right on time.
11:42:04 DEBUG   opendrift.readers.basereader.variables: Reader projection is latlon - rotation of vectors is not needed.
11:42:04 DEBUG   opendrift.models.basemodel: Obtained data for all elements.
11:42:04 DEBUG   opendrift.models.basemodel: ---------------------------------------
11:42:04 DEBUG   opendrift.models.basemodel: Finished processing all variable groups
11:42:04 DEBUG   opendrift.models.basemodel: Creating empty dictionary for profiles not profided by any reader: ['ocean_vertical_diffusivity']
11:42:04 DEBUG   opendrift.models.basemodel:       Using fallback value 0 for ocean_vertical_diffusivity for all profiles
11:42:04 DEBUG   opendrift.models.basemodel: ------------ SUMMARY -------------
11:42:04 DEBUG   opendrift.models.basemodel:     x_sea_water_velocity: -0.100408 (min) 0.513964 (max)
11:42:04 DEBUG   opendrift.models.basemodel:     y_sea_water_velocity: -0.310906 (min) 0.328978 (max)
11:42:04 DEBUG   opendrift.models.basemodel:     x_wind: 0 (min) 0 (max)
11:42:04 DEBUG   opendrift.models.basemodel:     y_wind: 0 (min) 0 (max)
11:42:04 DEBUG   opendrift.models.basemodel:     upward_sea_water_velocity: -0.00279549 (min) 0.00663046 (max)
11:42:04 DEBUG   opendrift.models.basemodel:     ocean_vertical_diffusivity: 0 (min) 0 (max)
11:42:04 DEBUG   opendrift.models.basemodel:     sea_surface_wave_significant_height: 0 (min) 0 (max)
11:42:04 DEBUG   opendrift.models.basemodel:     sea_surface_wave_stokes_drift_x_velocity: 0 (min) 0 (max)
11:42:04 DEBUG   opendrift.models.basemodel:     sea_surface_wave_stokes_drift_y_velocity: 0 (min) 0 (max)
11:42:04 DEBUG   opendrift.models.basemodel:     sea_surface_wave_period_at_variance_spectral_density_maximum: 0 (min) 0 (max)
11:42:04 DEBUG   opendrift.models.basemodel:     sea_surface_wave_mean_period_from_variance_spectral_density_second_frequency_moment: 0 (min) 0 (max)
11:42:04 DEBUG   opendrift.models.basemodel:     surface_downward_x_stress: 0 (min) 0 (max)
11:42:04 DEBUG   opendrift.models.basemodel:     surface_downward_y_stress: 0 (min) 0 (max)
11:42:04 DEBUG   opendrift.models.basemodel:     turbulent_kinetic_energy: 0 (min) 0 (max)
11:42:04 DEBUG   opendrift.models.basemodel:     turbulent_generic_length_scale: 0 (min) 0 (max)
11:42:04 DEBUG   opendrift.models.basemodel:     sea_floor_depth_below_sea_level: 0 (min) 49.547 (max)
11:42:04 DEBUG   opendrift.models.basemodel:     land_binary_mask: 0 (min) 1 (max)
11:42:04 DEBUG   opendrift.models.basemodel: ---------------------------------
11:42:04 DEBUG   opendrift.models.basemodel: 		30793 active elements
11:42:04 DEBUG   opendrift.models.basemodel: 		-8.210523047951744 <- latitude  -> -7.598478306881474
11:42:04 DEBUG   opendrift.models.basemodel: 		-34.92047956282539 <- longitude -> -34.6118805023541
11:42:04 DEBUG   opendrift.models.basemodel: 		z = 0.0
11:42:04 DEBUG   opendrift.models.basemodel: ---------------------------------
11:42:04 DEBUG   opendrift.models.physics_methods: Calculating Hs from wind, min: 0.000000, mean: 0.000000, max: 0.000000
11:42:04 DEBUG   opendrift.models.physics_methods: Calculating wave period Tm02 from wind
11:42:04 DEBUG   opendrift.models.physics_methods:    min: 1.256637, mean: 1.256637, max: 1.256637
11:42:04 DEBUG   opendrift.models.physics_methods: Calculating wave period from wind, min: 1.256637, mean: 1.256637, max: 1.256637
11:42:04 DEBUG   opendrift.models.basemodel: 127 elements scheduled for deactivation (stranded)
11:42:04 DEBUG   opendrift.models.basemodel: 	(z: 0.000000 to 0.000000)
11:42:04 DEBUG   opendrift.models.basemodel: No elements hit seafloor.
11:42:04 DEBUG   opendrift.models.basemodel: Removed 127 elements.
11:42:04 DEBUG   opendrift.models.basemodel: Removed 127 values from environment.
11:42:04 DEBUG   opendrift.models.basemodel: remove items from profile for z
11:42:04 DEBUG   opendrift.models.basemodel: remove items from profile for ocean_vertical_diffusivity
11:42:04 DEBUG   opendrift.models.basemodel: Removed 127 values from environment_profiles.
11:42:04 DEBUG   opendrift.models.basemodel: Calling OceanDrift.update()
11:42:04 DEBUG   opendrift.models.physics_methods: No wind for wind-sheared ocean drift
11:42:04 DEBUG   opendrift.models.physics_methods: No Stokes drift velocity available
11:42:04 DEBUG   opendrift.models.oceandrift: No vertical advection for elements at surface
11:42:04 DEBUG   opendrift.models.basemodel: Horizontal diffusivity is 0, no random walk.
11:42:04 DEBUG   opendrift.models.basemodel: 30666 active elements (1054 deactivated)
11:42:04 DEBUG   opendrift.models.basemodel: to be seeded: 0, already seeded 31720
11:42:04 DEBUG   opendrift.models.basemodel: No elements hit seafloor.
#####
11:43:09 INFO    opendrift.models.basemodel: 2013-07-15 16:00:00 - step 33 of 720 - 28483 active elements (3237 deactivated)
11:43:09 DEBUG   opendrift.models.basemodel: 0 elements scheduled.
11:43:09 DEBUG   opendrift.models.basemodel: ======================================================================
11:43:09 DEBUG   opendrift.models.basemodel: ----------------------------------------
11:43:09 DEBUG   opendrift.models.basemodel: Variable group ['sea_floor_depth_below_sea_level', 'x_sea_water_velocity', 'y_sea_water_velocity', 'upward_sea_water_velocity', 'land_binary_mask']
11:43:09 DEBUG   opendrift.models.basemodel: ----------------------------------------
11:43:09 DEBUG   opendrift.models.basemodel: Calling reader E:\Doutorado_Geoc_UFPE\Simula_Final\Netcdfs\00wind_i.nc
11:43:09 DEBUG   opendrift.models.basemodel: ----------------------------------------
11:43:09 DEBUG   opendrift.models.basemodel: Data needed for 28483 elements
11:43:09 DEBUG   opendrift.readers.basereader.variables: Fetching variables from E:\Doutorado_Geoc_UFPE\Simula_Final\Netcdfs\00wind_i.nc
11:43:09 DEBUG   opendrift.readers.basereader.structured: Reader time:
		2013-07-15 16:00:00 (before)
		2013-07-15 16:30:00 (after)
11:43:10 DEBUG   opendrift.readers.basereader.variables: Checking x_sea_water_velocity for invalid values
11:43:10 DEBUG   opendrift.readers.basereader.variables: Checking y_sea_water_velocity for invalid values
11:43:10 DEBUG   opendrift.readers.basereader.variables: Checking land_binary_mask for invalid values
11:43:10 DEBUG   opendrift.readers.interpolation.structured: Nearest interpolation will be used for landmask, and linearNDFast for other variables
11:43:10 DEBUG   opendrift.readers.basereader.structured: Fetched env-block (size 1329x1500x1) for time before (2013-07-15 16:00:00)
11:43:10 DEBUG   opendrift.readers.basereader.structured: Interpolating before (2013-07-15 16:00:00) in space  (linearNDFast)
11:43:10 DEBUG   opendrift.readers.interpolation.structured: Initialising interpolator.
11:43:10 DEBUG   opendrift: NaN values for 767 elements, expanding data 1
11:43:11 DEBUG   opendrift: NaN values for 357 elements, expanding data 2
11:43:11 DEBUG   opendrift: NaN values for 223 elements, expanding data 3
11:43:11 DEBUG   opendrift: NaN values for 177 elements, expanding data 4
11:43:11 DEBUG   opendrift: NaN values for 145 elements, expanding data 5
11:43:11 DEBUG   opendrift: NaN values for 108 elements, expanding data 6
11:43:11 DEBUG   opendrift: NaN values for 102 elements, expanding data 7
11:43:11 DEBUG   opendrift: NaN values for 95 elements, expanding data 8
11:43:11 DEBUG   opendrift: NaN values for 82 elements, expanding data 9
11:43:11 DEBUG   opendrift: NaN values for 73 elements, expanding data 10
11:43:11 WARNING opendrift: Still NaN-values after 10 iterations, exiting!
11:43:11 DEBUG   opendrift: NaN values for 161 elements, expanding data 1
11:43:11 DEBUG   opendrift: NaN values for 145 elements, expanding data 2
11:43:11 DEBUG   opendrift: NaN values for 131 elements, expanding data 3
11:43:12 DEBUG   opendrift: NaN values for 124 elements, expanding data 4
11:43:12 DEBUG   opendrift: NaN values for 118 elements, expanding data 5
11:43:12 DEBUG   opendrift: NaN values for 108 elements, expanding data 6
11:43:12 DEBUG   opendrift: NaN values for 102 elements, expanding data 7
11:43:12 DEBUG   opendrift: NaN values for 95 elements, expanding data 8
11:43:12 DEBUG   opendrift: NaN values for 82 elements, expanding data 9
11:43:12 DEBUG   opendrift: NaN values for 73 elements, expanding data 10
11:43:12 WARNING opendrift: Still NaN-values after 10 iterations, exiting!
11:43:12 DEBUG   opendrift: NaN values for 161 elements, expanding data 1
11:43:12 DEBUG   opendrift: NaN values for 145 elements, expanding data 2
11:43:12 DEBUG   opendrift: NaN values for 131 elements, expanding data 3
11:43:12 DEBUG   opendrift: NaN values for 124 elements, expanding data 4
11:43:12 DEBUG   opendrift: NaN values for 118 elements, expanding data 5
11:43:12 DEBUG   opendrift: NaN values for 108 elements, expanding data 6
11:43:12 DEBUG   opendrift: NaN values for 102 elements, expanding data 7
11:43:12 DEBUG   opendrift: NaN values for 95 elements, expanding data 8
11:43:13 DEBUG   opendrift: NaN values for 82 elements, expanding data 9
11:43:13 DEBUG   opendrift: NaN values for 73 elements, expanding data 10
11:43:13 WARNING opendrift: Still NaN-values after 10 iterations, exiting!
11:43:13 DEBUG   opendrift: NaN values for 161 elements, expanding data 1
11:43:13 DEBUG   opendrift: NaN values for 145 elements, expanding data 2
11:43:13 DEBUG   opendrift: NaN values for 131 elements, expanding data 3
11:43:13 DEBUG   opendrift: NaN values for 124 elements, expanding data 4
11:43:13 DEBUG   opendrift: NaN values for 118 elements, expanding data 5
11:43:13 DEBUG   opendrift: NaN values for 108 elements, expanding data 6
11:43:13 DEBUG   opendrift: NaN values for 102 elements, expanding data 7
11:43:13 DEBUG   opendrift: NaN values for 95 elements, expanding data 8
11:43:13 DEBUG   opendrift: NaN values for 82 elements, expanding data 9
11:43:13 DEBUG   opendrift: NaN values for 73 elements, expanding data 10
11:43:13 WARNING opendrift: Still NaN-values after 10 iterations, exiting!
11:43:13 DEBUG   opendrift.readers.basereader.structured: No time interpolation needed - right on time.
11:43:13 DEBUG   opendrift.readers.basereader.variables: Reader projection is latlon - rotation of vectors is not needed.
11:43:13 DEBUG   opendrift.models.basemodel: Obtained data for all elements.
11:43:13 DEBUG   opendrift.models.basemodel: ---------------------------------------
11:43:13 DEBUG   opendrift.models.basemodel: Finished processing all variable groups
11:43:13 DEBUG   opendrift.models.basemodel:     Using fallback value 0 for x_sea_water_velocity for 66 elements
11:43:13 DEBUG   opendrift.models.basemodel:     Using fallback value 0 for y_sea_water_velocity for 66 elements
11:43:13 DEBUG   opendrift.models.basemodel:     Using fallback value 0 for upward_sea_water_velocity for 66 elements
11:43:13 DEBUG   opendrift.models.basemodel: Creating empty dictionary for profiles not profided by any reader: ['ocean_vertical_diffusivity']
11:43:13 DEBUG   opendrift.models.basemodel:       Using fallback value 0 for ocean_vertical_diffusivity for all profiles
11:43:13 DEBUG   opendrift.models.basemodel:     Using fallback value 10000 for sea_floor_depth_below_sea_level for 66 elements
11:43:13 DEBUG   opendrift.models.basemodel: ------------ SUMMARY -------------
11:43:13 DEBUG   opendrift.models.basemodel:     x_sea_water_velocity: -0.101092 (min) 0.327728 (max)
11:43:13 DEBUG   opendrift.models.basemodel:     y_sea_water_velocity: -0.220162 (min) 0.335274 (max)
11:43:13 DEBUG   opendrift.models.basemodel:     x_wind: 0 (min) 0 (max)
11:43:13 DEBUG   opendrift.models.basemodel:     y_wind: 0 (min) 0 (max)
11:43:13 DEBUG   opendrift.models.basemodel:     upward_sea_water_velocity: -0.0017794 (min) 0.00260731 (max)
11:43:13 DEBUG   opendrift.models.basemodel:     ocean_vertical_diffusivity: 0 (min) 0 (max)
11:43:13 DEBUG   opendrift.models.basemodel:     sea_surface_wave_significant_height: 0 (min) 0 (max)
11:43:13 DEBUG   opendrift.models.basemodel:     sea_surface_wave_stokes_drift_x_velocity: 0 (min) 0 (max)
11:43:13 DEBUG   opendrift.models.basemodel:     sea_surface_wave_stokes_drift_y_velocity: 0 (min) 0 (max)
11:43:13 DEBUG   opendrift.models.basemodel:     sea_surface_wave_period_at_variance_spectral_density_maximum: 0 (min) 0 (max)
11:43:13 DEBUG   opendrift.models.basemodel:     sea_surface_wave_mean_period_from_variance_spectral_density_second_frequency_moment: 0 (min) 0 (max)
11:43:13 DEBUG   opendrift.models.basemodel:     surface_downward_x_stress: 0 (min) 0 (max)
11:43:13 DEBUG   opendrift.models.basemodel:     surface_downward_y_stress: 0 (min) 0 (max)
11:43:13 DEBUG   opendrift.models.basemodel:     turbulent_kinetic_energy: 0 (min) 0 (max)
11:43:13 DEBUG   opendrift.models.basemodel:     turbulent_generic_length_scale: 0 (min) 0 (max)
11:43:13 DEBUG   opendrift.models.basemodel:     sea_floor_depth_below_sea_level: 0 (min) 10000 (max)
11:43:13 DEBUG   opendrift.models.basemodel:     land_binary_mask: 0 (min) 1 (max)
11:43:13 DEBUG   opendrift.models.basemodel: ---------------------------------
11:43:13 DEBUG   opendrift.models.basemodel: 		28483 active elements
11:43:13 DEBUG   opendrift.models.basemodel: 		-8.212972604119456 <- latitude  -> -7.596092142856598
11:43:13 DEBUG   opendrift.models.basemodel: 		-34.92039034976317 <- longitude -> -34.60268629154702
11:43:13 DEBUG   opendrift.models.basemodel: 		z = 0.0
11:43:13 DEBUG   opendrift.models.basemodel: ---------------------------------
11:43:13 DEBUG   opendrift.models.physics_methods: Calculating Hs from wind, min: 0.000000, mean: 0.000000, max: 0.000000
11:43:13 DEBUG   opendrift.models.physics_methods: Calculating wave period Tm02 from wind
11:43:13 DEBUG   opendrift.models.physics_methods:    min: 1.256637, mean: 1.256637, max: 1.256637
11:43:13 DEBUG   opendrift.models.physics_methods: Calculating wave period from wind, min: 1.256637, mean: 1.256637, max: 1.256637
11:43:13 DEBUG   opendrift.models.basemodel: 29 elements scheduled for deactivation (stranded)
11:43:13 DEBUG   opendrift.models.basemodel: 	(z: 0.000000 to 0.000000)
11:43:13 DEBUG   opendrift.models.basemodel: No elements hit seafloor.
11:43:14 DEBUG   opendrift.models.basemodel: Removed 29 elements.
11:43:14 DEBUG   opendrift.models.basemodel: Removed 29 values from environment.
11:43:14 DEBUG   opendrift.models.basemodel: remove items from profile for z
11:43:14 DEBUG   opendrift.models.basemodel: remove items from profile for ocean_vertical_diffusivity
11:43:14 DEBUG   opendrift.models.basemodel: Removed 29 values from environment_profiles.
11:43:14 DEBUG   opendrift.models.basemodel: Calling OceanDrift.update()
11:43:14 DEBUG   opendrift.models.physics_methods: No wind for wind-sheared ocean drift
11:43:14 DEBUG   opendrift.models.physics_methods: No Stokes drift velocity available
11:43:14 DEBUG   opendrift.models.oceandrift: No vertical advection for elements at surface
11:43:14 DEBUG   opendrift.models.basemodel: Horizontal diffusivity is 0, no random walk.
11:43:14 DEBUG   opendrift.models.basemodel: 28454 active elements (3266 deactivated)
11:43:14 DEBUG   opendrift.models.basemodel: to be seeded: 0, already seeded 31720
11:43:14 DEBUG   opendrift.models.basemodel: No elements hit seafloor.

What do you think? 

Best

**Comment by josefilho77** [comment]
No more clues? A added some horizontal diffusion and the result changed a lil bit. Do you think that could be the bathymetry? I mean, shallow areas...


https://user-images.githubusercontent.com/59928324/119006563-dff35100-b966-11eb-8a01-c7e7d28effc5.mp4

**Comment by knutfrode** [comment]
Could it be that the current in your file is simply 0 close to land?
You could try to plot it with e.g. ncview, or from commandline with
`$ readerinfo  E:\Doutorado_Geoc_UFPE\Simula_Final\Netcdfs\00wind_i.nc -p x_sea_water_velocity`
and compare with:
`$ readerinfo  E:\Doutorado_Geoc_UFPE\Simula_Final\Netcdfs\00wind_i.nc -p land_binary_mask`

**Comment by gauteh** [comment]
Closing, please comment if not solved.
