### ISSUE TITLE
telemac: packaging the python scripts?

### ISSUE THREAD

**Issue by gauteh** [OpenDrift/opendrift#629]
@Boorhin:

The telemac package is GPL like opendrift is. The python scripts inside telemac is about 2.6 mb, we need the data_manip part. The latest available zip of telemac only contains the old python 2.7 version of the scripts, hence it is necessary to use svn to export telemac from source to get these scripts. This is about 4gb compared to 2.6mb that we actually need. Maybe we can make a source-package with just these scripts that can be installed with `pip install git:...`? I would prefer not to need to maintain this for telemac, and they probably want to do that themselves. But it would make life a lot easier for users of this reader.

**Comment by Boorhin** [comment]
Let me try to make the Gdal version and we will see.
Totally understand that you wouldn't like to maintain it

**Comment by gauteh** [comment]
Ok, good, closing this issue then.

**Comment by gauteh** [comment]
What happens with the 3D file? Do you have an example file? Is it the one included with the tests?

**Comment by Boorhin** [comment]
Gdal raises an error and say it is not a valid Selafin file
No these are very large files. I can try to pass you a Gdrive link to one if you want to test.
I actually think that the reader is very slow because it doesn't keep the file open. 
mmap the file could be an option to explore. I have done it for similar binary files before.

**Comment by gauteh** [comment]
Ok, yeah, would be good to have both a 2D and a 3D file in the repo for testing eventually (especially given that the behavior of the readers seem to be quite different between the two). If you can share a 3d file over gdrive for now that would be interesting!

**Comment by gauteh** [comment]
Closing, don't think we will take on packaging telemac python scripts.
