### ISSUE TITLE
Can not save movie

### ISSUE THREAD

**Issue by ZenKa24** [OpenDrift/opendrift#63]
Dear all,
I get this error when I have saved a movie:
**## RuntimeError: Error creating movie, return code: 1 Try setting mpl.verbose.set_level("helpful")**

Please show me how to solve it?

Thanks you!

**Comment by knutfrode** [comment]
Please check that:
- your filename end with ".mp4"
- FFMPEG is installed on your system

Does this resolve the problem?

**Comment by ZenKa24** [comment]
Sure, my filename ended with ".mp4"
I could save movie before and I get this error after I updated model by git pull

**Comment by knutfrode** [comment]
Ok, then the most recent update seems not compatible with your version of matplotlib.
I have made a workaround now, so please update your code and try again.

**Comment by ZenKa24** [comment]
It worked :+1: 
So I want to make slower motion movie what I need do?

Thank you so much!

**Comment by ZenKa24** [comment]
I get more error when I run openoil3D with 'seafloor':
 **## ValueError: A reader providing the variable sea_floor_depth_below_sea_level must be added before seeding elements at seafloor.**

Please check it to me!
Thanks,

**Comment by knutfrode** [comment]
You can make slower movie by specifying fps (frames per second) as input til animation() method.

To seed elements at seafloor, you first need to add a reader which provides ocean depth. Otherwise OpenDrift cannot know what is the depth at the given location. Output form ocean models normally contains seafloor depth.

**Comment by ZenKa24** [comment]
But In your example_oilspill_seaflor.py file, I do not see you using ocean depth. I also run with seafloor before by command:
**## o.seed_elements(lon, lat, radius=10, number=2000, time=time, z='seafloor', oiltype='ALGERIAN CONDENSATE')**
It is OK!
But when I update model I got error. I have tried to run my script which successed but I got other error:
 **## o.config['processes']['evaporation'] = True
AttributeError: 'OpenOil3D' object has no attribute 'config'**

I do not know why? Please check it to me!

**Comment by knutfrode** [comment]
Seafloor works in the ``` example_oilspill_seaflor.py``` because it uses a reader (NorKyst800) which contains the variable ```sea_floor_depth_below_sea_level```
It still works on my machine with the latest version of OpenDrift. What error message do you get in your case?

The way to set config options has changed some time ago. Now the correct syntact is:
```o.set_config('processes:evaporation',  True)```

**Comment by ZenKa24** [comment]
I got this error:
## ValueError: A reader providing the variable sea_floor_depth_below_sea_level must be added before seeding elements at seafloor.

**Comment by knutfrode** [comment]
Ok, that is strange. Did you modify the script? Can you paste the full script here?

**Comment by ZenKa24** [comment]
It seem that I understand my solution. Maybe my input which no contains the variable ocean depth. 
I use CMEMS current data and wind data. If I want to add ocean depth in my case what I need do that?

**Comment by knutfrode** [comment]
I believe you can choose to also include seafloor depth when you download ocean model data from CMEMS.

**Comment by ZenKa24** [comment]
I can see, I will edit my script.

Thanks for your help!

**Comment by knutfrode** [comment]
Your're welcome!
Closing this ticket.
