### ISSUE TITLE
[How to] Seed with different markercolor?

### ISSUE THREAD

**Issue by josefilho77** [OpenDrift/opendrift#633]
Hi, is possible to define marker color somewhere when defining seed position? I dig into the code (plot, animation) and concluded that there is a kind of default marker color (green/active, red/stranded) and others to compare.

Is it possible to define it based o position? i.e. I want my seeds in some position/seedtime with one color and the most northern part with a different color.

Sorry for the basic question, but I dig into the closed/open issues and did not find anything related to it. 

Regards

**Comment by knutfrode** [comment]
Yes, there is an element property `origin_marker` for this purpose.
It is not well documented, but I updated now one of the example scripts to illustrate the usage:
https://github.com/OpenDrift/opendrift/pull/634/files

The [gallery](https://opendrift.github.io/gallery/example_multi_seed.html#sphx-glr-gallery-example-multi-seed-py) should be updated to show this within a few hours.
