### ISSUE TITLE
Saving  start and final times for each particle

### ISSUE THREAD

**Issue by AndresSepulveda** [OpenDrift/opendrift#644]
As a continuation of issue #582 

Saving only start and final lat/lon for each particle #582

how can I save now the initial release time and  the final (deactivation) time?

Any help is appreciated.

Regards,

Andrés

**Comment by AndresSepulveda** [comment]
This seems to work for the start time

            lons_start = o.elements_scheduled.lon
            lats_start = o.elements_scheduled.lat
           time_start = o.elements_scheduled_time

            o.run(end_time=self.confobj.end_date,
                time_step=timedelta(minutes=60),
                export_variables=['status','time'])

but I haven´t figured out how to store the final time.

**Comment by knutfrode** [comment]
This should give you the deactivation times:

```
index_of_first, index_of_last = o.index_of_activation_and_deactivation()
times = o.get_time_array()[0]
deactivation_times = [times[i] for i in index_of_last]
print(deactivation_times)
```

Note that the end time of the simulation will be returned for particles that have not been deactivated.

**Comment by AndresSepulveda** [comment]
Thanks, that works fine. Output is now

2000-01-02 02:40:00 -74.2300 -42.4600 2000-01-07 02:00:00 -74.1950 -42.3077 1
2000-01-03 05:20:00 -74.2300 -42.4600 2000-01-08 05:00:00 -74.1875 -42.3060 1
