### ISSUE TITLE
Readers not added for the some variables

### ISSUE THREAD

**Issue by HanhHelen** [OpenDrift/opendrift#67]
On GUI I got the announcement:
Readers not added for the following variables:
  ocean_vertical_diffusivity
  sea_surface_wave_period_at_variance_spectral_density_maximum
  upward_sea_water_velocity
I guess I have problem with the database from these links:
 'http://data.ncof.co.uk/thredds/dodsC/METOFFICE-GLO-AF-PHYS-HOURLY-CUR',    'http://oos.soest.hawaii.edu/thredds/dodsC/hioos/model/atm/ncep_global/NCEP_Global_Atmospheric_Model_best.ncd'])
Hope the authors can help. Thanks in advance.

**Comment by knutfrode** [comment]
This is just a warning that those sources does not contain the given variables, and that (reasonable) default values will be used instead. But they contain the most important variables, including ocean current (x_sea_water_velocity, y_sea_water_velocity) and wind (x_wind, y_wind). Wave parameters will be parameterised from wind if no readers are available to provide wave parameters.
