### ISSUE TITLE
High resolution Coastline configuration

### ISSUE THREAD

**Issue by rivano10** [OpenDrift/opendrift#68]
Hi,

I tried to use my own coastline with a very high resolution. However OpenDrift still using default Basemap instead. I don't know what's the problem. I tried to configure (o.set_config('general:use_basemap_landmask', False) as you said in #62 , but still doesn't work. I need to do something else?

I attach my program. Can you tell what I am doing wrong?

[example.zip](https://github.com/OpenDrift/opendrift/files/1823411/example.zip)

Thanks in advance,
Gino

**Comment by knutfrode** [comment]
Hi,

Does your readers contain the variable "land_binary_mask" as recognised by
OpenDrift?

You can check this by printing the readers ("print <reader>") or printing
the simulation object ("print o") before or after the run.
Note that even if a customised landmask is used during the simulation, the
built-in plotting methods in OpenDrift will use the Basemap landmask for
plots.
It would also be useful to see the log from your run; it should indicate
which reader is used for land_binary_mask.

2018-03-19 2:28 GMT+01:00 rivano10 <notifications@github.com>:

**Comment by rivano10** [comment]
Hi again, thank you for the answers. With your comment a have a few questions:
1) My two readers contain the land_binary_mask, but my roms file ('croco_his2_finegrid_3_mod2.nc' in my file attached before) have a not very good resolutions. I don't want to use it. I need to use the 'cup2_Opendrift.nc' wich have the finest resolution coastline. in "log" (attached here) the simulation use both, I think. Is it possible to use 'cup2_Opendrift.nc' only?

2) "Note that even if a customised landmask is used during the simulation, the built-in plotting methods in OpenDrift will use the Basemap landmask for plots." My principal idea is do a High resolution plot and animation using this finest resolution coastline (cup2_Opendrift.nc'), because my simulation it's in the coast. Is possible to do it? 

![log](https://user-images.githubusercontent.com/17747249/37615759-cbb53584-2b8c-11e8-83fa-cad26ab24abb.png)

**Comment by knutfrode** [comment]
1) You can add your readers in opposite order, first 'cup2_Opendrift.nc' and then 'croco_his2_finegrid_3_mod2.nc'

You can also add one reader at a time, and specify which variables this reader shall provide, e.g.:
```
reader_telemac = reader_ROMS_native.Reader('croco_his2_finegrid_3.nc')
reader_landmask = reader_netCDF_CF_generic.Reader('cup2_Opendrift.nc')
o.add_reader(reader_landmask, variables='land_binary_mask')
o.add_reader(reader_telemac)
```
You can check that order is as expected by printing simulation object again.

2) Presently the plotting and animation methods may only use the vector coastlines provided by Basemap.
You may display the landmask from your readers as a red/blue mask by:
```
o.plot(background='land_binary_mask')
```
but the Basemap landmask will be shown on top.
This could be updated to show only the rasterised landmask, but I won't have time to implement that before at least one month from now.
If you need this more urgently, you could try to modify the existing plot-method.

**Comment by rivano10** [comment]
I did the changes you mentioned in 1. However my simulation stop in the firts step. Maybe is not reading the coastline correctly because I have some really weird WARNINGS (e.g. WARNING: Data block from cup2_Opendrift.nc not large enough to cover element positions within timestep. Buffer size (8) must be increased.). But I'm not sure if that it's the real problem because I'm a begginer in Python. Do you know how can I fix it?
[files.zip](https://github.com/OpenDrift/opendrift/files/1827279/files.zip)


I attached my coastline and log files

Thanks in advance

**Comment by AndresSepulveda** [comment]
Hi Gino, were you able to solve the buffer size issue? I also get

WARNING: Data block from roms native not large enough to cover element positions within timestep. Buffer size (6) must be increased.

but I am not sure where to change that. I think the initial size is set in basereader.py, but to change it within the program... something like

o.buffer(9)   ?

**Comment by knutfrode** [comment]
The way to set it is:
```r.buffer = 9```
Where ```r``` is a reader, after it is created, but before it is added to the simulation object (```o```).
However, most likely this warning is a bit misleading, and instead due to elements exiting the coverage of the reader.
