### ISSUE TITLE
missing variables 'land_binary_mask' 

### ISSUE THREAD

**Issue by arian-dialectaquiz** [OpenDrift/opendrift#681]
Hello!
I'm dealing with a problem that I don't quite understand why.
I wish to use the land mask of the model, not the general one, so I disabled the use of the general land mask as in [https://opendrift.github.io/gallery/example_model_landmask.html],  doing:
`o.set_config('general:use_auto_landmask', False)`

but an error was raised:

`Simulation stopped within first timestep. "Missing variables: ['land_binary_mask']", 'The simulation stopped before requested end time was reached.'`

However, when I print the reader, it finds the variable 'land_binary_mask'  as shown in the figure:

![image](https://user-images.githubusercontent.com/59614436/129958711-145eff54-b184-4d75-878a-cc85c42e0a2c.png)

Could you help me? I've no idea why this happens.

Thank you!

**Comment by knutfrode** [comment]
Hi,
This reader is valid for a given time (25Oct2019 to 27Oct2019) and for a given area.
Could it be that the seeded elements are outside this area or time interval?

If not, can you post the full log until the given error message?

**Comment by Arian-dia** [comment]
Hi!
Yes, both in time and space it is valid, as shown in the figure that is generated when I used the general land mask:

![test](https://user-images.githubusercontent.com/59614436/129971498-593eedc6-7e3f-487a-bdd5-08eb75733055.png)

The full log is in the .txt attached file.

[log_test.txt](https://github.com/OpenDrift/opendrift/files/7010140/log_test.txt)

**Comment by knutfrode** [comment]
There is an error message `IndexError: index 62 is out of bounds for axis 0 with size 1`, indicating that there could be something wrong with this file.

Could you post an ncdump of it?

You can also try the following from commandline:
`readerinfo.py <file> -p land_binary_mask`

**Comment by Arian-dia** [comment]
I did not understand how to perform your last advice `readerinfo.py <file> -p land_binary_mask`.
But this error `IndexError: index 62 is out of bounds for axis 0 with size 1` did not occur befor I disable the general land_mask. The index 62 is probably the indx position, that is no longer match with the space configuration. 

The ncdump log is in the .txt, and the `FSM: free surface mask` variable is the land_binary_mask
[ncdump_from_r298.txt](https://github.com/OpenDrift/opendrift/files/7010306/ncdump_from_r298.txt)

**Comment by Arian-dia** [comment]
Yes. The readerwas made based at the ROMS_native_reader, but for other model.
I've declared the FSM with a new standard name of land_binary_mask:

![image](https://user-images.githubusercontent.com/59614436/129977415-c6069f87-9a12-4242-ad4e-ec96c58d89f8.png)

And I also defined it before the get_variables funtion:

![image](https://user-images.githubusercontent.com/59614436/129977619-cc4e1a52-0076-4019-994c-90dbe32b6f32.png)

I'll insert some debug to check it better.
The indexing issues to which you refer are the indx and indy indexes?

**Comment by Arian-dia** [comment]
I managed to overcome the index error via remapping the FSM name befor the initialization

`self.Dataset_a = xr.open_dataset(filename)

remap_names_a = {'FSM': 'land_binary_mask'}
self.Dataset_1 = self.Dataset_a.rename(remap_names_a)`

But the same error appears regarding the land_mask

`ValueError: Simulation stopped within first timestep. "Missing variables: ['land_binary_mask']", 'The simulation stopped before requested end time was reached.'`

**Comment by knutfrode** [comment]
Ok, if the index error is gone, there must be another error also causing
you reader not to work for landsmask.
Please look for the first error message in your log, this is normally the
real error.

**Comment by Arian-dia** [comment]
Hello!
Sorry for the delay to answer.
It worked. I looked to the initial erros and wrote some debug.

![image](https://user-images.githubusercontent.com/59614436/130166240-7aa914db-89e6-4bf6-bdc4-753702ed9a21.png)



Thank you so much!


[log_test.txt](https://github.com/OpenDrift/opendrift/files/7018527/log_test.txt)
