### ISSUE TITLE
WRF?

### ISSUE THREAD

**Issue by ivicajan** [OpenDrift/opendrift#70]
Dear developers,

wondering if there will be support for readers to ingest WRF model outputs?

Doesn't have to be WRF, I can actually rename any netcdf variable via ncml on my opendap server but not sure what exact dimension/variable names should I use. 
I've tried with what I found in the code for AROME (2d lon/lat) but as I do not have projection_lambert information and even I renamed my variables to be longitude, latitude and x_wind_10m etc still I am not able to load them. 

example is available at:
http://130.95.29.59:8080/thredds/dodsC/WRF/perth_agg.ncml
so you can ncdump -h that link...  
any comment is welcome
Thanks in advance,
Ivica

**Comment by knutfrode** [comment]
Hi,

If you add standard_name = 'longitude"/"latitude" to your LON/LAT variables it should work.

But the best (fastest) would be if your file contained x- and y- coordinates and a projection definition (proj4 string).

**Comment by ivicajan** [comment]
I think i tried with that standard_name attribute but as my lon lat are 2d it just error in line 137 or something like that.
If i go with x and y they should be in meters and proj will put them on lon/lat?CheersIvica
-------- Original message --------From: Knut-Frode Dagestad <notifications@github.com> Date: 12/4/18  8:49 pm  (GMT+08:00) To: OpenDrift/opendrift <opendrift@noreply.github.com> Cc: Ivica Janekovic <ivica.jan@gmail.com>, Author <author@noreply.github.com> Subject: Re: [OpenDrift/opendrift] WRF? (#70) 
Hi,
If you add standard_name = 'longitude"/"latitude" to your LON/LAT variables it should work.
But the best (fastest) would be if your file contained x- and y- coordinates and a projection definition (proj4 string).

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/OpenDrift/opendrift","title":"OpenDrift/opendrift","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/OpenDrift/opendrift"}},"updates":{"snippets":[{"icon":"PERSON","message":"@knutfrode in #70: Hi,\r\n\r\nIf you add standard_name = 'longitude\"/\"latitude\" to your LON/LAT variables it should work.\r\n\r\nBut the best (fastest) would be if your file contained x- and y- coordinates and a projection definition (proj4 string)."}],"action":{"name":"View Issue","url":"https://github.com/OpenDrift/opendrift/issues/70#issuecomment-380793324"}}}

**Comment by knutfrode** [comment]
If you add standard_name to LON and LAT, and make a file available, then I can have a look at it.

**Comment by ivicajan** [comment]
I changed it in ncml, so no need to change netCDF files...
In that way I can reshape it into whatever is needed (dimension name,
variable name, attribs etc), just let me know.
http://130.95.29.59:8080/thredds/catalog/WRF/catalog.html?dataset=WRF/perth_agg.ncml
just click on opendap link..

Thanks for the help
Ivica

**Comment by knutfrode** [comment]
I see that the support for files with only 2D arrays of lon/lat is presently not sufficient.
I can try to improve that, but unfortunately wont have time the next couple of weeks.

If you want to try in the meantime by adding projection coordinates to your files, I can provide some hints:
- you need a variable (any type) with attribute "proj4" which is a coordinate system definition, e.g. ```proj4 = "+proj=stere +lat_0=90 +lon_0=70 +lat_ts=60 +units=m +a=6.371e+06 +e=0 +no_defs"```
- and then you need cooresponding x- and y- coordinates (1D arrays) as variables with ```standard_name=projection_x_coordinate``` (same for y).

**Comment by ivicajan** [comment]
No worries,
when you get time it would be great to have 2D lon/lat coords working for
wind.
I thought this is similar like you have for ocean (for example ROMS has
lon_rho, lon_u, lon_v and the same for v which are 2D as well).

cheers
Ivica

**Comment by huluyeer** [comment]
Thank for the advice. I successfully connected with  WRF model outputs through your suggestion.

1. I refer to this code. write a new netCDF files.
https://github.com/OpenDrift/opendrift/blob/ab620c940eda1be5680eaca18b1a5bdda0b0da20/opendrift/models/basemodel.py#L2932
2. add the proj4 and  standard_name to LON and LAT
3. change the lon/lat into 1D
4. use scipy.interpolate.griddata() modify the U10 and V10.  Because the latitude is not constant.  y-coordinate is constant, but I didn't output it.
5.   use  reader_netCDF_CF_generic()

**Comment by knutfrode** [comment]
The netCDF-generic-reader now has better support for datasets with only lon/lat-arrays and no projection/x-y information.

Please test, and provide feedback if your dataset is not supported.
