### ISSUE TITLE
What happens if particles move out of reader_basemap_landmask coverage 

### ISSUE THREAD

**Issue by simonweppe** [OpenDrift/opendrift#72]
At the moment, it seems that this will just return a ValueError, saying that the particles aire out of the domain, (and potentially skip for the next basemap reader if there is one).

Is there any way to set a basemap reader so that "out of domain" particles are instead flagged as "True" (as the on-land ones), so that they would be removed (stranded), or recirculated (previous) depending on coastline 'general:coastline_action' ?

Could be useful to spatially limit max simulation extents. I'll give it a try if there is no existing switch.

**Comment by knutfrode** [comment]
If setting fallback value of land_binary mask to 1, offgrid is treated as land.
```
o.fallback_values['land_binary_mask'] = 1
```
You must then make sure that no other readers except for basemap will provide landmask, as readers have precedence over fallback_values.

However, in the meantime, the extent of a simulation may also be restricted with config settings, e.g.:

```
o.set_config('drift:deactivate_north_of' = 80)
```
and similarly for ```south_of, west_of, east_of```

**Comment by gauteh** [comment]
@knutfrode: Is this issue obsolete with the new landmask reader?

**Comment by knutfrode** [comment]
Yes, this should be ok. Closing issue.
