### ISSUE TITLE
Changing projection for output

### ISSUE THREAD

**Issue by OakesHolland** [OpenDrift/opendrift#728]
Hi team,

I am running trajectory sims around Antarctica, and the outputs are coming out quite squished - they cover long distances longitudinally, but not latitudially - and they cross the 180oE line. See below.

![casey_aut](https://user-images.githubusercontent.com/73867353/136645666-a246489c-1453-4e5c-a8d8-aa1d54d579b1.jpg)
 
Is there a way to change to a polar stereo projection for the map and animation outputs?  Sorry if it's a simple question, I'm quite new to python coding.  The figure provided was made just using the built-in o.plot feature, and the animation suffers similar display problems plotting in this region.

Also, while I am here, is it possible to output a csv file of only certain variables (e.g. lat,lon,age_seconds, time)?

Many thanks in advance :)

Kind regards,
Oakes

**Comment by knutfrode** [comment]
Hi Oakes,

Presently, the plot/animation methods do only support Mercator projection. On thing that could help a little, is to set the bounds through the keyword `corners = [lonmin, lonmax, latmin, latmax]`, as in this example:
https://opendrift.github.io/gallery/example_grid.html#sphx-glr-gallery-example-grid-py
Note that neither simulation nor plotting is presently 100% waterproof wrt crossing the dateline and/or the 0 meridian, so issues may arise, and it might be a challenge to achieve what you want in this case, with crossing of dateline.

Direct export is only to netCDF-file, and the variables to output there may be limited with
`export_variables= [<list of variables>}` as demonstrated in this example:
https://opendrift.github.io/gallery/example_generic.html
It should be fairly straightforward to produce a csv file based on the netCDF-file, or make an ascii-export method as this one for the Leeway model in particular: 
https://opendrift.github.io/_modules/opendrift/models/leeway.html#Leeway.export_ascii
However, one need then generally to deal with the possibility of elements seeded and deactivated at different times.

**Comment by gauteh** [comment]
With trajan you can specify a different CRS for the plot.
