### ISSUE TITLE
Problem installing opendrift

### ISSUE THREAD

**Issue by hroarty** [OpenDrift/opendrift#736]
When I choose option 1 for the install I am able to clone the repository but I get the attached error when I try to create the environment from the yml file.
[opendrift_install_error.txt](https://github.com/OpenDrift/opendrift/files/7353942/opendrift_install_error.txt)

**Comment by knutfrode** [comment]
Did you manage to install OpenDrift after reinstalling Miniconda or/and disabling any PYTHONPATH variable?

**Comment by hroarty** [comment]
I haven't had a chance to try this.  Thanks for following up.  Will try and get to this tomorrow.

**Comment by gauteh** [comment]
Did you figure this one out? Closing until further information.
