### ISSUE TITLE
o.animation speed?

### ISSUE THREAD

**Issue by AndresSepulveda** [OpenDrift/opendrift#74]
Is it possible to slow down the gif bieng written by  o.animation ?

**Comment by knutfrode** [comment]
There is an option fps (frames per second), e.g.
```o.animation(filename='test.gif', fps=5)```

I am not sure if it presently works as intended on all platforms, but please test on your machine. I believe it requires that your Python may access your Imagemagick installation.
https://github.com/OpenDrift/opendrift/blob/master/opendrift/models/basemodel.py#L3246

The animated GIFs may be quite large. However, I have good experience of making MP4-animations, and then this nice web-site to convert to GIFs, or making other improvements:
https://ezgif.com/video-to-gif

**Comment by AndresSepulveda** [comment]
Thanks, that works fine.
