### ISSUE TITLE
Plot track in animation?

### ISSUE THREAD

**Issue by AndresSepulveda** [OpenDrift/opendrift#75]
Hi,

I would like to do a combination of the o.plot and o.animation where an animation is produced, but also with the grey track of the trajectory. Any suggestion on that?

**Comment by knutfrode** [comment]
This was quite simple to implement (https://github.com/OpenDrift/opendrift/commit/90ce36235661bcca4fbb76eb24c49287c0d3a9df) and is now possible if you provide keyword ```show_trajectories=True``` to ```animation()```

Line properties/style is hardcoded for now, but can make it adjustable if necessary.
