### ISSUE TITLE
Pelagic egg, T and S response?

### ISSUE THREAD

**Issue by AndresSepulveda** [OpenDrift/opendrift#76]
I wonder if there is anything done to add T and S response for a pelagic egg? We want to adapt that routine for a particular species.

**Comment by knutfrode** [comment]
This has been done e.g. by @trondkr for the work in [this publication](https://www.researchgate.net/publication/324705889_Sensitivity_of_modelled_North_Sea_cod_larvae_transport_to_vertical_behaviour_ocean_model_resolution_and_interannual_variation_in_ocean_dynamics).

That code is not yet adapted for the open repository, as it e.g. contains e.g. some fortran-python-bindings. However, it might become available in the open repository within this year.

**Comment by AndresSepulveda** [comment]
Hi, any news on the this addition to the OpenDRIFT? Larval response to T and S fields in an interesting topic in a few projects here...
