### ISSUE TITLE
Run OpenDrift in parallel

### ISSUE THREAD

**Issue by AndresSepulveda** [OpenDrift/opendrift#77]
Is it possible?

**Comment by knutfrode** [comment]
OpenDrift is optimised for performance in many ways, but there is presently no built-in parallelisation.
A simulation consists of many different tasks, and it will depend on the specific case what is the performance bottleneck. Hence, parallelisation is not trivial here.

The good news about this is that as OpenDrift uses only one processor, you may increase the performance by doing several runs in parallell, with different invoking scripts.

Any pull-requests with parallelisation of tasks is welcome!
