### ISSUE TITLE
Question about io_netcdf

### ISSUE THREAD

**Issue by Boorhin** [OpenDrift/opendrift#792]
line77      `  var.setncattr('coordinates', 'lat lon time')`
 Is added as an attribute of the variables while initialising the netcdf. 
I don't understand this as the variable has for coordinates ('trajectory', 'time')
Is that an error? or is there a specific from CF that I am not understanding?
Cheers

**Comment by knutfrode** [comment]
You are right, I have no idea where that strange line came from.
So I have now removed it: https://github.com/OpenDrift/opendrift/pull/793

**Comment by Boorhin** [comment]
Sorry just found also a minor one with a range starting by 0 line 93
` 0:num_steps_to_export`
 Could be `:num_steps_to_export`
