### ISSUE TITLE
Improve support for netCDF CF format

### ISSUE THREAD

**Issue by knutfrode** [OpenDrift/opendrift#8]
E.g. data from the global HYCOM model are read with wrong geolocation (probably since lon/lat are 2D arrays for some reason.)
http://tds.hycom.org/thredds/GLBu0.08/expt_91.1.html

**Comment by cordeirovpn** [comment]
Hello,
even formatting the 2D arrays from HYCOM to 1D reader_netCDF_CF_generic.Reader() still does not working.
The reader_netCDF_CF_unstructured.Reader(), apparently,  works well after formatting the 2D lat/lon arrays to 1D from HYCOM - Analysis(GLBa.0.08/expt_91.1). But when run it still fails.

the following command (as example):
In [9]: myreader = reader_netCDF_CF_unstructured.Reader('/home/path/datafile.nc')

INFO: Opening dataset: /home/path/data
INFO: Opening file with Dataset
DEBUG: Finding coordinate variables.

In [10]: print myreader
...
Available time range:
  start: 2015-01-10 00:00:00   end: 2015-01-10 00:00:00   step: None
Variables:
  y_sea_water_velocity
  sea_water_salinity
  x_sea_water_velocity
===========================

But when I runs the OceanDrift simulation I get the following error:

'OceanDrift' object has no attribute 'environment'

Do you have any idea about what is going on?

**Comment by knutfrode** [comment]
The HYCOM data are provided on different grids, including [a complex, hybrid one](https://hycom.org/data/glbv0pt08) and a [curvilinear](https://hycom.org/data/glba0pt08) grid, which are not well supported yet. 

However, there is also a product which is interpolated to a uniform grid, which works well with OpenDrift: https://hycom.org/data/glbu0pt08

http://tds.hycom.org/thredds/GLBu0.08/expt_91.1.html
http://tds.hycom.org/thredds/GLBu0.08/expt_91.2.html 

The unstructured netCDF reader should not be used for these datasets.

**Comment by cordeirovpn** [comment]
Hello,
Thanks for your reply.
Your suggestion works well with reader_netCDF_CF_generic.
 HYCOM + NCODA Global 1/12° Reanalysis works well too. Probably because both use GLBu0.08.
