### ISSUE TITLE
plot after run

### ISSUE THREAD

**Issue by oceandiff** [OpenDrift/opendrift#812]
Hi, there is a way to plot or create an animation after the run without re-run the model?
Thank you

**Comment by gauteh** [comment]
Try o.plot() or o.animation(), take a look at the examples for a quick
tutorial.

tir. 21. des. 2021, 11:28 skrev oceandiff ***@***.***>:

**Comment by AndresSepulveda** [comment]
I do this

  import opendrift 
  import numpy as np 

  o = opendrift.open("archivo.nc", elements=np.arange(0,392000,100)) 
  o.plot(filename="archivo.png",linecolor="z",fast = True) 
  o.animation(filename="archivo.mp4",linecolor="z",fast = True)

to plot a few trajectories, usefull if the plot takes too long.

You can also do

   opendrift_animate.py openout.nc -f anim.mp4
   opendrift_plot.py openout.nc -f plot.png

**Comment by oceandiff** [comment]
Thank you!
