### ISSUE TITLE
error while running tests

### ISSUE THREAD

**Issue by wkikk** [OpenDrift/opendrift#82]
Hi all, 
I tried to run the test procedure and have many errors as follow (always at the same line in basemodel.py).
does any one already experienced this situation ?
Thanks in advance for any help.
Y

 ======================================================================
ERROR: test_shipdrift_backwards (__main__.TestModels)
Case above, reversed
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_models.py", line 92, in test_shipdrift_backwards
    s.run(time_step=-600, duration=timedelta(hours=4))
  File "/home/quentin/opendrift-master/opendrift/models/basemodel.py", line 2088, in run
    'first timestep. ' + self.get_messages())
ValueError: Simulation stopped within first timestep. 'The simulation stopped before requested end time was reached.'

======================================================================
ERROR: test_windblow (__main__.TestModels)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_models.py", line 54, in test_windblow
    o.run(steps=24, time_step=3600)
  File "/home/quentin/opendrift-master/opendrift/models/basemodel.py", line 2088, in run
    'first timestep. ' + self.get_messages())
ValueError: Simulation stopped within first timestep. 'The simulation stopped before requested end time was reached.'

**Comment by knutfrode** [comment]
Hi,

Could you please post a bit more of the output, e.g. the first 500 lines. The above messages do not say why simulation stopped.

**Comment by wkikk** [comment]
Thank you for your quick answer !
please find below the full error message:

~/opendrift-master/tests$ python2  test_models.py
INFO: OpenDriftSimulation initialised (version 1.0.4)
DEBUG: Setting buffer size 3 for reader ArtificialOceanEddy, assuming a maximum average speed of 5 m/s.
DEBUG: Setting buffer size 2 for reader ArtificialOceanEddy, assuming a maximum average speed of 1 m/s.
DEBUG: Calculation SRS set to: +proj=stere +lat_0=90 +lon_0=70 +lat_ts=60 +units=m +a=6.371e+06 +e=0 +no_defs +ellps=WGS84 
DEBUG: Using srs for common grid: +proj=stere +lat_0=90 +lon_0=70 +lat_ts=60 +units=m +a=6.371e+06 +e=0 +no_defs
DEBUG: Added reader ArtificialOceanEddy
WARNING: Oil type not specified, using default: AASGAR
TIMING: (0.01s) __main__.TestModels.test_seed
.DEBUG: Calculation SRS set to: None
241
ETIMING: (0.04s) __main__.TestModels.test_shipdrift
25
ETIMING: (0.03s) __main__.TestModels.test_shipdrift_backwards
25
WARNING: The simulation stopped before requested end time was reached.
ETIMING: (0.05s) __main__.TestModels.test_windblow

======================================================================
ERROR: test_shipdrift (__main__.TestModels)
Sintef case study
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_models.py", line 71, in test_shipdrift
    s.run(time_step=60, duration=timedelta(hours=4))
  File "/home/quentin/opendrift-master/opendrift/models/basemodel.py", line 2088, in run
    'first timestep. ' + self.get_messages())
ValueError: Simulation stopped within first timestep. 'The simulation stopped before requested end time was reached.'


======================================================================
ERROR: test_shipdrift_backwards (__main__.TestModels)
Case above, reversed
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_models.py", line 92, in test_shipdrift_backwards
    s.run(time_step=-600, duration=timedelta(hours=4))
  File "/home/quentin/opendrift-master/opendrift/models/basemodel.py", line 2088, in run
    'first timestep. ' + self.get_messages())
ValueError: Simulation stopped within first timestep. 'The simulation stopped before requested end time was reached.'


======================================================================
ERROR: test_windblow (__main__.TestModels)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_models.py", line 54, in test_windblow
    o.run(steps=24, time_step=3600)
  File "/home/quentin/opendrift-master/opendrift/models/basemodel.py", line 2088, in run
    'first timestep. ' + self.get_messages())
ValueError: Simulation stopped within first timestep. 'The simulation stopped before requested end time was reached.'


----------------------------------------------------------------------
Ran 4 tests in 0.127s

FAILED (errors=3)

**Comment by knutfrode** [comment]
Unfortunately those specific tests do not show enough detail (high loglevel).
Can you instead paste the full output from ```test_stranding.py```

**Comment by wkikk** [comment]
You can find it below!
python2 test_stranding.py
9
WARNING: Data type of variable (int16) and _FillValue (float32) is not the same. Masking 0-values instead
WARNING: The simulation stopped before requested end time was reached.
ETIMING: (2.78s) __main__.TestStranding.test_stranding_3d
29
WARNING: The simulation stopped before requested end time was reached.
ETIMING: (2.52s) __main__.TestStranding.test_stranding_options
INFO: OpenDriftSimulation initialised (version 1.0.4)
INFO: Opening dataset: /home/quentin/opendrift-master/tests/test_data/2Feb2016_Nordic_sigma_3d/Arctic20_1to5Feb_2016.nc
INFO: Opening file with Dataset
DEBUG: Finding coordinate variables.
DEBUG: Parsing variable: X
DEBUG: Parsing variable: Y
DEBUG: Parsing variable: aice
DEBUG: Parsing variable: depth
DEBUG: Parsing variable: forecast_reference_time
DEBUG: Parsing variable: h
DEBUG: Parsing variable: hice
DEBUG: Parsing variable: latitude
DEBUG: Parsing variable: longitude
DEBUG: Parsing variable: mask
DEBUG: Parsing variable: polar_stereographic
DEBUG: Parsing variable: salinity
DEBUG: Parsing variable: temperature
DEBUG: Parsing variable: time
DEBUG: Parsing variable: u
DEBUG: Parsing variable: ubar
DEBUG: Parsing variable: v
DEBUG: Parsing variable: vbar
DEBUG: Parsing variable: zeta
DEBUG: Setting buffer size 24 for reader /home/quentin/opendrift-master/tests/test_data/2Feb2016_Nordic_sigma_3d/Arctic20_1to5Feb_2016.nc, assuming a maximum average speed of 5 m/s.
INFO: Opening dataset: /home/quentin/opendrift-master/tests/test_data/2Feb2016_Nordic_sigma_3d/Nordic-4km_SLEVELS_avg_00_subset2Feb2016.nc
INFO: Opening file with Dataset
INFO: Read GLS parameters from file.
INFO: Making Splines for lon,lat to x,y conversion...
DEBUG: Setting buffer size 108 for reader roms native, assuming a maximum average speed of 5 m/s.
DEBUG: Setting buffer size 7 for reader /home/quentin/opendrift-master/tests/test_data/2Feb2016_Nordic_sigma_3d/Arctic20_1to5Feb_2016.nc, assuming a maximum average speed of 1 m/s.
DEBUG: Calculation SRS set to: +units=m +proj=stere +a=6371000 +b=6371000 +lat_0=90 +lat_ts=60 +lon_0=58 +ellps=WGS84
DEBUG: Using srs for common grid: +proj=stere +a=6371000 +b=6371000 +lat_0=90 +lat_ts=60 +lon_0=58
DEBUG: Added reader /home/quentin/opendrift-master/tests/test_data/2Feb2016_Nordic_sigma_3d/Arctic20_1to5Feb_2016.nc
DEBUG: Setting buffer size 24 for reader roms native, assuming a maximum average speed of 1 m/s.
DEBUG: Added reader roms native
DEBUG: ------------------------------------------------------
DEBUG: Software and hardware:
DEBUG:   unknown GB memory
DEBUG:   4 processors (x86_64)
DEBUG:   Basemap version 1.0.7
DEBUG:   NumPy version 1.13.3
DEBUG:   SciPy version 1.1.0
DEBUG:   Matplotlib version 2.2.2
DEBUG:   NetCDF4 version 1.4.0
DEBUG:   Python version 2.7.15 |Anaconda, Inc.| (default, May  1 2018, 23:32:55) [GCC 7.2.0]
DEBUG: ------------------------------------------------------
INFO: Config validation OK
DEBUG: No output file is specified, neglecting export_buffer_length
INFO: Setting SRS to latlong, since non-zero value used for fallback vectors (x_sea_water_velocity)
DEBUG: Calculation SRS set to: +units=m +proj=latlong +ellps=WGS84
INFO: Fallback values will be used for the following variables which have no readers: 
INFO: 	sea_surface_wave_significant_height: 0.000000
INFO: 	x_wind: 0.000000
INFO: 	y_wind: 0.000000
INFO: 	ocean_vertical_diffusivity: 0.020000
INFO: 	surface_downward_x_stress: 0.000000
INFO: 	surface_downward_y_stress: 0.000000
INFO: 	turbulent_kinetic_energy: 0.000000
INFO: 	turbulent_generic_length_scale: 0.000000
INFO: 	upward_sea_water_velocity: 0.000000
INFO: Adding a dynamical landmask (resolution "c") based on assumed maximum speed of 1 m/s. Adding a customised landmask may be faster...
DEBUG: Creating Basemap...
DEBUG: Creating rasterized Basemap...
DEBUG: Rasterizing Basemap, number of land polys: 4
DEBUG: Rasterizing Basemap, bounding box: [728000.0, 1643500.0, -500.0, 1382000.0]
DEBUG: backend agg version v2.2
DEBUG: Rasterized size: [1831, 2765]
DEBUG: backend Qt5Agg version 5.9.2
DEBUG: Added reader basemap_landmask
INFO: Using existing reader for land_binary_mask
DEBUG: ----------------------------------------
DEBUG: Variable group ['land_binary_mask']
DEBUG: ----------------------------------------
DEBUG: Calling reader basemap_landmask
DEBUG: ----------------------------------------
DEBUG: Data needed for 100 elements
DEBUG: Reader time:
		None (before)
		None (after)
DEBUG: Fetching variables from basemap_landmask
DEBUG: Checking 0 of 100 coordinates to polygons
DEBUG: Fetched env-before
DEBUG: No time interpolation needed - right on time.
DEBUG: Obtained data for all elements.
DEBUG: ---------------------------------------
DEBUG: Finished processing all variable groups
DEBUG: ------------ SUMMARY -------------
DEBUG:     land_binary_mask: 0 (min) 0 (max)
DEBUG: ---------------------------------
DEBUG: 		0 active elements
INFO: All points are in ocean
3
DEBUG: to be seeded: 100, already seeded 0
WARNING: The simulation stopped before requested end time was reached.
INFO: ========================
INFO: End of simulation:
INFO: arrays used as indices must be of integer (or boolean) type
INFO: Traceback (most recent call last):
  File "/home/quentin/opendrift-master/opendrift/models/basemodel.py", line 2001, in run
    self.release_elements()
  File "/home/quentin/opendrift-master/opendrift/models/basemodel.py", line 1143, in release_elements
    self.elements_scheduled.lat[indices])
  File "/home/quentin/opendrift-master/opendrift/models/basemodel.py", line 408, in store_present_positions
    self.previous_lon[IDs-1] = np.copy(lons)
  File "/home/quentin/miniconda2/lib/python2.7/site-packages/numpy/ma/core.py", line 3399, in __setitem__
    _data[indx] = dval
IndexError: arrays used as indices must be of integer (or boolean) type

INFO: 'The simulation stopped before requested end time was reached.'

ETIMING: (0.45s) __main__.TestStranding.test_stranding_roms

======================================================================
ERROR: test_stranding_3d (__main__.TestStranding)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_stranding.py", line 48, in test_stranding_3d
    o.run(end_time=reader_nordic.end_time, time_step=3600*6)
  File "/home/quentin/opendrift-master/opendrift/models/basemodel.py", line 2088, in run
    'first timestep. ' + self.get_messages())
ValueError: Simulation stopped within first timestep. 'The simulation stopped before requested end time was reached.'


======================================================================
ERROR: test_stranding_options (__main__.TestStranding)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_stranding.py", line 106, in test_stranding_options
    o.run(steps=28, time_step=3600*2)
  File "/home/quentin/opendrift-master/opendrift/models/basemodel.py", line 2088, in run
    'first timestep. ' + self.get_messages())
ValueError: Simulation stopped within first timestep. 'The simulation stopped before requested end time was reached.'


======================================================================
ERROR: test_stranding_roms (__main__.TestStranding)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_stranding.py", line 74, in test_stranding_roms
    o.run(end_time=reader_nordic.end_time, time_step=3600*36)
  File "/home/quentin/opendrift-master/opendrift/models/basemodel.py", line 2081, in run
    self.get_messages())
SystemExit: Simulation aborted. 'The simulation stopped before requested end time was reached.'


----------------------------------------------------------------------
Ran 3 tests in 5.752s

FAILED (errors=3)

**Comment by knutfrode** [comment]
I see that you have a quite old version of Basemap (1.0.7) and bright new versions of e.g. netCDF (1.4.0).
The newest configuration seems, however to work well for Python2:
https://travis-ci.org/OpenDrift/opendrift/builds/402663501?utm_source=github_status&utm_medium=notification

Could you please update your Basemap to version 1.1.0, and see if that helps?

And can you also please check that you have no local modifications in your OpenDrift folder?

**Comment by knutfrode** [comment]
Very good!
