### ISSUE TITLE
cant define reader buffer size

### ISSUE THREAD

**Issue by KKotzak** [OpenDrift/opendrift#83]
Hi,

I'm using the generic reader to get wind data and I'm getting the following warning:
_____________________________________________________
DEBUG: Setting buffer size 31 for reader nemo native, assuming a maximum
average speed of 1 m/s.
...
DEBUG: Setting buffer size 3 for reader
http://dataserver.cigom.org/thredds/dodsC/linea3/phy/cfsr/u10v10, assuming
a maximum average speed of 1 m/s
...
WARNING: Data block from
http://dataserver.cigom.org/thredds/dodsC/linea3/phy/cfsr/u10v10 not large
enough to cover element positions within timestep. Buffer size (3) must be
increased.
...
_________________________________________________________

Obviously, assuming 1 m/s maximum wind speed is too low and that is why
the buffer is not large enough. The question is now how we force a larger
buffer.

From the OpenOil code I found the reader.set_buffer_size() method:
 def add_reader(self, readers, variables=None):
…
# Horizontal buffer of reader must be large enough to cover
# the distance possibly covered by elements within a time step
reader.set_buffer_size(max_speed=self.max_speed)
___________________________________________________________________

But after setting manually the buffer size in my code, the buffer size keeps reverting automatically to 1m/s:
...
reader_oceanwind = reader_netCDF_CF_generic.Reader('http://dataserver.cigom.org/thredds/dodsC/linea3/phy/dfs52/u10v10')
reader_oceanwind.set_buffer_size(max_speed=40)
...

Any ideas how to avoid this buffer warning?
One more question, how can you select not the first hit but the second from the oil database when more than one matches are found? E.g I set the oil type to: oiltype = 'MAIN PASS BLOCK 306' and automatically selects the first hit.

Thanks
Kostas

**Comment by knutfrode** [comment]
Hi,

The buffer/max_speed mechanisms is not well documented, but there are some notes here:
https://github.com/OpenDrift/opendrift/wiki/Miscellaneous-tips#some-notes-about-performance

The buffer size for any reader is calculated automatically based on the expected maximum speed which has been postulated/anticipated for this specific model ("max_speed"), and the time_step of the reader. The buffer of a reader may be manually overriden like you did, or by simply setting it directly AFTER it has been added to the simulation object, e.g.
```
o.add_reader(r)
r.buffer = 10
```
Alternatively, you may also adjust the ```max_speed``` of the model before adding any readers:
```
o.max_speed = 5
```

If this still does not help, the buffer warning might be an misleading warning if the elements are just outside the coverage of this reader.

**Comment by knutfrode** [comment]
Regarding the oil type, the OpenDrift interface to ADIOS expects that oil names are unique, as is the case in the default database.
Thus if you add your own oils, and some have the same name, you will not be able to select the secondary ones.
Can you instead make unique names for your oil types?

**Comment by KKotzak** [comment]
Hi Knutfrode,

Thank you for the help. Following your instructions, I managed to set the buffer with r.buffer = xx after I added it to the simulation and it didn't revert back. I am still getting the warning message but it might be a misleading warning as you said since the simulation seems to work fine.

Thank you also for the feedback on the Oil database. I'll make sure they have unique names.

**Comment by knutfrode** [comment]
If results seem fine, I would think that there is no need to worry about that warning in this case.
OpenDrift gives presently some unnecessary and confusing warnings. I will clean that up one day.
