### ISSUE TITLE
Leeway model Jibe probability

### ISSUE THREAD

**Issue by ShamblingCrane** [OpenDrift/opendrift#84]
Would it be possible to make the jibe probability an argument to the `run` command for the Leeway drift model? It could be of interest to run simulations with a range of jibe probability, down to the extreme where it's zero.

**Comment by knutfrode** [comment]
I added now this possibility, except that ```jibeProbability``` is input of the ```seed_elements``` method, instead of the ```run``` method: https://github.com/OpenDrift/opendrift/commit/4859f1c78aa8829df0cbe980e3921dcadf1903a2
You may provide either a scalar (same for all elements), or an array with same length as the number of elements.
