### ISSUE TITLE
Leeway model - object property models

### ISSUE THREAD

**Issue by ShamblingCrane** [OpenDrift/opendrift#86]
The included leeway object properties (file OBJECTPROP.DAT) are the result of most recent works in the field; there are, however, both older models (based on earlier works), and cruder models (e.g. IAMSAR manual Vol.II), for which it may still be interesting to run simulations.

Could it be possible to include a configuration option to indicate the path to a specific file to read leeway properties from, provided it respected the format of OBJECTPROP.DAT? While it would be possible to just swap-in another file with the same name, that would feel somewhat dirty.

**Comment by knutfrode** [comment]
It seems that this possibility is already implemented (I had actually forgotten this):
https://github.com/OpenDrift/opendrift/blob/master/opendrift/models/leeway.py#L94

Thus it should probably work if you try this:
```
>>>l = Leeway(d=<OBJECTPROP-file>)
```

**Comment by ShamblingCrane** [comment]
Confirmed.

 I made a copy of the original file, renamed it, removed almost all categories and modified descriptions for the rest. Working as expected, showing only the remaining items with their relative descriptions. 

Closing this issue.
