### ISSUE TITLE
Leeway model object properties

### ISSUE THREAD

**Issue by ShamblingCrane** [OpenDrift/opendrift#87]
In the OBJECTPROP.DAT file, the 24th item (LIFE-RAFT-SB-10, Life Raft - Shallow ballast, canopy, Navy Sub Escape (SEIE) 1-man raft, NO drogue) has a positive left crosswind slope. I was wondering if this could be an error, since all entries have positive right crosswind slopes and negative left crosswind slopes, and this seems to be the only exception. Wouldn't it mean the left crosswind component would still push the raft to the right of the downwind direction?

**Comment by knutfrode** [comment]
The coefficients for item 24 and 25 (Navy Sub Escape (SEIE) 1-man raft, w/wo drogue) seem to be not from the original table by Allen and Plourde (1999), but added later based on [this work by Turner (2006)](www.dtic.mil/dtic/tr/fulltext/u2/a457525.pdf
)

The relevant data should be in their Table 4:
![leeway_seie_rafts](https://user-images.githubusercontent.com/5222051/47508168-e0d9aa00-d873-11e8-9057-236af691519f.png)

Numbers seem to be right, but it could be that the sign has not been imported correctly for these two special cases.
@oyvindbreivik, would you know?

**Comment by knutfrode** [comment]
It seems that the "unconstrained" coefficients are used from Turner (2006), despite that they recommend in their summary that the "constrained" coefficients should be used. The unconstrained coefficients may reveal "unphysical" behavior, although this should vanish among the large variability/spread.

I have written an email to Arthur Allen asking whether he recommends replacing the unconstrained with constrained coefficients.
For Turner (2006), this applies to 3 categories:
 LIFE-RAFT-SB-10
 LIFE-RAFT-SB-11
Navy Submarine EPIRB (SEPIRB)

**Comment by knutfrode** [comment]
Arthur Allen recommends actually to rather used the unconstrained coefficients, as the constrained coeffiecients will overpredict at higher winds speeds, and give more noise or uncertainty at very low wind speeds.
Thus these coefficients are then fine, and a slightly negative mean value is not a problem, as the spread is large.
