### ISSUE TITLE
Adding new Standard Name mappings

### ISSUE THREAD

**Issue by patcdaniel** [OpenDrift/opendrift#88]
Hi,

Is there a way of adding custom variable name mappings to a reader object? I ended up manually appending the Reader Parent class mapping dictionary and rerunning the setup.py. It worked but seemed cumbersome.

The high frequency radar derived surface current CF name that is used by IOOS is:

variable name: 'u'
standard_name: "surface_eastward_sea_water_velocity"
variable name: 'v'
standard_name: "surface_westward_sea_water_velocity"

example file:
http://hfrnet-tds.ucsd.edu/thredds/dodsC/HFR/USWC/2km/hourly/RTV/HFRADAR_US_West_Coast_2km_Resolution_Hourly_RTV_best.ncd

Best and Thanks,

Patrick

**Comment by knutfrode** [comment]
Hi,

I added now mapping for these variables in basereader.py:
https://github.com/OpenDrift/opendrift/commit/c83e0a18a80c13ffa0e41a9950d0d93a89495386

Please check if it works.
Note that if you install with ```python setup.py develop```then you don't need to rerun setup.py each time you modify the code.
