### ISSUE TITLE
Have modified ROMS reader

### ISSUE THREAD

**Issue by kthyng** [OpenDrift/opendrift#888]
Hi! A few months ago I modified the ROMS reader that is available in your repo in order to get it working for my application. I would say that some of the changes are specific to my use case and model output I'm using, and some were generally necessary. I'm willing to share the file, but not sure if it would be helpful, given this. Do you have a way of handling this? Thanks!

**Comment by knutfrode** [comment]
Hi!
Any changes that could be of general interest are highly welcome, but things that are specific to a user or case should preferably be kept outside of the main repository.
It is possible to make a [pull request](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/about-pull-requests), but it might be simpler in this case to send your version of the ROMS reader to me (knutfd@met.no), and then I can see what eventually would fit and not.

**Comment by kthyng** [comment]
Ok happy to make a PR, but I'll start with an email since I think the changes to the file are not particularly tidy and easy to tease apart. Thank you!
