### ISSUE TITLE
backward propagation

### ISSUE THREAD

**Issue by CaroMedel** [OpenDrift/opendrift#891]
Hi, 

I would like to implement a backward run. I use this:

lons = [-74.21, -73.96]
lats = [-43.40, -43.40]

o.schedule_elements([lons, lats], time)
o.run(duration=timedelta(days=2), time_step=-10800, outfile='file.nc') 

I get this error:

   self.elements_scheduled.ID = np.arange(1, len(elements) + 1)
AttributeError: 'list' object has no attribute 'ID'

Thanks,
Caro

**Comment by knutfrode** [comment]
Hi,

`schedule_elements` is an internal method that should not be used directly.
Instead you should use `o.seed_elements`

**Comment by CaroMedel** [comment]
Thanks!
