### ISSUE TITLE
Random number with OceanDrift

### ISSUE THREAD

**Issue by vincentcasseau** [OpenDrift/opendrift#904]
Hello,

I've noticed that random numbers are deterministic when drawn from the _update(self)_ function of the OceanDrift class and correspond to a seed number of 0. I am wondering why that is. Would you happen to have any explanations or recommendations?

Many thanks,
Vincent

----
To replicate this observation:

In `oceandrift.py`, I added
```python
print(np.random.random(1))
exit()
```
at the very beginning of the _update(self)_ function.
Then, I ran `example_constant_current.py` a couple of times for different instantiations of the OceanDrift object.

Run 1:
```python
o = OceanDrift(loglevel=20)
```

Output
```python
[0.5488135]
```

Run 2:
```python
o = OceanDrift(loglevel=20, seed=1)
```

Output
```python
[0.5488135]
```

Run 3:
```python
o = OceanDrift(loglevel=20, seed=None)
```

Output
```python
[0.5488135]
```

--------------------

Please note that setting the seed number in the OceanDrift constructor rather than the parent OpenDriftSimulation class as

```python
# Calling general constructor of parent class
super(OceanDrift, self).__init__(*args, **kwargs)
        
if 'seed' in kwargs:
    np.random.seed(kwargs['seed'])
```

and in `basemodel.py`

```python
# Using a fixed seed will generate the same random numbers
# each run, useful for sensitivity tests
# Use seed = None to get different random numbers each time
#np.random.seed(seed)
```

fixes the problem but I don't like it as these lines would need to be repeated in any child class of OpenDriftSimulation.

**Comment by knutfrode** [comment]
Indeed, there was a bug.
The cause was the config setting `seed:ocean_only` (defaults to True for OceanDrift), which creates a temporary/internal simulation object to check if points are seeded on land or not. This additional object thus resets the seed number.
This is now fixed in this commit: https://github.com/OpenDrift/opendrift/commit/89b76684e5d84ca645276b1ef71f26c33399248e

**Comment by vincentcasseau** [comment]
Perfect, it works. Thanks a lot!
