### ISSUE TITLE
Constant depth below sea level

### ISSUE THREAD

**Issue by Diego1991** [OpenDrift/opendrift#906]
Hi,

I am using OpenDrift and ROMS to simulate the path of a subsurface drifter moving at a constant depth of 3 m below sea level, and then compare with the observed trajectory. It is possible to use `seed_elements(z=-3)` but I was wondering if this is a constant depth relative to the mean sea level z=0 or if it is a fluctuating depth relative to the sea level affected by tides. The latter would be the desired behavior for this case. Is there something like `z='surface-3'` as there is for the seafloor? 

Also, the ROMS has the vertical component `w` in it, but I would like to prevent the elements from moving vertically for this case. I was planning planning to use the 3-D OceanDrift module but there may be a better choice. If not, after creating the ROMS reader, can I deactivate w?

Your help is much appreciated. Thank you,
Diego

**Comment by knutfrode** [comment]
Hi,

(I thought I had answered this one before, but cannot find it, thus answering again just in case...)
Presently, z is always relative to mean sea level. However, you may add `sea_surface_height_above_mean_sea_level` (or similar) as a required variable to your module. Then it should be a straightforward update inside your `update` method to make sure particle depths (`self.elements.z`) are relative to this, and not mean sea level.

Regarding disabling vertical motion, see this issue:
https://github.com/OpenDrift/opendrift/issues/909
