### ISSUE TITLE
How can I deactivate w

### ISSUE THREAD

**Issue by CaroMedel** [OpenDrift/opendrift#909]
Hi,

I'm using a CROCO output with the vertical component w, but I want to deactivated w. I want the particles to have a constant depth over time.
How can I deactivate w?

Thanks,
Caro

**Comment by knutfrode** [comment]
You can do:
`o.disable_vertical_motion()`

Basically this makes two config settings, to disable respectively vertical advection and vertical mixing:
```
o.set_config('drift:vertical_advection': False)
o.set_config('drift:vertical_mixing': False)
```

**Comment by CaroMedel** [comment]
Thanks!
