### ISSUE TITLE
Read NEMO files

### ISSUE THREAD

**Issue by trondkr** [OpenDrift/opendrift#91]
Hei. I have ocean U, V, S, T files originating from the NEMO model. Following the NEMO approach, each variable is in a separate file. Do you have a reader that supports reading NEMO files as input to OpenDrift (I could not find one)? In order to create one would my best approach be to base it on the ROMS reader file? Thanks, Knut-Frode! Cheers, Trond

**Comment by knutfrode** [comment]
Unfortunately this was not answered. Please re-open if still relevant.
