### ISSUE TITLE
Import new readers

### ISSUE THREAD

**Issue by Rbiton1** [OpenDrift/opendrift#916]
Hi,
I want to create an oil spill simulation whether in the gulf of Mexico or between France an Corsica. I have tried for two days now to import new readers, each time when I launch the program there are missing info or the period don't correspond. If I do the simulation in the gulf of Mexico I need for information for the 2010-04-10 and following days, for the Corsica one, I need for info for the 2018-10-08 and following days. I have tried to upload datas from the CMEMS, don't know if it's the right way to do it...

**Comment by knutfrode** [comment]
Hi,
Your readers/files must cover your seeding locations in both time and space.
The error message from the output log (debug mode) should tell you what eventually is the problem.

**Comment by Rbiton1** [comment]
With most of my tries, x_sea_water_velocity and y_sea_water_velocity were missing but these info seems to be in the file I downloaded.
Is it preferable to add a reader by downloading it or with a link ?
Thanks for your quick response.

**Comment by knutfrode** [comment]
Does the actual variables have attributes called `standard_name` which are respectively `x_sea_water_velocity` and `y_sea_water_velocity` ?
If not, the files are not CF-compliant, and you need to use a variable mapping like in this example:
https://opendrift.github.io/gallery/example_macondo.html

This is the same whether using a local file or a Thredds URL.

**Comment by Rbiton1** [comment]
Thank you for your help, it seems to work with the variable mapping. 
I should be able to do what I want now.
