### ISSUE TITLE
Unable to read 'upward_sea_water_velocity' using reader_ROMS_native

### ISSUE THREAD

**Issue by mevo-creator** [OpenDrift/opendrift#919]
Hei, I've used Opendrift previously to track particles on the Norwegian Continental Shelf (NCS), I need to run some simulations again. Earlier I was reading ocean currents data using 

`SVIM = reader_ROMS_native.Reader('https://thredds.met.no/thredds/dodsC/nansen-legacy-ocean/svim_daily_agg')
o.add_reader(SVIM, variables = ['x_sea_water_velocity', 'y_sea_water_velocity', 'upward_sea_water_velocity','sea_floor_depth_below_sea_level'])`

But now using the above code gives an error as 

`Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\mevo\opendrift\opendrift\models\basemodel.py", line 924, in add_reader
    raise ValueError(
ValueError: Reader roms native does not provide variables: ['upward_sea_water_velocity']` 

It seems like things have changed in the latest version? I need to track particles in 3 dimensions so is there some other model/reader that needs to be used to read 'upward_sea_water_velocity'?

Thanks

**Comment by mevo-creator** [comment]
Hi @knutfrode , could you please help with the above error?

**Comment by knutfrode** [comment]
It seems that the later years of the model have been run without storing upward velocity (and vertical diffusivity), and thus the aggregate is then (automatically) missing these variables for the whole time series.
The later years may be re-run, but I cannot tell when this will be available, this is outside of my control.

In the meantime, the only options seems to be to add each monthly file with daily data:
https://thredds.met.no/thredds/catalog/nansen-legacy-ocean/SVIM/catalog.html

But there may also be other models around that cover the given area and time with needed variables.

**Comment by mevo-creator** [comment]
Ohh..that was unlucky cause earlier I've successfully added 'upward_sea_water_velocity' variable using 'reader_ROMS_native' and was able to run long term simulation. So it seems like the upward_sea_water_velocity is stored in the model output for most of the time series. 

Anyway, I need to run simulations for at least 1-2 years. So by adding each monthly file you mean to download these monthly files, club them together and read currents from local disk? could it be feasible to do this for 1-2 years of simulation considering the size of files or some other constraints? 

My objective is to see the vertical distribution of particles over time. These particles are assumed as polymers dissolved in the water and the de-polymerization rate of these polymers is dependent on the intensity of solar irradiation, which changes with depth. So, upward_sea_wter_velocity and tracking particles in three dimensions become important. Please suggest if there are some other alternatives to run such simulation within Opendrift. 
Thanks

**Comment by mevo-creator** [comment]
Ohh...that was unfortunate...because earlier it was possible to read 'upward_sea_water_velocity' so it seems like this variable is stored for most of the time series. The particles are assumed as polymers dissolved in water and the de-polymerization rate is dependent on solar irradiation, which will change with depth. Hence, vertical diffusivity and upward_sea_water_velocity become important.

I need to track particles for atleast 2 years, so if I understand correctly another option, would it be feasible to download the monthly files, combine them and read the ocean currents data from the local disk....given the size of the files or some other constraints...?

The particles release location is around Stavanger/Bergen, so essentially area covering North/Norwegian/Barents sea (as was the case with SVIM data). There are some Threads available in [this example](https://opendrift.github.io/gallery/example_long_global_thredds.html) and [this example](https://opendrift.github.io/gallery/example_thredds_resources.html). Could it be possible to use one of these thredds for this purpose? It would be helpful to get some suggestion on this, thanks so much!

**Comment by mevo-creator** [comment]
Hi @knutfrode , if possible could you please make some suggestions for the above query? Thanks

**Comment by knutfrode** [comment]
It seems like neither HYCOM or MERCATOR provides vertical currents.
Thus the only options seems to be to use the monthly files of SVIM that do actually include vertical current (before 2018 I believe).
You can either download files locally (but could use subsetting to reduce amount of data), or use individual thredds URL directly.
But if combining the thredds URLs, there might be an issue that the last time of one month is 12 UTC on the last day, whereas the next one start at 12 UTC of the first day of the month - thus an apparent "gap" of 1 day. Not sure how to fill that gap, so best might be to download files and merge them somehow to a (very large) physical file.

**Comment by mevo-creator** [comment]
ok..I'll try to create a physical file. 
It would be helpful if the SVIM dataset can somehow be accessed with two different URLs, one before 2018 when vertical currents are available and the other after 2018 or if it is possible to re-run the model with vertical currents data for last few years. Not sure how feasible either of these options could be. 
Thank you for the suggestion!

**Comment by mevo-creator** [comment]
ok..I'll try to create a physical file, thank you for the suggestion.

It would be helpful if the SVIM dataset can somehow be accessed with two different URLs, one before 2018 when vertical currents are available and the other after 2018 or if it is possible to re-run the model with vertical currents data for last few years. Not sure how feasible either of these options could be.
