### ISSUE TITLE
Error reading file - Basemap

### ISSUE THREAD

**Issue by AndresSepulveda** [OpenDrift/opendrift#92]
Hi, we are using a (large) ROMS file and we get the following problem 

python opendrift_oneyear.py 
INFO: OpenDriftSimulation initialised (version 1.0.5)
INFO: Opening dataset: /media/cristian/TOSHIBA/oneyear.nc
INFO: Opening file with Dataset
INFO: 'gls_cmu0'
INFO: Did not find complete set of GLS parameters
INFO: Ocean time given as seconds relative to start Setting artifical start time of 1 Jan 2000.
INFO: Making Splines for lon,lat to x,y conversion...
DEBUG: Setting buffer size 831 for reader roms native, assuming a maximum average speed of 5 m/s.
DEBUG: Setting buffer size 168 for reader roms native, assuming a maximum average speed of 1 m/s.
DEBUG: roms native is unprojected, cannot use for common grid
DEBUG: Added reader roms native
INFO: Setting SRS to latlong, since not defined before.
DEBUG: Calculation SRS set to: +units=m +proj=latlong +ellps=WGS84
DEBUG: ------------------------------------------------------
DEBUG: Software and hardware:
DEBUG:   19 GB memory
DEBUG:   4 processors (x86_64)
DEBUG:   Basemap version 1.1.0
DEBUG:   NumPy version 1.15.4
DEBUG:   SciPy version 1.1.0
DEBUG:   Matplotlib version 2.2.3
DEBUG:   NetCDF4 version 1.4.1
DEBUG:   Python version 2.7.15 |Anaconda, Inc.| (default, May  1 2018, 23:32:55) [GCC 7.2.0]
DEBUG: ------------------------------------------------------
INFO: Config validation OK
DEBUG: No output file is specified, neglecting export_buffer_length
INFO: Fallback values will be used for the following variables which have no readers: 
INFO: 	x_wind: 0.000000
INFO: 	y_wind: 0.000000
INFO: Duration, steps or end time not specified, running until end of first reader: 2018-10-22 12:00:00
INFO: Adding a dynamical landmask (resolution "h") based on assumed maximum speed of 1 m/s. Adding a customised landmask may be faster...
DEBUG: Creating Basemap...
Traceback (most recent call last):
  File "opendrift_oneyear.py", line 60, in <module>
    o.run(time_step=86400)
  File "/home/cristian/Documentos/opendrift-master/opendrift/models/basemodel.py", line 2041, in run
    projection='merc')
  File "/home/cristian/Documentos/opendrift-master/opendrift/readers/reader_basemap_landmask.py", line 64, in __init__
    resolution=resolution, projection=projection)
  File "/home/cristian/anaconda2/lib/python2.7/site-packages/mpl_toolkits/basemap/__init__.py", line 704, in __init__
    llcrnrlon = _validated_or_none(llcrnrlon, 'llcrnrlon', -360, 720)
  File "/home/cristian/anaconda2/lib/python2.7/site-packages/mpl_toolkits/basemap/__init__.py", line 525, in _validated_or_none
    return _validated_ll(param, name, minval, maxval)
  File "/home/cristian/anaconda2/lib/python2.7/site-packages/mpl_toolkits/basemap/__init__.py", line 518, in _validated_ll
    (name, minval, maxval))
ValueError: llcrnrlon must be between -360.000000 and 720.000000 degrees
cristian@cristian:~/Documentos/PartiMOSA$

**Comment by AndresSepulveda** [comment]
Sorry, I don know what why the screen output looks like that.

**Comment by knutfrode** [comment]
Hi,

One quick fix could be to use the landmask directly from the ROMS file (if it is included). This would also be much faster than using a vector coastline from Basemap. This can be achieved by setting:
```o.set_config('general:use_basemap_landmask', False)```

Other workarounds using Basemap landmask could be to either:
- specify a Basemap reader explicitly, covering the area of interest, and add this to your simulation object, as in [this example](https://github.com/OpenDrift/opendrift/blob/master/examples/example_backandforth.py#L17). Select then an appropriate resolution, "full" (f) or "high" (h) would take a lot of time/memory if the area is large. 
- lower the "max_speed" parameter, which is used to estimate the size of the automatically created Basemap, e.g. ```o.max_speed = .1```

If you can make available the output from ```$ readerinfo.py <ROMSfile.nc>``` or ```>>> print ROMS_reader```, I could try to make a "safety-net" in the code for longitudes outside -360,720.

**Comment by AndresSepulveda** [comment]
This worked, thanks!

o.max_speed = .1

The first option 

o.set_config('general:use_basemap_landmask', False)

gave us an error. Notice we use ROMS_AGRIF, and the only landmask available is

	float mask_rho(eta_rho, xi_rho) ;

might this be a problem?

INFO: OpenDriftSimulation initialised (version 1.0.2)
INFO: Opening dataset: /media/mosa/TOSHIBA/oneyear.nc
INFO: Opening file with Dataset
INFO: 'gls_cmu0'
INFO: Did not find complete set of GLS parameters
INFO: Ocean time given as seconds relative to start Setting artifical start time of 1 Jan 2000.
INFO: Making Splines for lon,lat to x,y conversion...
DEBUG: Setting buffer size 831 for reader roms native, assuming a maximum average speed of 5 m/s.
DEBUG: Setting buffer size 168 for reader roms native, assuming a maximum average speed of 1 m/s.
DEBUG: roms native is unprojected, cannot use for common grid
DEBUG: Added reader roms native
INFO: Setting SRS to latlong, since not defined before.
DEBUG: Calculation SRS set to: +units=m +proj=latlong +ellps=WGS84
INFO: 
==============================================
drift:max_age_seconds [None] float(min=0, default=None)
drift:scheme [euler] option('euler', 'runge-kutta', default='euler')
drift:wind_drift_factor [0.02] float(min=0, max=1, default=0.02)
drift:stokes_drift [True] boolean(default=True)
drift:current_uncertainty [0.1] float(min=0, max=5, default=.1)
drift:wind_uncertainty [1.0] float(min=0, max=5, default=1)
drift:relative_wind [False] boolean(default=False)
drift:use_tabularised_stokes_drift [False] boolean(default=False)
drift:tabularised_stokes_drift_fetch [25000] option(5000, 25000, 50000, default=25000)
general:basemap_resolution [h] option('f', 'h', 'i', 'c', default='h')
general:minimise_map_whitespace [False] boolean(default=False)
general:coastline_action [stranding] option('none', 'stranding', 'previous', default='stranding')
==============================================

Traceback (most recent call last):
  File "oneyear.py", line 31, in <module>
    o.set_config('general:use_basemap_landmask', False)
  File "/home/mosa/opendrift/opendrift/models/basemodel.py", line 257, in set_config
    raise ValueError('Wrong configuration')
ValueError: Wrong configuration

**Comment by knutfrode** [comment]
This option seemed to fail since your version of OpenDrift is fairly old (1.0.2, present is 1.0.5).
If you update, it should hopefully work. There are several other [small improvements](https://github.com/OpenDrift/opendrift/issues/32#issuecomment-358269067) since 1.0.2, and I believe backward compatibility should be ok.

**Comment by AndresSepulveda** [comment]
ok, thanks, I will update. Just for the record, the second option (defined area) fails in the same way as the first (same version problem).
and
readerinfo.py gives

mosa@parti-mosa:/var/www/html/MOSAv5/python_folder$ readerinfo.py oneyear.nc 
Testing /home/mosa/opendrift/opendrift/readers/reader_netCDF_CF_generic.pyc...
...not applicable.
Testing /home/mosa/opendrift/opendrift/readers/reader_ROMS_native.pyc...
===========================
Reader: roms native
Projection: 
  None
Coverage: [pixels]
  xmin: 0.000000   xmax: 504.000000   step: 1   numx: 505
  ymin: 0.000000   ymax: 602.000000   step: 1   numy: 603
  Corners (lon, lat):
    (-79.00, -40.99)  (-72.00, -40.99)
    (-79.00, -47.00)  (-72.00, -47.00)
Vertical levels [sigma]: 
  [-0.98809522 -0.96428573 -0.94047618 -0.91666669 -0.89285713 -0.86904764
 -0.84523809 -0.8214286  -0.79761904 -0.77380955 -0.75       -0.72619045
 -0.70238096 -0.6785714  -0.65476191 -0.63095236 -0.60714287 -0.58333331
 -0.55952382 -0.53571427 -0.51190478 -0.48809522 -0.4642857  -0.44047618
 -0.41666666 -0.39285713 -0.36904761 -0.34523809 -0.32142857 -0.29761904
 -0.27380952 -0.25       -0.22619048 -0.20238096 -0.17857143 -0.15476191
 -0.13095239 -0.10714286 -0.08333334 -0.05952381 -0.03571429 -0.01190476]
Available time range:
  start: 2017-09-30 11:30:08   end: 2018-10-22 12:00:00   step: 2 days, 0:29:52
    192 times (-194 missing)
Variables:
  sea_floor_depth_below_sea_level
  sea_water_salinity
  sea_water_temperature
  x_sea_water_velocity
  y_sea_water_velocity
  sea_surface_height
===========================

**Comment by knutfrode** [comment]
I believe this should work after you update. Probably this older version of OpenDrift tries to add an automatic Basemap reader even if you added one manually.

**Comment by AndresSepulveda** [comment]
Confirmed. With version 1.0.5 

o.set_config('general:use_basemap_landmask', False)

works fine. 

However without that, and without the  o.max_speed=0.1 option, it fail for version 1.0.5 and 1.0.2.

Could  it be something related to Basemap itself?

**Comment by AndresSepulveda** [comment]
Here is a file with three time steps

http://ronin.dgeo.udec.cl/opendrift/opendrift.nc.gz

Thanks in advance,

Andres

**Comment by knutfrode** [comment]
This is a bit strange, when I run ```$ readerinfo.py <ROMSfile>```, it reports the following variables:
```Variables:
  sea_floor_depth_below_sea_level
  land_binary_mask
  sea_water_salinity
  sea_water_temperature
  x_sea_water_velocity
  y_sea_water_velocity
  sea_surface_height
```
whereas in your case (above), ```land_binary_mask``` was missing.
Did you make any lokal modifications to your ROMS reader?

**Comment by knutfrode** [comment]
Note: I made now [an update](https://github.com/OpenDrift/opendrift/commit/4c579b066c9edfbb951deecffe0521735bf34e3d) to the ROMS native reader, which improves its performance quite a bit, by re-using coefficients which are used to convert from sigma- to z-coordinates.
Thus I recommend updating your OpenDrift once more to benefit from this.
