### ISSUE TITLE
access to the equations

### ISSUE THREAD

**Issue by Rbiton1** [OpenDrift/opendrift#923]
Hi, I have to make an oral presentation about oil spills so I have to make a simulation and explain the physical equations behind it. I already did the simulation I wanted with OpenDrift, I would now know if it's possible to have access to the equations used by the program so I could explain exactly what my program do. On the OpenDrift website the Langragian and Eulerian methods are quoted without much explanations and I didn't found any equations while searching in all the docs in the OpenDrift file I downloaded.
thanking you in advance

**Comment by knutfrode** [comment]
Hi,
You may find the relevant equations in some of the papers here: https://opendrift.github.io/references.html
E.g.:
https://agupubs.onlinelibrary.wiley.com/doi/10.1029/2020JC016499
https://os.copernicus.org/articles/14/1581/2018/

But also in the source code itself:
https://opendrift.github.io/_modules/opendrift/models/openoil/openoil.html#OpenOil

**Comment by Rbiton1** [comment]
Thank you for these links, it will for sure help a lot
