### ISSUE TITLE
random initial values

### ISSUE THREAD

**Issue by CaroMedel** [OpenDrift/opendrift#926]
I'm working with the LarvalFish model and I want the variable " weight " to start with random values, not fixed ones. I would like the particles take random initial values between 0.1 and 0.3. Is it possible?

**Comment by knutfrode** [comment]
Hi, yes you can do as in [this example](https://opendrift.github.io/gallery/example_drifter.html) (with `weigth` instead of `wind_drift_factor`):

```
wind_drift_factor = np.random.uniform(0, 0.06, 2000)
o.seed_elements(4.7, 59.9, radius=3000, number=2000,
                time=reader_current.start_time,
                wind_drift_factor=wind_drift_factor)
```

**Comment by CaroMedel** [comment]
It works. Thank you for your help
