### ISSUE TITLE
CMES data access

### ISSUE THREAD

**Issue by ocecept** [OpenDrift/opendrift#934]
Hi all;

Is the CMEMS example working in the last version? 

I use to provided user and passwrd explicitly in older versions, but I can not do it now. 

I tried to created the  .netrc file as suggested: 

machine nrt.cmems-du.eu
login myuser
password mypass

I keep it at my home folder, but the access to the CMEMS does not work. 

I usually download all the data for research but the online access is very good for lectures. 

Many thanks

Carlos

**Comment by knutfrode** [comment]
Hi,
Yes, it is working, but some additional information should probably be added to the example description:

1. The `.netrc` file should be unreadable to others: `chmod 500 .netrc`
2. It is also necessary to have a file `.dodsrc` in your home folder, which should contain a line like:
`HTTP.NETRC=<path to your .netrc-file>`

Please tell me if this works for you, and I will add this piece of information to the example description.

**Comment by ocecept** [comment]
Hi,

After I did what you mentioned, now it works perfectly! 

I had changed the .netrc to unreadable before, so adding the .dodsrc looks to do the trick. 

Thanks a lot again

**Comment by CalumF** [comment]
Hi,

Just a small thing - in the docs (opendrift/examples/example_long_cmems.py) the file is a .dodrsc rather than .dodsrc - I'd not come across them before so it took me a sec to work out!

**Comment by knutfrode** [comment]
You are right, there was a typo!
This is now fixed: https://github.com/OpenDrift/opendrift/commit/6031e172f49a96cab1611705e0070bca7f0869ca
