### ISSUE TITLE
A Problem about ‘Reader’

### ISSUE THREAD

**Issue by nkburridge** [OpenDrift/opendrift#94]
Dear professor:
I am an undergraduate student from Nanjing University. I encountered a problem while **reading the Ocean model data**.The detailed error message of the problem is posted as follows:
```
reader_norkyst = reader_netCDF_CF_generic.Reader(lw.test_data_folder() + 
    '16Nov2015_NorKyst_z_surface/norkyst800_subset_16Nov2015.nc')
INFO: Opening dataset: D:\MY_PROGRAM\Anaconda3\lib\site-packages\opendrift-1.0.5-py3.6.egg\tests\test_data\16Nov2015_NorKyst_z_surface/norkyst800_subset_16Nov2015.nc
INFO: Opening file with Dataset
DEBUG: Finding coordinate variables.
DEBUG: Parsing variable: X
DEBUG: Parsing variable: Y
DEBUG: Parsing variable: depth
DEBUG: Parsing variable: projection_stere
DEBUG: Parsing variable: time
DEBUG: Parsing variable: u
DEBUG: Parsing variable: v
Traceback (most recent call last):

  File "<ipython-input-18-acd296fb67b3>", line 2, in <module>
    '16Nov2015_NorKyst_z_surface/norkyst800_subset_16Nov2015.nc')

  File "D:\MY_PROGRAM\Anaconda3\lib\site-packages\opendrift-1.0.5-py3.6.egg\opendrift\readers\reader_netCDF_CF_generic.py", line 208, in __init__
    super(Reader, self).__init__()

  File "D:\MY_PROGRAM\Anaconda3\lib\site-packages\opendrift-1.0.5-py3.6.egg\opendrift\readers\basereader.py", line 145, in __init__
    self.proj = pyproj.Proj(self.proj4)

  File "D:\MY_PROGRAM\Anaconda3\Lib\site-packages\pyproj\__init__.py", line 358, in __new__
    return _proj.Proj.__new__(self, projstring)

  File "_proj.pyx", line 84, in _proj.Proj.__cinit__

RuntimeError: b'argument not numerical or out of range'
```

**Comment by vic1309** [comment]
I'm facing the same problem here. reader_arome is working well, but when I run reader_norkyst I receive the following message:

RuntimeError: b'argument not numerical or out of range'

Best wishes

**Comment by knutfrode** [comment]
This might look like a conda-problem.
Does the testall-script succed with all the tests?
Could you please update your version of OpenDrift, and report the output you get from:
```
>>> import opendrift
>>> print opendrift.versions()
```

@nkburridge , did you find a solution to this problem, as you closed the issue?

**Comment by nkburridge** [comment]
Hi,
I have solved this problem on my computer. Generally speaking, I think the reason is the installation of related packages and path problem. I use Anaconda and Spyder. Firstly, installing Opendrift by Anaconda Prompt. Then, I  launch Spyder through Anaconda(Donn't start spyder through double-click), setting the path in PYPHONPATH manager, and the error disappears. I also changed some environment variables about anaconda. So, you can try to change environment variables or PYPHONPATHs or Starting sequence. @knutfrode @vic1309

**Comment by knutfrode** [comment]
The method ```versions()``` was added two days ago, so you might need to update to the latest version.

However, according to the comment by nkburridge above, this seems not a to be an OpenDrift-problem, but rather related to installation of other packages with conda, and perhaps the setting of PYTHONPATH.

**Comment by knutfrode** [comment]
This seems to be a problem with version 5.0.0 of Proj4: https://github.com/OSGeo/proj.4/issues/1191

For me, it helped to downgrade proj4 with ```conda install proj4=4.9.3```

**Comment by knutfrode** [comment]
A workaround for this bug is now implemented in OpenDrift: https://github.com/OpenDrift/opendrift/commit/f11f1b6e521d8f9c5bb20543384cac87b767e895

So please update to the latest version of OpenDrift if you face this problem.
