### ISSUE TITLE
Problem with animation in OpenDrift 1.0.5

### ISSUE THREAD

**Issue by AndresSepulveda** [OpenDrift/opendrift#95]
Hi, I get the following message when trying to make an animation

INFO: Saving animation to /var/www/html/MOSAv5/python_folder/simulation.gif...
INFO: Making animated gif...
INFO: Could not save animation:
INFO: save() got an unexpected keyword argument 'clear_temp'
DEBUG: Traceback (most recent call last):
  File "/home/mosa/opendrift/opendrift/models/basemodel.py", line 3620, in _save_animation
    anim.save(filename, fps=fps, clear_temp=False)
TypeError: save() got an unexpected keyword argument 'clear_temp'

DEBUG: Time to make animation: 0:00:44.216971

My software versions are

INFO: OpenDriftSimulation initialised (version 1.0.5)
DEBUG: Software and hardware:
DEBUG:   7 GB memory
DEBUG:   4 processors (x86_64)
DEBUG:   Basemap version 1.1.0
DEBUG:   NumPy version 1.13.3
DEBUG:   SciPy version 0.19.1
DEBUG:   Matplotlib version 2.1.1
DEBUG:   NetCDF4 version 1.3.1
DEBUG:   Python version 2.7.15rc1 (default, Nov 12 2018, 14:31:15) [GCC 7.3.0]

If I modify, in /home/mosa/opendrift/opendrift/models/basemodel.py,

    anim.save(filename, fps=fps, clear_temp=False)
to
    anim.save(filename, fps=fps) # , clear_temp=False)

the computer froze.

Any help on this topic?

Regards,

Andres

**Comment by knutfrode** [comment]
The ```clear_temp``` is apparently for old versions of Matplotlib only, so I now [removed that](https://github.com/OpenDrift/opendrift/commit/723ee4858941edef601f2c5b65401d719f219ec4), like you did.

I have no idea why it froze on your computer. However, if the simulation has many timesteps (> 100), I think gif is anyway not a good option, as files become very large.
Could you use mp4 instead? Then you need ffmpeg library.

I can recommend this online tool to convert between mp4 and gif, with high quality and minimised file size: https://ezgif.com/video-to-gif

**Comment by AndresSepulveda** [comment]
Thanks! The mp4 option works fine. I am away from my office, so next week I will investigate why it froze. Maybe it was not related to this change in the code.
