### ISSUE TITLE
FileNotFoundError: [WinError 2] The system cannot find the file specified

### ISSUE THREAD

**Issue by Nichsouz** [OpenDrift/opendrift#951]
Dear all,

I am facing a boring FileNotFoundError whenever I try to animate_profile a model. If I try making it like o.animate_profile() it works well and I can see in Python output windows. But if I try exporting it in filename="xxxxxx.mp4" it retrieves the error message.
I'm afraid it all began when I reinstalled conda and opendrift in my computer. Could it be a new version conflict?

Thanks in advance. Below I posted a screenshot of the occurrence. 

![image](https://user-images.githubusercontent.com/74186191/183841405-3261f274-b2af-479e-ab59-90029af3e0ac.png)

**Comment by knutfrode** [comment]
Similar works fine for me, so it could well be a problem with your installation.

But before reinstalling, you'd might check that the folder that you are writing the file to actually exists.

It might also be enough to reinstall the conda environment, and not the whole anaconda:
```
$ conda activate
$ conda env remove -n opendrift
$ conda env create -f environment.yml
$ conda activate opendrift
$ pip install -e .
```

**Comment by Nichsouz** [comment]
It worked. 

During my reinstallation, I've put conda in another HD. Apparently, the environment.yml was not working effectively. After some adjustments, it worked and now it is pretty fine. It was a conda malfunction, not opendrift. 

Many thanks.
