### ISSUE TITLE
Forced wind time series

### ISSUE THREAD

**Issue by SHENH-BIO** [OpenDrift/opendrift#955]
Hi all. I am looking for a way to let the opendrift to respond a user defined wind time series (say from a buoy observation), which is homogeneous in model spatial domain. I see in o.set_config, there is an option to set constant or fallback, but those are for constant winds at all time. Is there a way we can set a time series for the wind forcing?  And also is it possible to edit the variables from the readers? Say, readu=reader_netCDF_CF_generic.Reader('u.nc'), I want to change readu['x_sea_water_velocity'][ix,iy] into 0.0. If so, how? Thank you.

**Comment by SHENH-BIO** [comment]
Hi Knut-Frode,
Thank you for the information. It is very helpful. Just to clarify. I found your test case here: https://github.com/OpenDrift/opendrift/blob/12c58d1e220541d39ecdda92baeac6b67aadcf18/tests/readers/test_readers.py, where time series and wind speed/direction is defined. There is no information on the grid (lon,lat). Does the o.run automatically put the time series to each/every grid from, say, current data grid?

**Comment by SHENH-BIO** [comment]
For anyone who may be interested: 
Update: I tested the function of reader_timeseries, it turns out the function automatically assigned a global lon [-180,180], lat [-90, 90]. Thus it can be called before or after the call of any other datasets.

**Comment by knutfrode** [comment]
reader_timeseries does not have a grid, values are valid for all positions.
Variation is only in time.
