### ISSUE TITLE
Some Problems about Ocean Environmental Data used to Drive the OpenDrift

### ISSUE THREAD

**Issue by nkburridge** [OpenDrift/opendrift#96]
Dear Professor:
I am learning _OpenDrift_ by establishing a new drifting simulation in the [Yellow Sea](https://en.wikipedia.org/wiki/Yellow_Sea) region. However, I encountered some problems in the acquisition and processing of environmental data.

I downloaded the current data( Spatial Resolution is 1/3°, Temporal Resolution is 5 days ) from [OSCAR ](https://podaac.jpl.nasa.gov/dataset/OSCAR_L4_OC_third-deg)and the wind data from [ERA5 Dataset](https://cds.climate.copernicus.eu/cdsapp#!/dataset/reanalysis-era5-single-levels?tab=overview). The coverage of these data is global.

When I used these data to build a drifting model(Leeway), I met a problem of failing to get environmental variables. I think the problem rise from that these data need to be clipped, projected, and sampled. I tried to use tools like Python and ArcGIS to acquire processed data, which can normally drive a drifting model, but I failed. 

So I want to ask :
**1. What are the requirements for the format, spatio-temporal resolution and processing methods of environmental data(current, wind etc.) in OpenDrift?**
**2. For the problem I mentioned above, are there any systematic and convenient data processing methods/tools?**
@knutfrode 
Thank you very much.

**Comment by knutfrode** [comment]
Very good.
Merry Christmas to you too!
