### ISSUE TITLE
pip insall crashes because of unreleased gdal version

### ISSUE THREAD

**Issue by Boorhin** [OpenDrift/opendrift#969]
in pyproject.toml, line 38 you have
`GDAL = {version = "^3.5.1", optional = true}`
This version has not been released in a stable version so the install of opendrift triggers all kind of gdal error messages on my ubuntu 22.04 LTS. I have changed that to 3.3.1 which is working well since a while as I doubt there is need of experimental stuff.
`GDAL = {version = "^3.3.1", optional = true}`
And it works like a charm.

**Comment by gauteh** [comment]
Thanks, should hopefully be fixed now! We are working on getting opendrift into conda-forge.

https://github.com/conda-forge/staged-recipes/pull/20346
