### ISSUE TITLE
 Static 2D current field reader for 2d lon/lat possible?

### ISSUE THREAD

**Issue by SHENH-BIO** [OpenDrift/opendrift#976]
**Problem**: It seems the Static 2D current field reader (opendrift.readers.reader_constant_2d) only works for 1d lon/lat. I tried to repeat the example Knut-Frode Dagestad provided (ref: #955 ), it works fine for the example. However, when I commented out the 1d lon/lat, and used the 2d lon/lat. The simulation was through but the particles don't move as expected. The problem seems to be from the interpolation stage: "**_13:26:19 WARNING opendrift.models.basemodel: operands could not be broadcast together with shapes (968,) (30,)_** " . 
Which may be a problem originated from matrix multiplication in Python. A thread online suggested numpy.dot() might help.
Any suggestions?

==============**code** ====================
```
# Static 2D current field =======================

from datetime import datetime, timedelta
import numpy as np

from opendrift.readers.reader_constant_2d import Reader
from opendrift.models.oceandrift import OceanDrift

#Constructing a static, rotating ocean current field, 
lon, lat = np.meshgrid(np.linspace(2,6,30), np.linspace(59,62,30))
lon0 = 4
lat0 = 60.5
u = -(lat-lat0)/np.sqrt((lon-lon0)**2 + (lat-lat0)**2)
v = (lon-lon0)/np.sqrt((lon-lon0)**2 + (lat-lat0)**2)
lon1d = np.linspace(2,6,30)
lat1d = np.linspace(59,62,30)

r = Reader(x=lon, y=lat, proj4='+proj=latlong',
           array_dict = {'x_sea_water_velocity': u, 'y_sea_water_velocity': v})

o = OceanDrift(loglevel=20)
o.set_config('environment:fallback:land_binary_mask', 0)
o.add_reader(r)
o.seed_elements(lon=3, lat=60.5, number=1000, radius=30000, time=datetime.now())
o.run(duration=timedelta(hours=72))
o.animation(fast=True)

```

**Comment by knutfrode** [comment]
This reader presently only supports x/y (lon/lat) as 1D arrays. For 2D, an interpolation routine must be added. This may be done in the future, as needed.
