### ISSUE TITLE
openoil spilled mass

### ISSUE THREAD

**Issue by oceandiff** [OpenDrift/opendrift#987]
Hi all,
It is possible to impose the initial spilled mass, or assign a value of mass to each paticles?
Thank you in advance

**Comment by knutfrode** [comment]
Yes, you can assign a mass to each element by specifying `mass` (in kg) when seeding (scalar if all particles shall have same mass, or array for individual mass).
Alternatively you may provide the parameter `m3_per_hour` to specify the total volume of oil, to be divided evenly among the specified number of elements. The mass is then calculated from the volume after the oil density is obtained from the oil library for the given oil type. If spill is instantaneous, `m3_per_hour` is interpreted as `m3`

**Comment by oceandiff** [comment]
Thanks for your quick and accurate reply.
Best regards

**Comment by oceandiff** [comment]
I've another question, 
Is it possible to use an oil with known characteristics but not present in the list? I have density, kinematic viscosity and dynamic viscosity.
Thanks in advance
