### ISSUE TITLE
personalized oil type 

### ISSUE THREAD

**Issue by oceandiff** [OpenDrift/opendrift#989]
Hi all,
is it possible to use an oil with known characteristics but not present in the list? I have density, kinematic viscosity and dynamic viscosity and there is no oil with the same characteristics in the noaa ADIOS dataset. There is a way to create a personalized list and use it or something like that?
Thanks in advance

**Comment by gauteh** [comment]
Hi,

you can specify the oil type as a JSON string in the same format as the ADIOS database (https://adios.orr.noaa.gov/oils) by using this method: https://opendrift.github.io/autoapi/opendrift/models/openoil/index.html#opendrift.models.openoil.OpenOil.set_oiltype_by_json .

See this list of extra oils that opendrift provides that hopefully eventually will be part of ADIOS, or for some reason cannot be added to the database: https://github.com/OpenDrift/opendrift/blob/master/opendrift/models/openoil/adios/extra_oils/AD03128.json

If the oil type is of general interest it might be worth submitting it to the ADIOS database.

**Comment by oceandiff** [comment]
Thanks Gauteh,
i've understand how to write the json file with the specific oil characteristics, but how can I call the json personalized file instead of ADIOS db? 
thanks

**Comment by oceandiff** [comment]
I'm trying with:
`
o.set_oiltype_from_file('/opendrift-master/examples/test_oil/force/oil_test.json')`

I obtain this error:

`raceback (most recent call last):
  File "/media/alessandro/sda/opendrift-master/examples/ramogepol2022/oil1.py", line 12, in <module>
    o.set_oiltype_from_file('/media/alessandro/sda/opendrift-master/examples/ramogepol2022/force/oil_test.json')
  File "/media/alessandro/sda/opendrift-master/opendrift/models/openoil/openoil.py", line 1460, in set_oiltype_from_file
    self.oiltype = adios.oil.OpendriftOil(j)
  File "/media/alessandro/sda/opendrift-master/opendrift/models/openoil/adios/oil.py", line 66, in __init__
    data = o['data']
KeyError: 'data`

where is the problem?

**Comment by gauteh** [comment]
If you specify the file you should use [set_oiltype_from_file](https://opendrift.github.io/autoapi/opendrift/models/openoil/index.html#opendrift.models.openoil.OpenOil.set_oiltype_from_file).

**Comment by gauteh** [comment]
If you use:
* set_oiltype_from_json: you should pass in a dict parsed from json, if you use:
* set_oiltype_from_file: you can just pass in a path to a JSON file like you did. So you can try that first.

**Comment by oceandiff** [comment]
Thank you Gauteh for your help.
If I try with:

`o.set_oiltype_by_json('force/IT0001.json')`

I obtain this error:

`Traceback (most recent call last):
  File "/sda/opendrift-master/examples/oil1.py", line 12, in <module>
    o.set_oiltype_by_json('force/IT0001.json')
  File "/sda/opendrift-master/opendrift/models/openoil/openoil.py", line 1444, in set_oiltype_by_json
    self.oiltype = adios.oil.OpendriftOil(json)
  File "/sda/opendrift-master/opendrift/models/openoil/adios/oil.py", line 66, in __init__
    data = o['data']
TypeError: string indices must be integers
`

and if i try with `o.set_oiltype_from_file('force/IT0001.json')` I obtain another error:

`Traceback (most recent call last):
  File "/sda/opendrift-master/examples/oil1.py", line 12, in <module>
    o.set_oiltype_from_file('force/IT0001.json')
  File "/sda/opendrift-master/opendrift/models/openoil/openoil.py", line 1460, in set_oiltype_from_file
    self.oiltype = adios.oil.OpendriftOil(j)
  File "/sda/opendrift-master/opendrift/models/openoil/adios/oil.py", line 66, in __init__
    data = o['data']
KeyError: 'data'`

surely it is I who make some mistakes, but I can't figure out where.
Have you any idea?
Thank you in advance

**Comment by knutfrode** [comment]
I get the same error.

**Comment by gauteh** [comment]
There are two very similar types of JSON schemas, there could definetely be some confusion on our part on which one to use in which method. One is the type as received by the REST API (where the parameters is in a `data` sub field), the other as the files in the directory. Do you have the chance to post your JSON file here?

**Comment by knutfrode** [comment]
Aha!
I got this error with two of the files in the extra_oils folder.

**Comment by gauteh** [comment]
I've updated the code to use the format as in extra_oils, could you check if it works now?

**Comment by oceandiff** [comment]
Hi Gauteh,
sorry for the delay,
I've tested and the result is the same, if it can help you I am attaching you the json file:
`{
  "oil_id": "TE2022",
  "adios_data_model_version": "0.12.0",
  "metadata": {
    "name": "Fluido RMD 80",
    "source_id": "2022",
    "location": "Taranto",
    "reference": {
      "year": 2022,
      "reference": "Bollettino di analisi Prodotto N° Boll_O1_2022_031166"
    },
    "sample_date": "2022-08-28",
    "product_type": "Olio Combustibile denso",
    "API": 23.036,
    "comments": "ENI",
    "labels": [
      "Crude Oil",
      "Medium Crude"
    ],
    "model_completeness": 14,
    "gnome_suitable": false
  },
  "status": [],
  "review_status": {
    "status": "Not Reviewed"
  },
  "sub_samples": [
    {
      "metadata": {
        "name": "Fresh Oil Sample",
        "short_name": "Fresh Oil",
        "sample_id": "2022",
        "fraction_evaporated": {
          "value": 0,
          "unit": "%",
          "unit_type": "massfraction"
        }
      },
      "physical_properties": {
        "densities": [
          {
            "density": {
              "value": 0.9129,
              "unit": "g/mL",
              "standard_deviation": 0.0001,
              "replicates": 3,
              "unit_type": "density"
            },
            "ref_temp": {
              "value": 15,
              "unit": "C",
              "unit_type": "temperature"
            },
            "method": "ASTM D1298"
          },
          {
            "density": {
              "value": 0.9489,
              "unit": "g/mL",
              "standard_deviation": 0.0001,
              "replicates": 3,
              "unit_type": "density"
            },
            "ref_temp": {
              "value": 0,
              "unit": "C",
              "unit_type": "temperature"
            },
            "method": "ASTM D1298"
          }
        ],
        "dynamic_viscosities": [
            {
              "viscosity": {
               "value": 0.022,
               "unit": "kg/(m s)",
               "unit_type": "dynamicviscosity"
            },
              "ref_temp": {
              "value": 15,
              "unit": "C",
              "unit_type": "temperature"
                 }
             }
        ],
        "kinematic_viscosities": [
            {
              "viscosity": {
               "value": 0.000244,
               "unit": "m^2/s",
               "unit_type": "kinematicviscosity"
            },
              "ref_temp": {
              "value": 15,
              "unit": "C",
              "unit_type": "temperature"
                   }
               }
          ]
      },
      "distillation_data": {
        "cuts": []
      },
      "compounds": [],
      "bulk_composition": [],
      "industry_properties": []
    }
  ]
}
`
