### ISSUE TITLE
reader_grib pygrib.gribmessage marsParam attribute missing

### ISSUE THREAD

**Issue by ShamblingCrane** [OpenDrift/opendrift#99]
I am trying to use the [NOAA's NOMANDS NCEP](https://nomads.ncep.noaa.gov/) wind forecast data data.
[This](Data Transfer: NCEP GFS Forecasts (0.25 degree grid)) is the dataset I am using, and [this](https://nomads.ncep.noaa.gov/cgi-bin/filter_gfs_0p25_1hr.pl?dir=%2Fgfs.2019030400) is the specific series I am trying to read. By using their featured subsetter service to select wind components (UGRD, VGRD) 10 m above ground, I get this [download link](https://nomads.ncep.noaa.gov/cgi-bin/filter_gfs_0p25_1hr.pl?file=gfs.t00z.pgrb2.0p25.f005&lev_10_m_above_ground=on&var_UGRD=on&var_VGRD=on&leftlon=0&rightlon=360&toplat=90&bottomlat=-90&dir=%2Fgfs.2019030400).

I installed the pygrib library only recently via `conda install -c conda-forge pygrib` (I had to re-update gdal afterwards, on a side-note), and I have the **pygrib 2.0.4** version, released as of Feb 14th 2019. My system is **Centos 7.5**.

When I try to instantiate a reader_grib.Reader with the retrieved file, I get the following error:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<path to opendrift within miniconda2>/opendrift/readers/reader_grib.py", line 97, in __init__
    marsParams.append(m.marsParam)
  File "pygrib.pyx", line 843, in pygrib.gribmessage.__getattr__
  File "pygrib.pyx", line 1205, in pygrib.gribmessage.__getitem__
RuntimeError: Key/value not found
```

Line 90-97 of opendrift/readers/reader_grib.py , Reader __init__ method:
```
marsParams = [] 
    for m in self.grib:
    [...] 
    marsParams.append(m.marsParam)
```

If I open the same file via `pygrib.open`, as `reader_grib.Reader` does to set the `self.grib` object (`pygrib.open` object), I can iterate over its content in the same way. 
The type of each m is `pygrib.gribmessage`.
If I print all the fields of any such item via `pprint.pprint(dir(m))` I get:
```
['__class__',
 '__delattr__',
 '__delitem__',
 '__doc__',
 '__format__',
 '__getattr__',
 '__getattribute__',
 '__getitem__',
 '__hash__',
 '__init__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__setitem__',
 '__setstate__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '_all_keys',
 '_get_key',
 '_read_only_keys',
 '_reshape_mask',
 '_ro_keys',
 '_set_projparams',
 '_unshape_mask',
 'analDate',
 'data',
 'expand_grid',
 'expand_reduced',
 'fcstimeunits',
 'has_key',
 'is_missing',
 'keys',
 'latlons',
            (<-marsParam should be here, but it's missing)
 'messagenumber',
 'projparams',
 'tostring',
 'validDate',
 'valid_key']
```

Even downloading sources for pygrib versions 2.0.0-to-2.0.3, I haven't been able to find any reference to this attribute (the 2.0.0 dates back to Dec 29th 2014). I tried with the `ack "marsParam" .` inside the source folder of every release.

I also tried to repeat the procedure with a non-filtered [file](https://nomads.ncep.noaa.gov/pub/data/nccf/com/gfs/prod/gfs.2019030400/gfs.t00z.pgrb2.0p25.f009), from [here](https://nomads.ncep.noaa.gov/pub/data/nccf/com/gfs/prod/gfs.2019030400/), with the same results.

I am not familiar enough with the pygrib library (or the GRIB2 file format) to be able to track down the issue further than this. 
I can only think of a versioning problem (was `reader_grib.py` developed with a 1.x.x version of pygrib?), or a problem with the way this service stores data (maybe the data relative to this attribute is missing in the data stored at NOAA's, and thus the property is not instantiated to save memory?).
In case the problem is the latter, I think a new issue on how to integrate NOAA data sources would be needed.

**Comment by knutfrode** [comment]
Unfortunately this was not answered.
I am temporarily closing/archiving the issue, please reopen if this is still relevant for you.
